table 'Dim Indexering Forecasting'
	lineageTag: a47ea6da-670e-4553-ae3a-e7e0b311e998

	column Indexering
		dataType: double
		formatString: 0.000
		lineageTag: f4ffa6e9-6ec0-4ff1-872b-da261a3d5e9d
		summarizeBy: sum
		sourceColumn: Indexering

		annotation SummarizationSetBy = Automatic

	column 'Index Name'
		dataType: string
		lineageTag: 399c569b-dc40-4c2b-837d-c16111179b6b
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	partition 'Dim Indexering Forecasting' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = List.Generate(
				        () => 0.05, each _ > 0, each _ - 0.01
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Sorted Rows" = Table.Sort(#"Converted to Table",{{"Column1", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"Column1", "Indexering"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Indexering", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Indexering", Percentage.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type1", "Index", 1, 1, Int64.Type),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Index",{{"Index", type text}}),
				    #"Added Suffix" = Table.TransformColumns(#"Changed Type2", {{"Index", each _ & "%", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Suffix",{{"Index", "Index Name"}})
				in 
				    #"Renamed Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

