table 'Dim Indexering Actuals'
	lineageTag: 2775c383-b563-4d0e-9e76-c48d6bff275f

	column Indexering
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bfb264f2-8d84-4677-915f-f858e4a2238b
		summarizeBy: none
		sourceColumn: Indexering

		annotation SummarizationSetBy = Automatic

	column 'Index Name'
		dataType: string
		lineageTag: 69ef15b1-afe9-410a-8f69-0b8d0dfbbdf9
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	partition 'Dim Indexering Actuals' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = List.Numbers(0, 6, 1),  // generates 0 to 5 inclusive
				    Descending = List.Reverse(Source),  // 5 to 0
				    PercentageList = List.Transform(Descending, each _ * 0.01),
				
				    // Convert to table
				    #"Converted to Table" = Table.FromList(PercentageList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Indexering"}}),
				    
				    // Ensure correct type
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Indexering", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Indexering", Percentage.Type}}),
				    
				    // Format index name as percentage with two decimals
				    #"Added Index Name" = Table.AddColumn(#"Changed Type1", "Index Name", each Number.ToText([Indexering], "0.00%"), type text)
				in
				    #"Added Index Name"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

