table 'Dim Vacatures Medewerker'
	lineageTag: c23cc87a-8633-4e3b-99e9-15d2ef927a19

	column Geblokkeerd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 02803fbf-cc71-41f1-979b-5565a5f089ca
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: 777c4e52-c90d-4507-82b0-8fcb207ffe62
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: 56c89e1d-ddf0-49c7-9fa0-8e3f6ef3a74c
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: d51b3332-bacd-4bd1-8162-87aa60c34519
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column 'Cluster_Afdeling Formatieplaats'
		dataType: string
		lineageTag: 3eb60db9-c5da-48e5-97d9-8f0d0841b569
		summarizeBy: none
		sourceColumn: Cluster_Afdeling Formatieplaats

		annotation SummarizationSetBy = Automatic

	column Formatieplaats
		dataType: string
		lineageTag: 33ef58cc-31ba-4355-bee3-324b2afb537a
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column 'Formatieplaats Omschrijving'
		dataType: string
		lineageTag: 4002dcd7-ce95-483f-9b98-d9382de46c78
		summarizeBy: none
		sourceColumn: Formatieplaats Omschrijving

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 4b343272-44de-4a38-9ce6-92d874ccdc68
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Functie
		dataType: string
		lineageTag: 836d7b17-d111-4996-9a44-57157c7c0434
		summarizeBy: none
		sourceColumn: Functie

		annotation SummarizationSetBy = Automatic

	column 'C/A Formatie ID'
		dataType: int64
		formatString: 0
		lineageTag: cbe920bc-5ec5-4501-a55a-3370ebbad1b4
		summarizeBy: none
		sourceColumn: C/A Formatie ID

		annotation SummarizationSetBy = Automatic

	column 'Type Zorg Functie'
		dataType: string
		lineageTag: 2d7f4eef-b5fe-4ab3-8590-eaff95514558
		summarizeBy: none
		sourceColumn: Type Zorg Functie

		annotation SummarizationSetBy = Automatic

	column 'Staf of Zorg'
		dataType: string
		lineageTag: d6eebbbb-78ab-40ed-a4ff-0ae729b9c293
		summarizeBy: none
		sourceColumn: Staf of Zorg

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: ecf1ab72-6ec9-4998-a57a-37ee5be42097
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column Schaal/Trede
		dataType: string
		lineageTag: 5381a3c7-595e-4990-a2d0-90eaaa290be7
		summarizeBy: none
		sourceColumn: Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 7ca558e0-f1ad-4e86-ac88-7aa44f453d0d
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Feesturen flag' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Vacatures'),
			        'Dim Vacatures Medewerker'[Flag Vacatures in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 1e2d974e-94c4-4aa5-b4ba-f59a57baff34
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Vacatures in Fact Forecasting' =
			
			IF(
			    NOT ISBLANK(
			        LOOKUPVALUE(
			            'Fact Forecasting Vacatures'[Formatieplaats],
			            'Fact Forecasting Vacatures'[Formatieplaats],
			            'Dim Vacatures Medewerker'[Formatieplaats]
			        )
			    ),
			    1,
			    0
			)
		formatString: 0
		lineageTag: 483ee1da-fda0-4979-9c68-e2bdea96fdbb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Medische Specialisten' =
			
			IF(
			    'Dim Vacatures Medewerker'[Type Zorg Functie] = "Medisch Specialisten",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 1fb2b5ab-a1cd-4a01-9011-e4cd55045f51
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Maaltijdvergoeding' =
			
			IF(
			    'Dim Vacatures Medewerker'[Flag Medische Specialisten] = 1 ||
			    'Dim Vacatures Medewerker'[Type Personeel ID] = "S_4" ||
			    'Dim Vacatures Medewerker'[Type Personeel ID] = "S_5" ||
			    'Dim Vacatures Medewerker'[Type Personeel ID] = "O_4",
			    0,
			    1
			)
		formatString: 0
		lineageTag: 40057c84-3d10-48c3-b95a-dc62003d51a5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Arts-Assistenten' =
			
			IF(
			    'Dim Vacatures Medewerker'[Type Zorg Functie] = "Arts-assistenten",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 918cb75c-8583-4d71-87d0-886b8bd0d858
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Formatieplaats Coded + Omschrijving' = 'Dim Vacatures Medewerker'[Formatieplaats] & " " & "-" & " " & 'Dim Vacatures Medewerker'[Formatieplaats Omschrijving] & " " & "-" & " " & 'Dim Vacatures Medewerker'[Nr van Vacature]
		lineageTag: e976d3bf-a885-41f8-97ed-61e28738c5a9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Flag Medewerker'
		dataType: double
		lineageTag: 1451df42-4972-4d72-875c-5b88429c977f
		summarizeBy: sum
		sourceColumn: Flag Medewerker

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OE Code'
		dataType: string
		lineageTag: 086683d7-b5ea-43e8-a646-c6db4ffafb64
		summarizeBy: none
		sourceColumn: OE Code

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: f3bd37b7-4564-49f8-b1ca-b1abe5d91e26
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Medewerker ID'
		dataType: string
		lineageTag: b0a5003c-3f42-4ca6-acd2-770b69c30d98
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Voornaam
		dataType: string
		lineageTag: 44282346-ed76-493c-9561-0807101222a9
		summarizeBy: none
		sourceColumn: Voornaam

		annotation SummarizationSetBy = Automatic

	column Salaris
		dataType: double
		lineageTag: 3336d983-6537-48b9-9a0f-74a2779e9cc1
		summarizeBy: sum
		sourceColumn: Salaris

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status_dienstverband
		dataType: string
		lineageTag: 074bcb04-bbbe-4729-87a2-aea9ccf432b4
		summarizeBy: none
		sourceColumn: Status_dienstverband

		annotation SummarizationSetBy = Automatic

	column 'Nr van Vacature'
		dataType: string
		lineageTag: 65a32f68-b2ad-43a9-bafb-999e7784f799
		summarizeBy: none
		sourceColumn: Nr van Vacature

		annotation SummarizationSetBy = Automatic

	column 'Formatieplaats Vacature Nr'
		dataType: string
		lineageTag: c5e05841-6af1-44d3-b6b6-fad7beb58092
		summarizeBy: none
		sourceColumn: Formatieplaats Vacature Nr

		annotation SummarizationSetBy = Automatic

	column 'Naam en Nr Vacature' = 'Dim Vacatures Medewerker'[Voornaam] & " " & "-" & " " & 'Dim Vacatures Medewerker'[Nr van Vacature]
		lineageTag: f48c8e2d-d498-4d6a-a8f8-185dbb662416
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Flag Overtime 200% and 300% Type Personeel' =
			
			IF(
			    ('Dim Vacatures Medewerker'[Flag Medische Specialisten] = 1 || CONTAINSSTRING('Dim Vacatures Medewerker'[Soort_functie], "Echelon 2") || CONTAINSSTRING('Dim Vacatures Medewerker'[Soort_functie], "Echelon 1")) && 'Dim Vacatures Medewerker'[Flag Maaltijdvergoeding] = 0,
			    0,
			    1
			)
		formatString: 0
		lineageTag: 41ec8bd2-0819-45a6-911c-4745e27b16b5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Dim Vacatures Medewerker' = m
		mode: import
		queryGroup: Model
		source = ```
				let 
				    Source = #"Buffered Dim Vacatures Medewerker (STG)",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Functie", "C/A Formatie ID", "Dim Zorg.Type Zorg Functie", "Staf of Zorg", "Type Personeel ID", "Schaal/Trede", "Schaal ID"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Other Columns",{{"Dim Zorg.Type Zorg Functie", "Type Zorg Functie"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns2",{{"Type Zorg Functie", Text.Trim, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Trimmed Text", {"Formatieplaats"}, #"Dim Vacature per Verschil FTE", {"Formatieplaats"}, "Dim Vacature per Verschil FTE", JoinKind.LeftOuter),
				    #"Expanded Dim Vacature per Verschil FTE" = Table.ExpandTableColumn(#"Merged Queries", "Dim Vacature per Verschil FTE", {"Verschil (excl)", "Medewerker ID", "Nr van Vacature"}, {"Verschil (excl)", "Medewerker ID", "Nr van Vacature"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded Dim Vacature per Verschil FTE", "Flag Medewerker", each 0, type nullable number),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"OE", "OE Code"}, {"Omschrijving", "Formatieplaats Omschrijving"}, {"Cluster_Afdeling", "Cluster_Afdeling Formatieplaats"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Voornaam", each "Vacature" & " " & [Formatieplaats Omschrijving], type nullable text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom1",{{"Verschil (excl)", "FTE"}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns1", {"Schaal ID"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries1", "Dim SchaalType", {"Salaris"}, {"Salaris Original"}),
				    #"Added Custom2" = Table.AddColumn(#"Expanded Dim SchaalType", "Salaris", each [Salaris Original] * [FTE], type nullable number),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom2",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling Formatieplaats", "Formatieplaats", "Formatieplaats Omschrijving", "Kostenplaats", "OE Code", "Functie", "C/A Formatie ID", "Type Zorg Functie", "Staf of Zorg", "Type Personeel ID", "Schaal/Trede", "Schaal ID", "FTE", "Medewerker ID", "Nr van Vacature", "Flag Medewerker", "Voornaam", "Salaris"}),
				    #"Added Custom3" = Table.AddColumn(#"Removed Other Columns1", "Status_dienstverband", each "In dienst", type nullable text),
				    #"Transform Nr Vac" = Table.TransformColumns(#"Added Custom3", {{"Nr van Vacature", each Text.PadStart(Text.From(_), 2, "0"), type nullable text}}),
				    #"Added Custom4" = Table.AddColumn(#"Transform Nr Vac", "Formatieplaats Vacature Nr", each [Formatieplaats] & " " & "-" & " " & Text.From([Nr van Vacature]), type nullable text)
				in
				    #"Added Custom4"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

