table 'Dim Medewerkers'
	lineageTag: 81a5f0d1-0764-4ac7-a5c6-f2a44a93fcfe

	column 'Medewerker ID'
		dataType: string
		lineageTag: c24ca489-f9ed-4669-8da4-15157870f3b2
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Voornaam
		dataType: string
		lineageTag: c438a01a-9f65-43b4-bb7e-8fc152c4e4e2
		summarizeBy: none
		sourceColumn: Voornaam

		annotation SummarizationSetBy = Automatic

	column Achternaam
		dataType: string
		lineageTag: 150f88e2-9df5-4c8d-8142-d8e88b6309d8
		summarizeBy: none
		sourceColumn: Achternaam

		annotation SummarizationSetBy = Automatic

	column E-mail_werk
		dataType: string
		lineageTag: 1a5e9eab-5988-4de4-a07d-1c13f6522be0
		summarizeBy: none
		sourceColumn: E-mail_werk

		annotation SummarizationSetBy = Automatic

	column Geboortedatum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 85fc103b-1c3d-4c27-85ca-65d74b438254
		summarizeBy: none
		sourceColumn: Geboortedatum

		variation Variation
			isDefault
			relationship: 95b79e81-d8b3-4717-83b9-99b397357e2d
			defaultHierarchy: LocalDateTable_d8464d1c-c5b8-4e55-885d-98be5114bbb6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Geslacht
		dataType: string
		lineageTag: 10411ccc-533e-488d-9b07-65252cd353ab
		summarizeBy: none
		sourceColumn: Geslacht

		annotation SummarizationSetBy = Automatic

	column Leeftijd
		dataType: string
		lineageTag: ca4f8edf-1372-4991-8323-d70ee3494737
		summarizeBy: none
		sourceColumn: Leeftijd

		annotation SummarizationSetBy = Automatic

	column Status_dienstverband
		dataType: string
		lineageTag: 0da2fd39-2c09-4d83-a094-4b7f0bd15d7a
		summarizeBy: none
		sourceColumn: Status_dienstverband

		annotation SummarizationSetBy = Automatic

	column Geblokkeerd
		dataType: string
		lineageTag: a864d0bb-b5fa-4e88-9570-b3cefc6f1928
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Dienstbetrekking
		dataType: string
		lineageTag: eff798ef-36b1-4f90-8f09-eef89c25ee1e
		summarizeBy: none
		sourceColumn: Dienstbetrekking

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: 3fcb608a-e607-4fe7-b8c9-c6b213123b04
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column Begindatum_salaris
		dataType: dateTime
		formatString: Long Date
		lineageTag: 272163f0-9bfe-416c-bc78-b09e9261a728
		summarizeBy: none
		sourceColumn: Begindatum_salaris

		variation Variation
			isDefault
			relationship: 7d91547c-4632-4cfa-ab75-079edb7412e6
			defaultHierarchy: LocalDateTable_90566a9f-1ad9-4ebf-9102-b08c09f77e5e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Einddatum_salaris
		dataType: dateTime
		formatString: Long Date
		lineageTag: add43a4f-a69a-48e0-9e94-c0f1c115155d
		summarizeBy: none
		sourceColumn: Einddatum_salaris

		variation Variation
			isDefault
			relationship: 08c12b56-66fb-4f13-9e49-26c53321dc2c
			defaultHierarchy: LocalDateTable_ae3566aa-e5a6-4164-88b7-9c730a13454b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Begindatum_functie
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa8cb740-a642-4a61-ab21-8f3176cb3edc
		summarizeBy: none
		sourceColumn: Begindatum_functie

		variation Variation
			isDefault
			relationship: 4c51f2ea-e59e-4e94-a9c4-73a79c325805
			defaultHierarchy: LocalDateTable_bdc0e247-3e10-4793-a0ca-770323ec1c1a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Schaal
		dataType: string
		lineageTag: 5a7a8bcb-4e55-4fc9-8acd-f75a0f6e595a
		summarizeBy: none
		sourceColumn: Schaal

		annotation SummarizationSetBy = Automatic

	column Soort_medewerker
		dataType: string
		lineageTag: e032566a-6d95-440d-ab36-bde9f71e61f6
		summarizeBy: none
		sourceColumn: Soort_medewerker

		annotation SummarizationSetBy = Automatic

	column Type_contract
		dataType: string
		lineageTag: cc086877-d9f7-4f06-8c22-930959562c39
		summarizeBy: none
		sourceColumn: Type_contract

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: 9a3fccb0-cc2f-4b31-ade6-c20e5b3bc34d
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies_2
		dataType: string
		lineageTag: 74f16a93-7c54-48ac-8cbc-2cd926b72df8
		summarizeBy: none
		sourceColumn: Patientgebonden_functies_2

		annotation SummarizationSetBy = Automatic

	partition 'Dim Medewerkers' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Json.Document(Web.Contents("https://86331.rest.afas.online/ProfitRestServices/connectors/CMC_WeergaveBP" & "?skip=0&take=500000", [Headers=[Authorization="AfasToken PHRva2VuPjx2ZXJzaW9uPjE8L3ZlcnNpb24+PGRhdGE+Qjk5N0I1MjNGMzhENDgwNjgyRTA0NzQ4RkZCQUQ1RjU5MTA1OEU3QUEwQTQ0MDMxODlBNUVGNTNEMjFDREQ5MTwvZGF0YT48L3Rva2VuPg=="]])),
				    rows = Source[rows],
				    #"Converted to Table" = Table.FromList(rows, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Medewerker", "Roepnaam", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving", "Geboorteplaats", "Geslacht", "Leeftijd", "Datum_in_dienst", "Formatieplaats", "Omschrijving_3", "Omschrijving_3_2", "Datum_uit_dienst", "Dienstverband", "Dienstverband_2", "Status_dienstverband", "Kostenplaats", "Omschrijving_4", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Initiatief", "Dienstjaren", "Cluster_Afdeling", "Dienstbetrekking", "Nationaliteit", "Functie_2", "Omschrijving_4_2", "In_opleiding", "Cluster_Afdeling_2", "Patientgebonden_functies", "Patientgebonden_functies_2", "Soort_functie", "In_dienst__i.v.m._dienstjaren_", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Volgnummer", "Formatieplaats_2", "Omschrijving_5", "Service_Lines", "Service_Line_Type", "Cluster_Afdeling_3", "Organisatorische_eenheid_2", "Omschrijving_6", "Soort_medewerker", "Type_contract"}, {"Medewerker", "Roepnaam", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving", "Geboorteplaats", "Geslacht", "Leeftijd", "Datum_in_dienst", "Formatieplaats", "Omschrijving_3", "Omschrijving_3_2", "Datum_uit_dienst", "Dienstverband", "Dienstverband_2", "Status_dienstverband", "Kostenplaats", "Omschrijving_4", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Initiatief", "Dienstjaren", "Cluster_Afdeling", "Dienstbetrekking", "Nationaliteit", "Functie_2", "Omschrijving_4_2", "In_opleiding", "Cluster_Afdeling_2", "Patientgebonden_functies", "Patientgebonden_functies_2", "Soort_functie", "In_dienst__i.v.m._dienstjaren_", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Volgnummer", "Formatieplaats_2", "Omschrijving_5", "Service_Lines", "Service_Line_Type", "Cluster_Afdeling_3", "Organisatorische_eenheid_2", "Omschrijving_6", "Soort_medewerker", "Type_contract"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Column1",{"Medewerker", "Voornaam", "Achternaam", "E-mail_werk", "Geboortedatum", "Geslacht", "Leeftijd", "Status_dienstverband", "Geblokkeerd", "Dienstbetrekking", "Patientgebonden_functies", "Patientgebonden_functies_2", "Soort_functie", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Schaal", "Soort_medewerker", "Type_contract"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Medewerker"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each ([Status_dienstverband] <> "Uit dienst")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Medewerker", "Medewerker ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Geboortedatum", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Geboortedatum", type date}, {"Begindatum_salaris", type datetime}, {"Einddatum_salaris", type datetime}, {"Begindatum_functie", type datetime}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"Begindatum_salaris", type date}, {"Einddatum_salaris", type date}, {"Begindatum_functie", type date}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

