table 'Dim Vacatures Medewerker'
	lineageTag: c23cc87a-8633-4e3b-99e9-15d2ef927a19

	column Geblokkeerd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 02803fbf-cc71-41f1-979b-5565a5f089ca
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: 777c4e52-c90d-4507-82b0-8fcb207ffe62
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: 56c89e1d-ddf0-49c7-9fa0-8e3f6ef3a74c
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: d51b3332-bacd-4bd1-8162-87aa60c34519
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column Cluster_Afdeling
		dataType: string
		lineageTag: 3eb60db9-c5da-48e5-97d9-8f0d0841b569
		summarizeBy: none
		sourceColumn: Cluster_Afdeling

		annotation SummarizationSetBy = Automatic

	column Formatieplaats
		dataType: string
		lineageTag: 33ef58cc-31ba-4355-bee3-324b2afb537a
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column 'Formatieplaats Omschrijving'
		dataType: string
		lineageTag: 4002dcd7-ce95-483f-9b98-d9382de46c78
		summarizeBy: none
		sourceColumn: Formatieplaats Omschrijving

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 4b343272-44de-4a38-9ce6-92d874ccdc68
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Functie
		dataType: string
		lineageTag: 836d7b17-d111-4996-9a44-57157c7c0434
		summarizeBy: none
		sourceColumn: Functie

		annotation SummarizationSetBy = Automatic

	column 'C/A Formatie ID'
		dataType: int64
		formatString: 0
		lineageTag: cbe920bc-5ec5-4501-a55a-3370ebbad1b4
		summarizeBy: none
		sourceColumn: C/A Formatie ID

		annotation SummarizationSetBy = Automatic

	column 'Type Zorg Functie'
		dataType: string
		lineageTag: 2d7f4eef-b5fe-4ab3-8590-eaff95514558
		summarizeBy: none
		sourceColumn: Type Zorg Functie

		annotation SummarizationSetBy = Automatic

	column 'Staf of Zorg'
		dataType: string
		lineageTag: d6eebbbb-78ab-40ed-a4ff-0ae729b9c293
		summarizeBy: none
		sourceColumn: Staf of Zorg

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: ecf1ab72-6ec9-4998-a57a-37ee5be42097
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: double
		formatString: 0
		lineageTag: 7ca558e0-f1ad-4e86-ac88-7aa44f453d0d
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Feesturen flag' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Vacatures'),
			        'Dim Vacatures Medewerker'[Flag Vacatures in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 1e2d974e-94c4-4aa5-b4ba-f59a57baff34
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Vacatures in Fact Forecasting' =
			
			IF(
			    NOT ISBLANK(
			        LOOKUPVALUE(
			            'Fact Forecasting Vacatures'[Formatieplaats],
			            'Fact Forecasting Vacatures'[Formatieplaats],
			            'Dim Vacatures Medewerker'[Formatieplaats]
			        )
			    ),
			    1,
			    0
			)
		formatString: 0
		lineageTag: 483ee1da-fda0-4979-9c68-e2bdea96fdbb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Medische Specialisten' =
			
			IF(
			    'Dim Vacatures Medewerker'[Type Zorg Functie] = "Medisch Specialisten",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 1fb2b5ab-a1cd-4a01-9011-e4cd55045f51
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Maaltijdvergoeding' =
			
			IF(
			    'Dim Vacatures Medewerker'[Flag Medische Specialisten] = 1 ||
			    'Dim Vacatures Medewerker'[Type Personeel ID] = "S_4" ||
			    'Dim Vacatures Medewerker'[Type Personeel ID] = "S_5" ||
			    'Dim Vacatures Medewerker'[Type Personeel ID] = "O_4",
			    0,
			    1
			)
		formatString: 0
		lineageTag: 40057c84-3d10-48c3-b95a-dc62003d51a5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Arts-Assistenten' =
			
			IF(
			    'Dim Vacatures Medewerker'[Type Zorg Functie] = "Arts-assistenten",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 918cb75c-8583-4d71-87d0-886b8bd0d858
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Formatieplaats Coded + Omschrijving' = 'Dim Vacatures Medewerker'[Formatieplaats] & " " & "-" & " " & 'Dim Vacatures Medewerker'[Formatieplaats Omschrijving] & " " & "-" & " " & 'Dim Vacatures Medewerker'[Nr van Vacature]
		lineageTag: e976d3bf-a885-41f8-97ed-61e28738c5a9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Verschil (excl)'
		dataType: double
		lineageTag: f3bd37b7-4564-49f8-b1ca-b1abe5d91e26
		summarizeBy: sum
		sourceColumn: Verschil (excl)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Medewerker ID'
		dataType: string
		lineageTag: b0a5003c-3f42-4ca6-acd2-770b69c30d98
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Salaris
		dataType: double
		lineageTag: 3336d983-6537-48b9-9a0f-74a2779e9cc1
		summarizeBy: sum
		sourceColumn: Salaris

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nr van Vacature'
		dataType: string
		lineageTag: 65a32f68-b2ad-43a9-bafb-999e7784f799
		summarizeBy: none
		sourceColumn: Nr van Vacature

		annotation SummarizationSetBy = Automatic

	column 'Naam en Nr Vacature' = 'Dim Vacatures Medewerker'[Voornaam] & " " & "-" & " " & 'Dim Vacatures Medewerker'[Nr van Vacature]
		lineageTag: f48c8e2d-d498-4d6a-a8f8-185dbb662416
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Flag Overtime 200% and 300% Type Personeel' =
			
			IF(
			    ('Dim Vacatures Medewerker'[Flag Medische Specialisten] = 1 || CONTAINSSTRING('Dim Vacatures Medewerker'[Soort_functie], "Echelon 2") || CONTAINSSTRING('Dim Vacatures Medewerker'[Soort_functie], "Echelon 1")) && 'Dim Vacatures Medewerker'[Flag Maaltijdvergoeding] = 0,
			    0,
			    1
			)
		formatString: 0
		lineageTag: 41ec8bd2-0819-45a6-911c-4745e27b16b5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Declarerend_Niet-declarerend
		dataType: string
		lineageTag: 5de15dd7-c1da-4be1-9c46-e2b3a883986f
		summarizeBy: none
		sourceColumn: Declarerend_Niet-declarerend

		annotation SummarizationSetBy = Automatic

	column Service_Line_Type
		dataType: string
		lineageTag: 03f8f6ec-2a72-483c-bae9-0bdece104436
		summarizeBy: none
		sourceColumn: Service_Line_Type

		annotation SummarizationSetBy = Automatic

	column Service_Lines
		dataType: string
		lineageTag: 59e92323-a961-4484-8ade-fcec08b8f7ab
		summarizeBy: none
		sourceColumn: Service_Lines

		annotation SummarizationSetBy = Automatic

	column OE
		dataType: string
		lineageTag: dbae704a-e5be-412c-9c6e-32c24cc8dd20
		summarizeBy: none
		sourceColumn: OE

		annotation SummarizationSetBy = Automatic

	column Omschrijving_2
		dataType: string
		lineageTag: a1e15106-49ed-4a6a-8bf8-ac1ec864e7b9
		summarizeBy: none
		sourceColumn: Omschrijving_2

		annotation SummarizationSetBy = Automatic

	column Omschrijving_3
		dataType: string
		lineageTag: 5f8497ae-2877-4e7f-910a-38b95cc206cb
		summarizeBy: none
		sourceColumn: Omschrijving_3

		annotation SummarizationSetBy = Automatic

	column Generieke_functienaam
		dataType: string
		lineageTag: 6011ae77-42b4-448f-beb3-437d6e2d0078
		summarizeBy: none
		sourceColumn: Generieke_functienaam

		annotation SummarizationSetBy = Automatic

	column 'Begin Datum'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea3b33da-c3b3-4831-97be-5ce64201aa64
		summarizeBy: none
		sourceColumn: Begin Datum

		variation Variation
			isDefault
			relationship: 09433c0e-5e49-4764-8cbe-dd655f68ebe4
			defaultHierarchy: LocalDateTable_1037b00d-2c0f-4ada-adf0-f563bcdcf480.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Eind Datum'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a25f2ec4-5f9d-436b-bc26-ecc0813098ae
		summarizeBy: none
		sourceColumn: Eind Datum

		variation Variation
			isDefault
			relationship: 81ef511e-4f05-4a42-9d9a-e03435b5074d
			defaultHierarchy: LocalDateTable_ce44edf7-627d-4c86-9285-960f0aab00bb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Max Schaal/Trede'
		dataType: string
		lineageTag: ea0fc220-99d9-4639-9f7e-be9151c750eb
		summarizeBy: none
		sourceColumn: Max Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column SchaalType
		dataType: string
		lineageTag: dcf5ee39-16a2-4c0b-8289-ce3a9e8fbb03
		summarizeBy: none
		sourceColumn: SchaalType

		annotation SummarizationSetBy = Automatic

	partition 'Dim Vacatures Medewerker' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Json.Document(Web.Contents("https://86331.rest.afas.online/ProfitRestServices/connectors/CMC_Formatieplaats" & "?skip=-1&take=-1", [Headers=[Authorization="AfasToken PHRva2VuPjx2ZXJzaW9uPjE8L3ZlcnNpb24+PGRhdGE+Qjk5N0I1MjNGMzhENDgwNjgyRTA0NzQ4RkZCQUQ1RjU5MTA1OEU3QUEwQTQ0MDMxODlBNUVGNTNEMjFDREQ5MTwvZGF0YT48L3Rva2VuPg=="]])),
				    rows = Source[rows],
				    #"Converted to Table" = Table.FromList(rows, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}, {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"Geblokkeerd", type logical}, {"Naam_werkgever", type text}, {"Patientgebonden_functies", type text}, {"Soort_functie", type text}, {"Declarerend_Niet-declarerend", type text}, {"Service_Lines", type text}, {"Cluster_Afdeling", type text}, {"Omschrijving", type text}, {"Formatieplaats", type text}, {"Kostenplaats", Int64.Type}, {"Organisatorische_eenheid", type text}, {"Omschrijving_2", type text}, {"Functie", type text}, {"Omschrijving_3", type text}, {"Generieke_functienaam", type text}, {"Gebruiker", type text}, {"Type_functie", type text}, {"Naam", type text}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([Einddatum], "T"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Text Before Delimiter", "Eind Datum"}}),
				    #"Inserted Text Before Delimiter1" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Begindatum], "T"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Before Delimiter1",{{"Text Before Delimiter", "Begin Datum"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Begin Datum", type date}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum"}),
				    #"Inserted Text Before Delimiter2" = Table.AddColumn(#"Reordered Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Gewijzigd], "T"), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Text Before Delimiter2",{{"Text Before Delimiter", "Datum Gewijzigd"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Datum Gewijzigd", type date}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Changed Type3", "Text After Delimiter", each Text.AfterDelimiter([Gewijzigd], "T"), type text),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Inserted Text After Delimiter", {{"Text After Delimiter", each Text.BeforeDelimiter(_, "Z"), type text}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Extracted Text Before Delimiter",{{"Text After Delimiter", "Tijd Gewijzigd"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Tijd Gewijzigd", type time}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type4",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum", "Datum Gewijzigd", "Tijd Gewijzigd"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Aantal_FTE_2", type number}, {"Aantal_FTE", type number}, {"Aantal_FTE_3", type number}, {"Aantal_FTE_4", type number}, {"Verschil", type number}, {"FTE_Begroot", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type5", "Uren_Begroot", each [FTE_Begroot] * 8),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Uren_Werkelijk", each [Aantal_FTE] * 8),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Uren_Verschil", each [Verschil] * 8),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom2",{{"Uren_Begroot", type number}, {"Uren_Werkelijk", type number}, {"Uren_Verschil", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type6", each ([Naam_werkgever] = "Curacao Medical Center Exploitatie")),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Filtered Rows",{{"Kostenplaats", type text}}),
				    #"Renamed Columns8" = Table.RenameColumns(#"Changed Type7",{{"Aantal_FTE", "Werkelijk"}, {"Aantal_FTE_2", "Instroom"}, {"Aantal_FTE_3", "FTE uitstroom (zonder bepaalde tijd)"}, {"Verschil", "Verschil (excl) Original"}, {"Aantal_FTE_4", "Verschil"}, {"Organisatorische_eenheid", "OE"}, {"FTE_Begroot", "FTE_Begroot Original"}, {"Begin Datum", "Begin Datum Original"}, {"Eind Datum", "Eind Datum Original"}}),
				    #"Merged Queries9" = Table.NestedJoin(#"Renamed Columns8", {"Formatieplaats"}, Formatiebegroting, {"Formatieplaats"}, "Formatiebegroting", JoinKind.LeftOuter),
				    #"Expanded Formatiebegroting" = Table.ExpandTableColumn(#"Merged Queries9", "Formatiebegroting", {"Begindatum", "Einddatum", "FTE_Begroot"}, {"Begindatum", "Einddatum", "FTE_Begroot"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Expanded Formatiebegroting",{{"Begindatum", "Begin Datum"}, {"Einddatum", "Eind Datum"}}),
				    #"Added Custom5" = Table.AddColumn(#"Renamed Columns5", "Verschil (excl)", each [FTE_Begroot] - [Werkelijk], type nullable number),
				    #"Removed Other Columns3" = Table.SelectColumns(#"Added Custom5",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Werkelijk", "Instroom", "FTE uitstroom (zonder bepaalde tijd)", "Verschil", "Gebruiker", "Type_functie", "Naam", "Datum Gewijzigd", "Tijd Gewijzigd", "Uren_Begroot", "Uren_Werkelijk", "Uren_Verschil", "Begin Datum", "Eind Datum", "FTE_Begroot", "Verschil (excl)"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Other Columns3", each [#"Verschil (excl)"] > 0),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows1",{{"Formatieplaats", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns7" = Table.RenameColumns(#"Added Index",{{"Index", "Medewerker ID"}}),
				    #"Tranform Mdw ID" = Table.TransformColumns(#"Renamed Columns7", {{"Medewerker ID", each Text.PadStart(Text.From(_), 5, "0"), type text}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Tranform Mdw ID",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Werkelijk", "Instroom", "FTE uitstroom (zonder bepaalde tijd)", "Verschil", "Verschil (excl)", "Begin Datum", "Eind Datum", "Uren_Begroot", "Uren_Werkelijk", "Uren_Verschil", "Medewerker ID"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns1", {"Cluster_Afdeling"}, #"Dim Cluster/Afdeling Formatieplaats", {"Cluster/Afdeling Formatieplaatsniveau"}, "Dim Cluster/Afdeling Formatieplaats", JoinKind.LeftOuter),
				    #"Expanded Dim Cluster/Afdeling Formatieplaats" = Table.ExpandTableColumn(#"Merged Queries", "Dim Cluster/Afdeling Formatieplaats", {"C/A Formatie ID"}, {"C/A Formatie ID"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim Cluster/Afdeling Formatieplaats", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling"}, #"Dim Staf", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Staf", JoinKind.LeftOuter),
				    #"Expanded Dim Staf" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Staf", {"Staf of Zorg"}, {"Dim Staf.Staf of Zorg"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Dim Staf", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling"}, #"Dim Zorg", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Zorg", JoinKind.LeftOuter),
				    #"Expanded Dim Zorg" = Table.ExpandTableColumn(#"Merged Queries2", "Dim Zorg", {"Type Zorg Functie", "Staf of Zorg"}, {"Dim Zorg.Type Zorg Functie", "Dim Zorg.Staf of Zorg"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Dim Zorg", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling"}, #"Dim Medewerker Overig", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Medewerker Overig", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker Overig" = Table.ExpandTableColumn(#"Merged Queries3", "Dim Medewerker Overig", {"Staf of Zorg"}, {"Dim Medewerker Overig.Staf of Zorg"}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Expanded Dim Medewerker Overig", {{"Dim Medewerker Overig.Staf of Zorg", type text}}, "en-US"),{"Dim Staf.Staf of Zorg", "Dim Zorg.Staf of Zorg", "Dim Medewerker Overig.Staf of Zorg"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Staf of Zorg"),
				    #"Trimmed Text" = Table.TransformColumns(#"Merged Columns",{{"Dim Zorg.Type Zorg Functie", Text.Trim, type text}}),
				    #"Merged Queries4" = Table.NestedJoin(#"Trimmed Text", {"Soort_functie", "Dim Zorg.Type Zorg Functie", "Staf of Zorg"}, #"Dim Type Personeel", {"Soort_functie", "Type Zorg Functie", "Staf of Zorg"}, "Dim Type Personeel", JoinKind.LeftOuter),
				    #"Expanded Dim Type Personeel" = Table.ExpandTableColumn(#"Merged Queries4", "Dim Type Personeel", {"Type Personeel ID"}, {"Type Personeel ID"}),
				    #"Added Custom3" = Table.AddColumn(#"Expanded Dim Type Personeel", "Line ID (MdWID_Formatieplaats)", each Text.From([Medewerker ID]) & "_" & Text.From([Formatieplaats])),
				    #"Merged Queries5" = Table.NestedJoin(#"Added Custom3", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats CAO (Correct One)", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats CAO", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats CAO" = Table.ExpandTableColumn(#"Merged Queries5", "Dim Schaal per Formatieplaats CAO", {"Max Schaal/Trede", "Schaal ID", "SchaalType", "Salaris"}, {"CAO.Max Schaal/Trede", "CAO.Schaal ID", "CAO.SchaalType", "CAO.Salaris"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Expanded Dim Schaal per Formatieplaats CAO", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats BMP/LNT (Correct One)", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats LNT", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats LNT" = Table.ExpandTableColumn(#"Merged Queries6", "Dim Schaal per Formatieplaats LNT", {"SchaalType", "Max Schaal/Trede", "Salaris", "Schaal ID"}, {"LNT.SchaalType", "LNT.Max Schaal/Trede", "LNT.Salaris", "LNT.Schaal ID"}),
				    #"Merged Columns1" = Table.CombineColumns(#"Expanded Dim Schaal per Formatieplaats LNT",{"CAO.Max Schaal/Trede", "LNT.Max Schaal/Trede"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Max Schaal/Trede"),
				    #"Added Custom4" = Table.AddColumn(#"Merged Columns1", "Schaal ID", each if [CAO.Schaal ID] = null then [LNT.Schaal ID] else [CAO.Schaal ID], type nullable number),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom4", "SchaalType", each if [CAO.SchaalType] = null then [LNT.SchaalType] else [CAO.SchaalType], type nullable text),
				    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Salaris", each if [CAO.Salaris] = null then [LNT.Salaris] else [CAO.Salaris], type nullable number),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Added Custom7",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begin Datum", "Eind Datum", "C/A Formatie ID", "Dim Zorg.Type Zorg Functie", "Staf of Zorg", "Type Personeel ID", "Max Schaal/Trede", "Schaal ID", "SchaalType", "Salaris"}),
				    #"Merged Queries7" = Table.NestedJoin(#"Removed Other Columns2", {"Formatieplaats"}, #"Dim Vacature per Verschil FTE Test", {"Formatieplaats"}, "Dim Vacature per Verschil FTE Test", JoinKind.LeftOuter),
				    #"Expanded Dim Vacature per Verschil FTE Test" = Table.ExpandTableColumn(#"Merged Queries7", "Dim Vacature per Verschil FTE Test", {"Verschil (excl)", "Medewerker ID", "Nr van Vacature"}, {"Verschil (excl)", "Medewerker ID", "Nr van Vacature"}),
				    #"Transform Nr Vac" = Table.TransformColumns(#"Expanded Dim Vacature per Verschil FTE Test", {{"Nr van Vacature", each Text.PadStart(Text.From(_), 2, "0"), type nullable text}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Transform Nr Vac",{{"Dim Zorg.Type Zorg Functie", "Type Zorg Functie"}, {"Omschrijving", "Formatieplaats Omschrijving"}})
				in
				    #"Renamed Columns4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

