table 'Dim Indexering Actuals'
	lineageTag: 2775c383-b563-4d0e-9e76-c48d6bff275f

	column Indexering
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bfb264f2-8d84-4677-915f-f858e4a2238b
		summarizeBy: sum
		sourceColumn: Indexering

		annotation SummarizationSetBy = Automatic

	column 'Index Name'
		dataType: string
		lineageTag: 475e2d43-3789-4fc2-8830-a9c72730c21f
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	partition 'Dim Indexering Actuals' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = List.Generate(
				        () => 0.05, each _ > 0, each _ - 0.01
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Sorted Rows" = Table.Sort(#"Converted to Table",{{"Column1", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"Column1", "Indexering"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Indexering", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Indexering", Percentage.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type1", "Index", 1, 1, Int64.Type),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Index",{{"Index", type text}}),
				    #"Added Suffix" = Table.TransformColumns(#"Changed Type2", {{"Index", each _ & "%", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Suffix",{{"Index", "Index Name"}})
				in 
				    #"Renamed Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

