table 'Dim Vacatures Medewerker'
	lineageTag: c23cc87a-8633-4e3b-99e9-15d2ef927a19

	column Geblokkeerd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 02803fbf-cc71-41f1-979b-5565a5f089ca
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: 777c4e52-c90d-4507-82b0-8fcb207ffe62
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: 56c89e1d-ddf0-49c7-9fa0-8e3f6ef3a74c
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: d51b3332-bacd-4bd1-8162-87aa60c34519
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column Declarerend_Niet-declarerend
		dataType: string
		lineageTag: abc4dcf5-1f15-43a4-9665-934076245216
		summarizeBy: none
		sourceColumn: Declarerend_Niet-declarerend

		annotation SummarizationSetBy = Automatic

	column Service_Line_Type
		dataType: string
		lineageTag: 0af46e00-fc64-4c1b-9632-df08803f74cd
		summarizeBy: none
		sourceColumn: Service_Line_Type

		annotation SummarizationSetBy = Automatic

	column Service_Lines
		dataType: string
		lineageTag: eaf51365-224d-47bc-8962-8673a8dad2ab
		summarizeBy: none
		sourceColumn: Service_Lines

		annotation SummarizationSetBy = Automatic

	column Cluster_Afdeling
		dataType: string
		lineageTag: 3eb60db9-c5da-48e5-97d9-8f0d0841b569
		summarizeBy: none
		sourceColumn: Cluster_Afdeling

		annotation SummarizationSetBy = Automatic

	column Formatieplaats
		dataType: string
		lineageTag: 33ef58cc-31ba-4355-bee3-324b2afb537a
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		lineageTag: 4002dcd7-ce95-483f-9b98-d9382de46c78
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 4b343272-44de-4a38-9ce6-92d874ccdc68
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column OE
		dataType: string
		lineageTag: 8a2daf21-c42c-4532-b36d-72cfb0f97e1f
		summarizeBy: none
		sourceColumn: OE

		annotation SummarizationSetBy = Automatic

	column Omschrijving_2
		dataType: string
		lineageTag: c84f3843-6a37-4849-9fe1-ae6569693dd7
		summarizeBy: none
		sourceColumn: Omschrijving_2

		annotation SummarizationSetBy = Automatic

	column Functie
		dataType: string
		lineageTag: 836d7b17-d111-4996-9a44-57157c7c0434
		summarizeBy: none
		sourceColumn: Functie

		annotation SummarizationSetBy = Automatic

	column Omschrijving_3
		dataType: string
		lineageTag: 4bd7a16f-e048-44fd-91a9-db3b27d1ecff
		summarizeBy: none
		sourceColumn: Omschrijving_3

		annotation SummarizationSetBy = Automatic

	column Generieke_functienaam
		dataType: string
		lineageTag: af5353d0-66cc-4177-a95b-51e2a91ab282
		summarizeBy: none
		sourceColumn: Generieke_functienaam

		annotation SummarizationSetBy = Automatic

	column FTE_Begroot
		dataType: double
		lineageTag: 220ef26e-d521-40a5-a476-52a74d4bc53f
		summarizeBy: sum
		sourceColumn: FTE_Begroot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Werkelijk
		dataType: double
		lineageTag: 585093ec-b05c-4913-9ca7-c70695038c19
		summarizeBy: sum
		sourceColumn: Werkelijk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Instroom
		dataType: double
		lineageTag: 6b0428bd-be44-49ad-b008-562a5115d772
		summarizeBy: sum
		sourceColumn: Instroom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FTE uitstroom (zonder bepaalde tijd)'
		dataType: double
		lineageTag: d1033d97-10b2-46cc-9832-7619d7a4a4b5
		summarizeBy: sum
		sourceColumn: FTE uitstroom (zonder bepaalde tijd)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Verschil
		dataType: double
		lineageTag: ea4895b5-0e6a-46de-a254-7c231e959b6e
		summarizeBy: sum
		sourceColumn: Verschil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Verschil (excl)'
		dataType: double
		lineageTag: a65dbfda-ec2c-4765-9de8-7ca8b18655af
		summarizeBy: sum
		sourceColumn: Verschil (excl)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Begin Datum'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bb8a374d-a2a3-40e8-bc33-95649c8f627e
		summarizeBy: none
		sourceColumn: Begin Datum

		variation Variation
			isDefault
			relationship: ab72dbc2-501c-4fea-93b5-14b1181c507a
			defaultHierarchy: LocalDateTable_10b1e95f-df4b-4b17-adb3-71e2077a9514.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Eind Datum'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8012fc7c-eb84-4711-996b-5264c2a8e481
		summarizeBy: none
		sourceColumn: Eind Datum

		variation Variation
			isDefault
			relationship: 2a5b9733-d09a-48d3-8f99-49d783a73e2f
			defaultHierarchy: LocalDateTable_afb99120-4be0-4e49-9559-55267239d78e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Uren_Begroot
		dataType: double
		lineageTag: 49fa82f1-0030-4e1b-92a1-36f4411f1990
		summarizeBy: sum
		sourceColumn: Uren_Begroot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uren_Werkelijk
		dataType: double
		lineageTag: 5a5a9495-5c7c-414d-8327-9ebeaceef3eb
		summarizeBy: sum
		sourceColumn: Uren_Werkelijk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uren_Verschil
		dataType: double
		lineageTag: 6d84c574-0c18-4d07-9240-767bb6714b7d
		summarizeBy: sum
		sourceColumn: Uren_Verschil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Medewerker ID'
		dataType: int64
		formatString: 0
		lineageTag: f2fb4358-7863-4808-88ba-de50fc75cff8
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column 'C/A Formatie ID'
		dataType: int64
		formatString: 0
		lineageTag: cbe920bc-5ec5-4501-a55a-3370ebbad1b4
		summarizeBy: none
		sourceColumn: C/A Formatie ID

		annotation SummarizationSetBy = Automatic

	column 'Dim Zorg.Type Zorg Functie'
		dataType: string
		lineageTag: 2d7f4eef-b5fe-4ab3-8590-eaff95514558
		summarizeBy: none
		sourceColumn: Dim Zorg.Type Zorg Functie

		annotation SummarizationSetBy = Automatic

	column 'Staf of Zorg'
		dataType: string
		lineageTag: d6eebbbb-78ab-40ed-a4ff-0ae729b9c293
		summarizeBy: none
		sourceColumn: Staf of Zorg

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: ecf1ab72-6ec9-4998-a57a-37ee5be42097
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Line ID (MdWID_Formatieplaats)'
		dataType: string
		lineageTag: bc20b587-f073-4188-916e-1290fe7a96ca
		summarizeBy: none
		sourceColumn: Line ID (MdWID_Formatieplaats)

		annotation SummarizationSetBy = Automatic

	column Schaal/Trede
		dataType: string
		lineageTag: 5381a3c7-595e-4990-a2d0-90eaaa290be7
		summarizeBy: none
		sourceColumn: Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 7ca558e0-f1ad-4e86-ac88-7aa44f453d0d
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	partition 'Dim Vacatures Medewerker' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Json.Document(Web.Contents("https://86331.rest.afas.online/ProfitRestServices/connectors/CMC_Formatieplaats" & "?skip=-1&take=-1", [Headers=[Authorization="AfasToken PHRva2VuPjx2ZXJzaW9uPjE8L3ZlcnNpb24+PGRhdGE+Qjk5N0I1MjNGMzhENDgwNjgyRTA0NzQ4RkZCQUQ1RjU5MTA1OEU3QUEwQTQ0MDMxODlBNUVGNTNEMjFDREQ5MTwvZGF0YT48L3Rva2VuPg=="]])),
				    rows = Source[rows],
				    #"Converted to Table" = Table.FromList(rows, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}, {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"Geblokkeerd", type logical}, {"Naam_werkgever", type text}, {"Patientgebonden_functies", type text}, {"Soort_functie", type text}, {"Declarerend_Niet-declarerend", type text}, {"Service_Lines", type text}, {"Cluster_Afdeling", type text}, {"Omschrijving", type text}, {"Formatieplaats", type text}, {"Kostenplaats", Int64.Type}, {"Organisatorische_eenheid", type text}, {"Omschrijving_2", type text}, {"Functie", type text}, {"Omschrijving_3", type text}, {"Generieke_functienaam", type text}, {"Gebruiker", type text}, {"Type_functie", type text}, {"Naam", type text}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([Einddatum], "T"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Text Before Delimiter", "Eind Datum"}}),
				    #"Inserted Text Before Delimiter1" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Begindatum], "T"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Before Delimiter1",{{"Text Before Delimiter", "Begin Datum"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Begin Datum", type date}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum"}),
				    #"Inserted Text Before Delimiter2" = Table.AddColumn(#"Reordered Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Gewijzigd], "T"), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Text Before Delimiter2",{{"Text Before Delimiter", "Datum Gewijzigd"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Datum Gewijzigd", type date}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Changed Type3", "Text After Delimiter", each Text.AfterDelimiter([Gewijzigd], "T"), type text),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Inserted Text After Delimiter", {{"Text After Delimiter", each Text.BeforeDelimiter(_, "Z"), type text}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Extracted Text Before Delimiter",{{"Text After Delimiter", "Tijd Gewijzigd"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Tijd Gewijzigd", type time}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type4",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum", "Datum Gewijzigd", "Tijd Gewijzigd"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Aantal_FTE_2", type number}, {"Aantal_FTE", type number}, {"Aantal_FTE_3", type number}, {"Aantal_FTE_4", type number}, {"Verschil", type number}, {"FTE_Begroot", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type5", "Uren_Begroot", each [FTE_Begroot] * 8),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Uren_Werkelijk", each [Aantal_FTE] * 8),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Uren_Verschil", each [Verschil] * 8),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom2",{{"Uren_Begroot", type number}, {"Uren_Werkelijk", type number}, {"Uren_Verschil", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type6", each ([Naam_werkgever] = "Curacao Medical Center Exploitatie")),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Filtered Rows",{{"Kostenplaats", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type7", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns7" = Table.RenameColumns(#"Added Index",{{"Index", "Medewerker ID"}}),
				    #"Renamed Columns8" = Table.RenameColumns(#"Renamed Columns7",{{"Aantal_FTE", "Werkelijk"}, {"Aantal_FTE_2", "Instroom"}, {"Aantal_FTE_3", "FTE uitstroom (zonder bepaalde tijd)"}, {"Verschil", "Verschil (excl)"}, {"Aantal_FTE_4", "Verschil"}, {"Organisatorische_eenheid", "OE"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns8", each [#"Verschil (excl)"] > 0),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Filtered Rows1",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Werkelijk", "Instroom", "FTE uitstroom (zonder bepaalde tijd)", "Verschil", "Verschil (excl)", "Begin Datum", "Eind Datum", "Uren_Begroot", "Uren_Werkelijk", "Uren_Verschil", "Medewerker ID"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns1", {"Cluster_Afdeling"}, #"Dim Cluster/Afdeling Formatieplaats", {"Cluster/Afdeling Formatieplaatsniveau"}, "Dim Cluster/Afdeling Formatieplaats", JoinKind.LeftOuter),
				    #"Expanded Dim Cluster/Afdeling Formatieplaats" = Table.ExpandTableColumn(#"Merged Queries", "Dim Cluster/Afdeling Formatieplaats", {"C/A Formatie ID"}, {"C/A Formatie ID"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim Cluster/Afdeling Formatieplaats", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling"}, #"Dim Staf", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Staf", JoinKind.LeftOuter),
				    #"Expanded Dim Staf" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Staf", {"Staf of Zorg"}, {"Dim Staf.Staf of Zorg"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Dim Staf", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling"}, #"Dim Zorg", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Zorg", JoinKind.LeftOuter),
				    #"Expanded Dim Zorg" = Table.ExpandTableColumn(#"Merged Queries2", "Dim Zorg", {"Type Zorg Functie", "Staf of Zorg"}, {"Dim Zorg.Type Zorg Functie", "Dim Zorg.Staf of Zorg"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Dim Zorg", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling"}, #"Dim Medewerker Overig", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Medewerker Overig", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker Overig" = Table.ExpandTableColumn(#"Merged Queries3", "Dim Medewerker Overig", {"Staf of Zorg"}, {"Dim Medewerker Overig.Staf of Zorg"}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Expanded Dim Medewerker Overig", {{"Dim Medewerker Overig.Staf of Zorg", type text}}, "en-US"),{"Dim Staf.Staf of Zorg", "Dim Zorg.Staf of Zorg", "Dim Medewerker Overig.Staf of Zorg"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Staf of Zorg"),
				    #"Merged Queries4" = Table.NestedJoin(#"Merged Columns", {"Soort_functie", "Dim Zorg.Type Zorg Functie", "Staf of Zorg"}, #"Dim Type Personeel", {"Soort_functie", "Type Zorg Functie", "Staf of Zorg"}, "Dim Type Personeel", JoinKind.LeftOuter),
				    #"Expanded Dim Type Personeel" = Table.ExpandTableColumn(#"Merged Queries4", "Dim Type Personeel", {"Type Personeel ID"}, {"Type Personeel ID"}),
				    #"Added Custom3" = Table.AddColumn(#"Expanded Dim Type Personeel", "Line ID (MdWID_Formatieplaats)", each Text.From([Medewerker ID]) & "_" & Text.From([Formatieplaats])),
				    #"Merged Queries5" = Table.NestedJoin(#"Added Custom3", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats CAO", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats CAO", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats CAO" = Table.ExpandTableColumn(#"Merged Queries5", "Dim Schaal per Formatieplaats CAO", {"Max Schaal/Trede"}, {"Max Schaal/Trede"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Expanded Dim Schaal per Formatieplaats CAO", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats LNT", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats LNT", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats LNT" = Table.ExpandTableColumn(#"Merged Queries6", "Dim Schaal per Formatieplaats LNT", {"Schaal/Trede LNT 386K Vacature Forecasting"}, {"Schaal/Trede LNT 386K Vacature Forecasting"}),
				    #"Merged Queries7" = Table.NestedJoin(#"Expanded Dim Schaal per Formatieplaats LNT", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats BMP", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats BMP", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats BMP" = Table.ExpandTableColumn(#"Merged Queries7", "Dim Schaal per Formatieplaats BMP", {"Schaal/Trede BMP Forecast Vac"}, {"Schaal/Trede BMP Forecast Vac"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Expanded Dim Schaal per Formatieplaats BMP",{{"Schaal/Trede BMP Forecast Vac", "Schaal/Trede BMP Forecast Vac Original"}}),
				    #"Added Custom4" = Table.AddColumn(#"Renamed Columns4", "Schaal/Trede BMP Forecast Vac", each if [#"Schaal/Trede LNT 386K Vacature Forecasting"] <> null and [#"Schaal/Trede BMP Forecast Vac Original"] <> null then null else [#"Schaal/Trede BMP Forecast Vac Original"]),
				    #"Merged Columns1" = Table.CombineColumns(#"Added Custom4",{"Max Schaal/Trede", "Schaal/Trede LNT 386K Vacature Forecasting", "Schaal/Trede BMP Forecast Vac"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Schaal/Trede"),
				    #"Extracted Text Before Delimiter1" = Table.TransformColumns(#"Merged Columns1", {{"Schaal/Trede", each Text.BeforeDelimiter(_, "-"), type text}}),
				    #"Added Suffix" = Table.TransformColumns(#"Extracted Text Before Delimiter1", {{"Schaal/Trede", each _ & "-MAX", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Suffix","-MAX",null,Replacer.ReplaceValue,{"Schaal/Trede"}),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Replaced Value",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Werkelijk", "Instroom", "FTE uitstroom (zonder bepaalde tijd)", "Verschil", "Verschil (excl)", "Begin Datum", "Eind Datum", "Uren_Begroot", "Uren_Werkelijk", "Uren_Verschil", "Medewerker ID", "C/A Formatie ID", "Dim Zorg.Type Zorg Functie", "Staf of Zorg", "Type Personeel ID", "Line ID (MdWID_Formatieplaats)", "Schaal/Trede"}),
				    #"Merged Queries8" = Table.NestedJoin(#"Removed Other Columns2", {"Schaal/Trede"}, #"Dim SchaalType", {"Schaal/Trede"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries8", "Dim SchaalType", {"Schaal ID"}, {"Schaal ID"})
				in
				    #"Expanded Dim SchaalType"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

