table 'Dim Period'
	lineageTag: 359771a9-e570-4c97-8981-e43407ccad44

	column Year/Period
		dataType: string
		lineageTag: ed79c0d8-c29c-4cdf-9776-a3458a5c50e7
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c230585a-efca-4a2c-9859-9a925cf4585f
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: 1bb49979-e528-40f2-9797-216ef70a4191
			defaultHierarchy: LocalDateTable_b34c3d61-d546-40ce-a5bd-7e5591742761.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start date year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d73abcae-7499-4cd3-b691-ce730e272b13
		summarizeBy: none
		sourceColumn: Start date year

		variation Variation
			isDefault
			relationship: 0ec8b527-25b1-4985-8d90-f00159f67ef5
			defaultHierarchy: LocalDateTable_01929f72-a80b-407a-8777-f6a042f8cbec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month name (short)'
		dataType: string
		lineageTag: 6e41336c-c36c-4cd3-a768-b64bbd68c5db
		summarizeBy: none
		sourceColumn: Month name (short)
		sortByColumn: 'Month no.'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 50f25806-11bf-4993-9fb1-43ba18ef4b3f
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'Month no.'
		dataType: int64
		formatString: 0
		lineageTag: 66c19c48-936a-4cea-9f05-354a77541111
		summarizeBy: sum
		sourceColumn: Month no.

		annotation SummarizationSetBy = Automatic

	partition 'Dim Period' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    StartDate = #date(Date.Year(DateTime.LocalNow()) - 3, 1, 1),
				    TempEndDate = Date.AddYears(Date.From(DateTime.LocalNow()), 1),
				    EndDate = #date(Date.Year(TempEndDate), 12, 31),
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month no.", each Date.Month([Date]), type number),
				    #"Inserted Month Number (leading zeros)" = Table.AddColumn(#"Inserted Month", "Month no. (leading zeros)", each Text.PadStart(Text.From([#"Month no."]),2,"0")),
				    #"Inserted Month Name (long)" = Table.AddColumn(#"Inserted Month Number (leading zeros)", "Month name (long)", each Date.MonthName([Date]), type text),
				    #"Inserted Month Name (short)" = Table.AddColumn(#"Inserted Month Name (long)", "Month name (short)", each Text.Start([#"Month name (long)"],3)),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name (short)", "Quarter", each "Q"&Text.From(Date.QuarterOfYear([Date]))),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([Date]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date]), type number),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([Date]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of week no.", each if Date.DayOfWeek([Date])=0
				then 7
				else Date.DayOfWeek([Date])),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day of week", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week short" = Table.AddColumn(#"Inserted Day Name", "Day of week short", each Text.Start([Day of week],3)),
				    Custom1 = Table.AddColumn(#"Inserted Day of Week short", "DateFormatted", each Text.From([Day])&"-"&Text.From([#"Month no. (leading zeros)"]&"-"&Text.From([Year]))),
				    #"Inserted Year/Month no" = Table.AddColumn(Custom1, "Year/Month no.", each Text.From([Year])&"/"&Text.From([#"Month no. (leading zeros)"])),
				    #"Inserted Year/Month name" = Table.AddColumn(#"Inserted Year/Month no", "Year/Month name (short)", each Text.From([Year])&"/"&Text.From([#"Month name (short)"])),
				    #"Inserted Year/Quarter" = Table.AddColumn(#"Inserted Year/Month name", "Year/Quarter", each Text.From([Year])&"/"&Text.From([Quarter])),
				    #"Added ISO Week Number" = Table.AddColumn(#"Inserted Year/Quarter", "Week no.", each if
				Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=0
				
				then 
				Number.RoundDown((Date.DayOfYear(#date(Date.Year([Date])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([Date])-1,12,31), Day.Monday)+1)+10)/7)
				
				else if
				(Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year([Date]),12,31), Day.Monday)+1<4))
				
				then
				1
				
				else 
				Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)),
				    #"Added ISO Year" = Table.AddColumn(#"Added ISO Week Number", "Year (wk)", each Date.Year(Date.AddDays([Date], 26 - [#"Week no."]))),
				    #"Inserted Year/week" = Table.AddColumn(#"Added ISO Year", "Year/Week", each Text.From([#"Year (wk)"])&"/"&Text.PadStart(Text.From([#"Week no."]),2,"0")),
				    #"Inserted WY" = Table.AddColumn(#"Inserted Year/week", "WY", each [#"Day of week no."]*1000000 
				+[#"Week no."]*10000 
				+[#"Year (wk)"]),
				    #"Added Custom6" = Table.AddColumn(#"Inserted WY", "This week", each if
				Number.RoundDown((Date.DayOfYear(DateTime.LocalNow())-(Date.DayOfWeek(DateTime.LocalNow(), Day.Monday)+1)+10)/7)=0
				
				then 
				Number.RoundDown((Date.DayOfYear(#date(Date.Year(DateTime.LocalNow())-1,12,31))-(Date.DayOfWeek(#date(Date.Year(DateTime.LocalNow())-1,12,31), Day.Monday)+1)+10)/7)
				
				else if
				(Number.RoundDown((Date.DayOfYear(DateTime.LocalNow())-(Date.DayOfWeek(DateTime.LocalNow(), Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year(DateTime.LocalNow()),12,31), Day.Monday)+1<4))
				
				then
				1
				
				else 
				Number.RoundDown((Date.DayOfYear(DateTime.LocalNow())-(Date.DayOfWeek(DateTime.LocalNow(), Day.Monday)+1)+10)/7)),
				    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Previous week", each if
				Number.RoundDown((Date.DayOfYear(Date.AddDays(DateTime.LocalNow(),-7))-(Date.DayOfWeek(Date.AddDays(DateTime.LocalNow(),-7), Day.Monday)+1)+10)/7)=0
				
				then 
				Number.RoundDown((Date.DayOfYear(#date(Date.Year(Date.AddDays(DateTime.LocalNow(),-7))-1,12,31))-(Date.DayOfWeek(#date(Date.Year(Date.AddDays(DateTime.LocalNow(),-7))-1,12,31), Day.Monday)+1)+10)/7)
				
				else if
				(Number.RoundDown((Date.DayOfYear(Date.AddDays(DateTime.LocalNow(),-7))-(Date.DayOfWeek(Date.AddDays(DateTime.LocalNow(),-7), Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year(Date.AddDays(DateTime.LocalNow(),-7)),12,31), Day.Monday)+1<4))
				
				then
				1
				
				else 
				Number.RoundDown((Date.DayOfYear(Date.AddDays(DateTime.LocalNow(),-7))-(Date.DayOfWeek(Date.AddDays(DateTime.LocalNow(),-7), Day.Monday)+1)+10)/7)),
				    #"Inserted week no. (relative)" = Table.AddColumn(#"Added Custom7", "Week no. (relative)", each if [#"Week no."] = [This week] then "This week" else if [#"Week no."] = [Previous week] then "Previous week" else [#"Week no."]),
				    #"Added Custom9" = Table.AddColumn(#"Inserted week no. (relative)", "This year (wk)", each Date.Year(Date.AddDays(DateTime.LocalNow(), 26 - [This week]))),
				    #"Inserted year (wk) (relative)" = Table.AddColumn(#"Added Custom9", "Year (wk) (relative)", each if [#"Year (wk)"]=[#"This year (wk)"]
				then "This year"
				else [#"Year (wk)"]),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted year (wk) (relative)",{"This week", "Previous week", "This year (wk)"}),
				    #"Inserted year (relative)" = Table.AddColumn(#"Removed Columns", "Year (relative)", each if [Year]=Date.Year(DateTime.LocalNow())
				then "This year"
				else [Year]),
				    #"Inserted quarter (relative)" = Table.AddColumn(#"Inserted year (relative)", "Quarter (relative)", each if [Quarter]="Q"&Text.From(Date.QuarterOfYear(DateTime.LocalNow()))
				then "This quarter"
				else if [Quarter]="Q"&Text.From(Date.QuarterOfYear(DateTime.LocalNow())-1) or [Quarter]="Q"&Text.From(Date.QuarterOfYear(DateTime.LocalNow())+3)
				then "Previous quarter"
				else [Quarter]),
				    #"Inserted month name (relative)" = Table.AddColumn(#"Inserted quarter (relative)", "Month name (relative)", each if [#"Month no."]=Date.Month(DateTime.LocalNow())
				then "This month"
				else if [#"Month no."]=Date.Month(DateTime.LocalNow())-1 or [#"Month no."]=Date.Month(DateTime.LocalNow()) +11
				then "Previous month"
				else [#"Month name (long)"]),
				    #"Inserted Day of Year (wk)" = Table.AddColumn(#"Inserted month name (relative)", "Day of Year (wk) ", each Duration.Days(
				    [Date]-
				    Date.AddDays(#date([#"Year (wk)"],1,4),-1*
				    (
				        if Date.DayOfWeek(#date([#"Year (wk)"],1,4))=0
				        then 0
				        else Date.DayOfWeek(#date([#"Year (wk)"],1,4))
				    ))
				)),
				    #"Added Custom" = Table.AddColumn(#"Inserted Day of Year (wk)", "Start date year", each Date.AddDays(#date([#"Year (wk)"],1,4),1+
				-1*
				    (
				        if Date.DayOfWeek(#date([#"Year (wk)"],1,4))=0
				        then 0
				        else Date.DayOfWeek(#date([#"Year (wk)"],1,4))
				    ))),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Always", each 1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Year", Int64.Type}, {"Month no.", Int64.Type}, {"Month no. (leading zeros)", type text}, {"Month name (long)", type text}, {"Month name (short)", type text}, {"Quarter", type text}, {"Week of Year", Int64.Type}, {"Week of Month", Int64.Type}, {"Day", Int64.Type}, {"Day of week no.", Int64.Type}, {"Day of Year", Int64.Type}, {"Day of week", type text}, {"Day of week short", type text}, {"Year/Month no.", type text}, {"Year/Month name (short)", type text}, {"Year/Quarter", type text}, {"Week no.", Int64.Type}, {"Year (wk)", Int64.Type}, {"Year/Week", type text}, {"WY", Int64.Type}, {"Week no. (relative)", type text}, {"Year (wk) (relative)", type text}, {"Year (relative)", type text}, {"Quarter (relative)", type text}, {"Month name (relative)", type text}, {"Day of Year (wk) ", Int64.Type}, {"Start date year", type date}, {"Always", Int64.Type}, {"DateFormatted", type text}}),
				    #"Inserted Quarter1" = Table.AddColumn(#"Changed Type1", "Quarter.1", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Quarter no."}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns1", "Year/Month no.", "Year/Month no. - Copy"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column",{{"Year/Month no. - Copy", "Year/Period"}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Renamed Columns2", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Removed Other Columns" = Table.SelectColumns(#"Inserted Start of Month",{"Year", "Month no.", "Month name (short)", "Start date year", "Year/Period", "Start of Month"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Year/Period"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"Year/Period", "Start of Month", "Start date year"})
				in
				    #"Reordered Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

