table 'Dim Indexering Vacatures'
	lineageTag: a54d225c-4c7e-46a4-b5af-e6e17b920583

	column Indexering
		dataType: double
		lineageTag: 12fa9687-7f4b-470f-b4de-39856152fd94
		summarizeBy: none
		sourceColumn: Indexering

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Index Name'
		dataType: string
		lineageTag: d0fed41b-5f80-4d74-98c4-dc8b38d23a64
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	partition 'Dim Indexering Vacatures' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = List.Generate(
				        () => 0.05, each _ > 0, each _ - 0.01
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Sorted Rows" = Table.Sort(#"Converted to Table",{{"Column1", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"Column1", "Indexering"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Indexering", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Indexering", Percentage.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type1", "Index", 1, 1, Int64.Type),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Index",{{"Index", type text}}),
				    #"Added Suffix" = Table.TransformColumns(#"Changed Type2", {{"Index", each _ & "%", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Suffix",{{"Index", "Index Name"}})
				in 
				    #"Renamed Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

