table 'Dim SchaalType'
	lineageTag: db30c2e8-7814-41c3-9c68-cc68616837b3

	column Schaal
		dataType: string
		lineageTag: 955eedeb-20ca-4209-b827-c69aa5eb7f35
		summarizeBy: none
		sourceColumn: Schaal

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 23eedf2d-6c9c-4f85-aad2-e0d8dfaedd2f
		summarizeBy: none
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column Trede
		dataType: double
		lineageTag: a472fb8e-72ec-4012-987b-2abbea1af8a6
		summarizeBy: sum
		sourceColumn: Trede

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Salaris
		dataType: double
		lineageTag: 67ad25bf-29b2-4afb-b257-e71fce9603b5
		summarizeBy: sum
		sourceColumn: Salaris

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SchaalType Forecasting'
		dataType: string
		lineageTag: 722b9760-44a9-4991-b7e9-aebd7eae96d3
		summarizeBy: none
		sourceColumn: SchaalType Forecasting

		annotation SummarizationSetBy = Automatic

	column 'MAX Trede'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 74d08b79-c1fe-4fe3-89d9-3e953d441f3d
		summarizeBy: none
		sourceColumn: MAX Trede

		annotation SummarizationSetBy = Automatic

	column SchaalType
		dataType: string
		lineageTag: 64ed3b27-c6a3-48e8-b7a0-97c1dc55455c
		summarizeBy: none
		sourceColumn: SchaalType

		annotation SummarizationSetBy = Automatic

	column Schaal/Trede
		dataType: string
		lineageTag: 0b3518b9-5926-4835-a82d-f559c5028cdd
		summarizeBy: none
		sourceColumn: Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column 'Schaal Type ID'
		dataType: string
		lineageTag: b22ddf09-6151-4358-b7f3-9b6be5dfa4b8
		summarizeBy: none
		sourceColumn: Schaal Type ID

		annotation SummarizationSetBy = Automatic

	partition 'Dim SchaalType' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Table.Combine({#"CAO Schaal AFAS", #"BMP Schaal AFAS", #"LNT Schaal AFAS"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Schaal Type", "SchaalType"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns", #"Dim SchaalType AOVK"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Appended Query",{{"Max Trede Flag", "Schaal/Trede"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Schaal Type ID", each if [SchaalType] = "CAO" then 1 else if [SchaalType] = "LNT" then 2 else if [SchaalType] = "BMP" then 3 else 4),
				    #"Added Index" = Table.AddIndexColumn(#"Added Custom", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Index",{{"Index", "Schaal ID"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns2",null,"Andere OVK",Replacer.ReplaceValue,{"Schaal/Trede"}),
				    #"Added Custom1" = Table.AddColumn(#"Replaced Value", "MAX Trede", each if Text.Contains([#"Schaal/Trede"], "MAX") or [#"Schaal ID"] = 180 then true else false),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"MAX Trede", type logical}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type", "SchaalType Forecasting", each if [SchaalType] = "BMP" then "LNT" else [SchaalType]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"Trede", type number}, {"Salaris", type number}, {"SchaalType", type text}, {"Schaal/Trede", type text}, {"SchaalType Forecasting", type text}, {"Schaal", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

