table 'Dim Medewerker'
	lineageTag: 704d84f1-47ae-4d1b-a2ba-ebd6cdf4d30c

	column 'Medewerker ID'
		dataType: string
		lineageTag: 8532d454-4e1a-44c8-b39a-8d06ff98c90d
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Voornaam
		dataType: string
		lineageTag: 2a031a2b-2ca4-4ead-99a0-0f3a21f22639
		summarizeBy: none
		sourceColumn: Voornaam

		annotation SummarizationSetBy = Automatic

	column Achternaam
		dataType: string
		lineageTag: 693823a8-3621-458f-ae60-5a43bfdca8b6
		summarizeBy: none
		sourceColumn: Achternaam

		annotation SummarizationSetBy = Automatic

	column Geboortenaam
		dataType: string
		lineageTag: 79768447-5502-4c47-b651-80b3f76fdfa1
		summarizeBy: none
		sourceColumn: Geboortenaam

		annotation SummarizationSetBy = Automatic

	column E-mail_werk
		dataType: string
		lineageTag: d1d92bdb-8afc-440f-ad77-112335c14ba8
		summarizeBy: none
		sourceColumn: E-mail_werk

		annotation SummarizationSetBy = Automatic

	column Geboortedatum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06fd6bac-ba4f-4b55-84c2-38fe6bd38ec6
		summarizeBy: none
		sourceColumn: Geboortedatum

		variation Variation
			isDefault
			relationship: af0ae359-8051-4c8f-8e7b-9556229a1768
			defaultHierarchy: LocalDateTable_34f1b705-fae0-4db0-ba69-dc3ad200a7e3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Functie
		dataType: string
		lineageTag: 2a508837-53ca-4f6a-a6ea-981935f173e0
		summarizeBy: none
		sourceColumn: Functie

		annotation SummarizationSetBy = Automatic

	column Geslacht
		dataType: string
		lineageTag: e3bc2a44-c36d-415d-9f59-ea1084791f3d
		summarizeBy: none
		sourceColumn: Geslacht

		annotation SummarizationSetBy = Automatic

	column Leeftijd
		dataType: string
		lineageTag: 5791a4cb-e647-4ff7-8e9f-6013f0e4b77a
		summarizeBy: none
		sourceColumn: Leeftijd

		annotation SummarizationSetBy = Automatic

	column Datum_in_dienst
		dataType: dateTime
		formatString: Long Date
		lineageTag: 51aafaa1-fb06-478b-8f44-0eea34d66d60
		summarizeBy: none
		sourceColumn: Datum_in_dienst

		variation Variation
			isDefault
			relationship: 70058c35-4278-4132-bf5a-36fc527d722d
			defaultHierarchy: LocalDateTable_7179e43a-e07b-4353-ad18-05456413521c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Datum_uit_dienst
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5b1b530-3c3c-40ff-9f9d-0176f07346f6
		summarizeBy: none
		sourceColumn: Datum_uit_dienst

		variation Variation
			isDefault
			relationship: b15b4e5f-dd8d-402d-a0d3-16f0eb171abb
			defaultHierarchy: LocalDateTable_5f12439e-ea17-4015-b112-d0b0ea49a114.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status_dienstverband
		dataType: string
		lineageTag: ebac9da4-069f-470d-b97a-ed2013c43c27
		summarizeBy: none
		sourceColumn: Status_dienstverband

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: c2fc3ace-9cfc-4ac3-8fb8-59ca70dce9de
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Geblokkeerd
		dataType: string
		lineageTag: 0923da91-36ed-4265-86c4-e37e994b395c
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Aantal_FTE
		dataType: double
		lineageTag: cef5e719-270b-451a-9f3c-c31af34a2ddd
		summarizeBy: sum
		sourceColumn: Aantal_FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dienstjaren
		dataType: double
		formatString: 0.0
		lineageTag: 773e4fd0-6e62-4814-aabe-0490093182e0
		summarizeBy: sum
		sourceColumn: Dienstjaren

		annotation SummarizationSetBy = Automatic

	column In_opleiding
		dataType: string
		lineageTag: 4024fe93-f0eb-4daa-8bb1-86c070654e70
		summarizeBy: none
		sourceColumn: In_opleiding

		annotation SummarizationSetBy = Automatic

	column Salaris
		dataType: double
		lineageTag: 3a367313-673b-48cd-b3eb-702a65b9ad2f
		summarizeBy: sum
		sourceColumn: Salaris

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Begindatum_salaris
		dataType: dateTime
		formatString: Long Date
		lineageTag: db5ec135-4e75-452b-9112-a2c0f68184f5
		summarizeBy: none
		sourceColumn: Begindatum_salaris

		variation Variation
			isDefault
			relationship: ee060fd5-3406-47d7-a29a-5ce35876a3eb
			defaultHierarchy: LocalDateTable_a05a6d95-eba5-4957-a2a5-100deadbc7e5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Einddatum_salaris
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4d1b4b2-7910-417d-bd69-12a9211847e4
		summarizeBy: none
		sourceColumn: Einddatum_salaris

		variation Variation
			isDefault
			relationship: 37ded886-c002-4c53-90f7-68356261ba2d
			defaultHierarchy: LocalDateTable_c14b01a2-ce33-42b3-897e-a59aeebc8f72.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Begindatum_functie
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff8fd8eb-fba9-4539-bb2f-145503154344
		summarizeBy: none
		sourceColumn: Begindatum_functie

		variation Variation
			isDefault
			relationship: 9ea96603-4370-46b1-83e8-b9092b8726d4
			defaultHierarchy: LocalDateTable_d6929cb5-d1ee-4883-8a1f-f035cb711259.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Formatieplaats
		dataType: string
		lineageTag: f3a7fe43-8d6a-4a2b-97ba-ec0b4aecf41b
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column 'Cluster_Afdeling Formatieplaats'
		dataType: string
		lineageTag: 4e798cbe-1fe6-47fa-9d50-0053f004f277
		summarizeBy: none
		sourceColumn: Cluster_Afdeling Formatieplaats

		annotation SummarizationSetBy = Automatic

	column 'OE Code'
		dataType: string
		lineageTag: c7131ac7-79d7-46bb-97ea-e6a9dea45aec
		summarizeBy: none
		sourceColumn: OE Code

		annotation SummarizationSetBy = Automatic

	column Soort_medewerker
		dataType: string
		lineageTag: b705e31a-c94f-4fd0-a9b5-238421078386
		summarizeBy: none
		sourceColumn: Soort_medewerker

		annotation SummarizationSetBy = Automatic

	column Type_contract
		dataType: string
		lineageTag: 107a8471-e2c9-4199-a4a8-133ad2404adf
		summarizeBy: none
		sourceColumn: Type_contract

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: fe025293-426f-4a10-85a7-976c01fd2e81
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Dienstbetrekking ID'
		dataType: int64
		formatString: 0
		lineageTag: 4839fa5b-66a6-4607-b981-961232cdbb14
		summarizeBy: none
		sourceColumn: Dienstbetrekking ID

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: d578eaba-0ae6-4e76-bca7-b02da6dd7b94
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Cluster/Afdeling Functie'
		dataType: string
		lineageTag: a8ba295b-1345-4d4b-b4cc-c2c2cf1d2c59
		summarizeBy: none
		sourceColumn: Cluster/Afdeling Functie

		annotation SummarizationSetBy = Automatic

	column 'C/A Formatie ID'
		dataType: int64
		formatString: 0
		lineageTag: 67bf4684-279b-4753-ab47-33952bb9ad0b
		summarizeBy: none
		sourceColumn: C/A Formatie ID

		annotation SummarizationSetBy = Automatic

	column 'C/A Functie ID'
		dataType: int64
		formatString: 0
		lineageTag: d3a802f1-1508-48a7-af8c-b5b29c9a0d77
		summarizeBy: count
		sourceColumn: C/A Functie ID

		annotation SummarizationSetBy = Automatic

	column 'Volledige Naam' = 'Dim Medewerker'[Achternaam] & " " & "," & " " & 'Dim Medewerker'[Voorletters] & " " & "(" & 'Dim Medewerker'[Voornaam] & ")"
		lineageTag: 1b42076c-7936-433a-8898-bbd49f2e914d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Voorletters
		dataType: string
		lineageTag: 2339b9ca-18b9-4537-af73-531aec11d50f
		summarizeBy: none
		sourceColumn: Voorletters

		annotation SummarizationSetBy = Automatic

	column Voorvoegsel
		dataType: string
		lineageTag: 41afc439-27b0-485f-a41e-7cf5622be78a
		summarizeBy: none
		sourceColumn: Voorvoegsel

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: bac42867-8567-4e7b-87a6-1a5b19f61541
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: 829307b3-cd25-41a6-ac90-0df031a8b2ff
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column 'Staf of Zorg'
		dataType: string
		lineageTag: b7df9270-79d2-4b1c-871a-1bf252a51ee8
		summarizeBy: none
		sourceColumn: Staf of Zorg

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: 514d1d63-bcf4-4310-be70-12e52fad7a1d
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column 'Dim Zorg.Type Zorg Functie'
		dataType: string
		lineageTag: aeafe45b-638e-42ad-824f-2914bdea7411
		summarizeBy: none
		sourceColumn: Dim Zorg.Type Zorg Functie

		annotation SummarizationSetBy = Automatic

	column 'In_dienst__i.v.m._dienstjaren_'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 22dbb561-ce7e-41e0-8330-a33111d0a579
		summarizeBy: none
		sourceColumn: In_dienst__i.v.m._dienstjaren_

		variation Variation
			isDefault
			relationship: 5375ce7a-e028-4880-be47-6a65fc18ba68
			defaultHierarchy: LocalDateTable_b0951fab-f7e7-469c-b1c8-e5981f017388.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: 4f3021fc-e460-40b9-ac05-9958e8ee7e08
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column 'Flag Indexering Forecasting' =
			
			IF(
			    'Dim Medewerker'[Type Personeel ID] = "Z_3" || 'Dim Medewerker'[Type Personeel ID] = "Z_1" || 'Dim Medewerker'[Type Personeel ID] = "Z_15" || 'Dim Medewerker'[Type Personeel ID] = "Z_10" || 'Dim Medewerker'[Dienstbetrekking ID] = 4,
			    "0",
			    "1"
			)
		lineageTag: 69c029c4-f0f6-4fc8-b852-82697c4bfdd4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Flag Overtime 200% and 300% Type Personeel' =
			
			IF(
			    ('Dim Medewerker'[Type Personeel ID] IN {"Z_1", "Z_10", "Z_15"} || CONTAINSSTRING('Dim Medewerker'[Soort_functie], "Echelon 2") || CONTAINSSTRING('Dim Medewerker'[Soort_functie], "Echelon 1")) && 'Dim Medewerker'[Flag Maaltijdvergoeding] = 0,
			    0,
			    1
			)
		formatString: 0
		lineageTag: 8ab862c8-9568-4391-92a4-46d56bb5b8e3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Cessantia = 40
		formatString: 0
		lineageTag: a6b5a7fa-b714-49af-91de-3131258f6cea
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Maaltijdvergoeding' =
			
			IF(
			    'Dim Medewerker'[Type Personeel ID] = "Z_1" ||
			    'Dim Medewerker'[Type Personeel ID] = "Z_10" ||
			    'Dim Medewerker'[Type Personeel ID] = "Z_15" ||
			    'Dim Medewerker'[Type Personeel ID] = "S_4" ||
			    'Dim Medewerker'[Type Personeel ID] = "S_5" ||
			    'Dim Medewerker'[Type Personeel ID] = "O_4",
			    0,
			    1
			)
		formatString: 0
		lineageTag: c9482b14-ab21-46db-b279-cce1922cceb8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Medewerkers in Fact Forecasting' =
			
			SWITCH(
			    TRUE(),
			    NOT ISBLANK(
			        LOOKUPVALUE(
			            'Fact Forecasting Medewerkers'[Medewerker ID],
			            'Fact Forecasting Medewerkers'[Medewerker ID],
			            'Dim Medewerker'[Medewerker ID]
			        )
			    ),1,
			    'Dim Medewerker'[Medewerker ID] IN {"0001", "0002"}, 1,
			    0
			)
		formatString: 0
		lineageTag: 7ac878e8-a62b-470c-83b8-49fa5124ac3c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag 3086 - Feesturen 200%' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Personeels Kosten'),
			        'Fact Personeels Kosten'[LC] IN { "3010", "3011", "3012" },
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1,
			        'Dim Period'[Year] IN {YEAR(TODAY()), YEAR(TODAY()) - 1}
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 40a7d7aa-2677-4a3b-bbf6-e64a31e880b1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Overwerk 200%' =
			
			IF(
			    'Dim Medewerker'[Flag Overtime 200% and 300% Type Personeel] = 1 &&
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] IN { "2622"},
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: f6afd0ef-c113-458f-a0f1-657f72385318
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Overwerk 300%' =
			
			IF(
			    'Dim Medewerker'[Flag Overtime 200% and 300% Type Personeel] = 1 &&
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] IN { "3075"},
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 8db0e5fd-c42f-48bb-a11e-0a07340c0fbc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3027 - Speciale Toelage' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Personeels Kosten'),
			        'Fact Personeels Kosten'[LC] = "3027",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1,
			        'Dim Period'[Year] = YEAR(TODAY())
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 32f4226d-3bed-49c8-a949-3fa3faef510e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3021 - Instructievergoeding' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] = "3021",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 388641bb-2f06-40da-ae86-406e61bf44ca
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag 4105000 - Gratificaties' =
			
			// 'Dim Medewerker'[Dienstjaren] IN {12.5, 25, 35, 40}
			IF(
			    'Dim Medewerker'[Dienstjaren Forecasting] = 12.5 || 'Dim Medewerker'[Dienstjaren Forecasting] = 25 || 'Dim Medewerker'[Dienstjaren Forecasting] = 35 || 'Dim Medewerker'[Dienstjaren Forecasting] = 40,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 4b45244e-be21-4146-8388-3bf118d525b8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Dienstjaren Forecasting' = 'Dim Medewerker'[Dienstjaren] + 1
		formatString: 0.0
		lineageTag: ef1817a6-126b-4628-8d35-c59fbc705816
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag GB 4116000 - Medische Kosten Eig Risico' = ```
			
			LOOKUPVALUE(
			    'Dim SchaalType'[SchaalType Forecasting],
			    'Dim SchaalType'[Schaal ID], 'Dim Medewerker'[Schaal ID]
			)
			
			```
		lineageTag: b20d3af8-7e58-4c42-8f29-abc8d4cc45a9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'FLag LC 3095 - Vergunning' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Personeels Kosten'),
			        'Fact Personeels Kosten'[LC] IN { "3095"},
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1,
			        'Dim Period'[Year] = YEAR(TODAY())
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 8702c2c0-cb0a-4220-a283-f13004f9e562
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC - 3091 Ziektekosten WG bijdrage' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] IN { "3091"},
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1,
			        'Dim Type Personeel'[Type Personeel ID] IN {"Z_1", "Z_10", "Z_15"}
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: b12660e5-fff1-4411-8cd4-1ce32d78244a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3142 - Medische Kosten Eig Risico (Eigen Personeel)' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1,
			        'Dim Medewerker'[Flag LC - 3091 Ziektekosten WG bijdrage] = 0,
			        FILTER(
			            ALL('Dim Type Personeel'),
			            'Dim Type Personeel'[Type Personeel ID] <> "Z_1" || 'Dim Type Personeel'[Type Personeel ID] <> "Z_10" || 'Dim Type Personeel'[Type Personeel ID] <> "Z_15"
			        )
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 87830d17-8bfc-4724-ae54-3e159c417230
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Medewerker'
		dataType: double
		lineageTag: f7491f9a-1a92-44cd-b4de-3476e7b2d76a
		summarizeBy: sum
		sourceColumn: Flag Medewerker

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Formatieplaats Omschrijving'
		dataType: string
		lineageTag: 93bf97df-d0ee-4190-829d-702680a8bd28
		summarizeBy: none
		sourceColumn: Formatieplaats Omschrijving

		annotation SummarizationSetBy = Automatic

	column Schaal/Trede
		dataType: string
		lineageTag: 7cec738f-0ff3-4632-8379-1c7e233cf940
		summarizeBy: none
		sourceColumn: Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column 'Flag Stagaire' =
			
			IF(
			    'Dim Medewerker'[Medewerker ID] = "0002",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 3736eb0a-5f4f-48ac-8a32-668e3f6c862c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Vrijwilleger' =
			
			IF(
			    'Dim Medewerker'[Medewerker ID] = "0001",
			    1,
			    0
			)
		formatString: 0
		lineageTag: c083650c-1735-4038-861c-2153d450995c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Medische Specialisten' =
			
			IF(
			    'Dim Medewerker'[Type Personeel ID] IN {"Z_1", "Z_10", "Z_15"},
			    1,
			    0
			)
		formatString: 0
		lineageTag: 7de41ca3-e58d-45ad-bd10-9951234db896
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Overwerk Schemawerk 30%' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] IN { "3010"},
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 7dac5dfc-c486-4041-9e71-00bf03111b73
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag GB 4106000 Bijzondere Vergoeding'
		type: calculated
		lineageTag: 5fb274b9-ecd8-4854-bf14-92db66c74535
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag KPL 1840 - Medische Dienst' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[Kostenplaats] IN {"1840"},
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 747aff51-13c0-448e-b97d-2a715e0fc2a3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag GB 4125100 - Personeel niet in loondienst' =
			
			IF(
			    'Dim Medewerker'[Kostenplaats] = "1840" ||
			    'Dim Medewerker'[Dienstbetrekking ID] = 5,
			    1,
			    0
			)
		formatString: 0
		lineageTag: af9e5bcd-c5ca-4234-8ac3-8025a82d3919
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Maanden in Dienst' = RELATED('Fact Medewerker Maanden in Dienst Actuals'[Maanden in Dienst])
		formatString: 0
		lineageTag: d3a8d4fd-779f-4b5b-8178-e156319ca8d0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3010 - Schemawerk 30%' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] = "3010",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 8ab827ed-5f42-4d72-9195-0d1e4804a677
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3011 - Schemawerk 45%' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] = "3011",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 6db275ab-f248-4995-9f7e-853d30d6cdc5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3012 - Schemawerk 50%' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] = "3012",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 364b13a8-c58d-446a-82b4-a4b070652872
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'OE Flag LC 3019 - Standby' = RELATED('Dim Organisatie Eenheid Flag Standby'[OE])
		lineageTag: fee1a740-f008-4b12-8354-ab259451b76f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3019 - Standby Toelage' = ```
			
			// IF(
			//     ISBLANK('Dim Medewerker'[OE Flag LC 3019 - Standby]), 
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] = "3019",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			    )
			// 1
			// )
			```
		formatString: 0
		lineageTag: f2998bf5-bdeb-4918-9fc9-ad35bc068e2e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag LC 3026 - Wachttoelage' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Fact Forecasting Medewerkers'),
			        'Fact Forecasting Medewerkers'[LC] = "3026",
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			    ) > 0,
			    1,
			    0
			    )
		formatString: 0
		lineageTag: 46f4a1bf-e732-4021-81ca-2e763aa0e5b8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Dim Medewerker' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Json.Document(Web.Contents("https://86331.rest.afas.online/ProfitRestServices/connectors/CMC_WeergaveBP" & "?skip=0&take=500000", [Headers=[Authorization="AfasToken PHRva2VuPjx2ZXJzaW9uPjE8L3ZlcnNpb24+PGRhdGE+Qjk5N0I1MjNGMzhENDgwNjgyRTA0NzQ4RkZCQUQ1RjU5MTA1OEU3QUEwQTQ0MDMxODlBNUVGNTNEMjFDREQ5MTwvZGF0YT48L3Rva2VuPg=="]])),
				    rows = Source[rows],
				    #"Converted to Table" = Table.FromList(rows, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Medewerker", "Roepnaam", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving", "Geboorteplaats", "Geslacht", "Leeftijd", "Datum_in_dienst", "Formatieplaats", "Omschrijving_3", "Omschrijving_3_2", "Datum_uit_dienst", "Dienstverband", "Dienstverband_2", "Status_dienstverband", "Kostenplaats", "Omschrijving_4", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Initiatief", "Dienstjaren", "Cluster_Afdeling", "Dienstbetrekking", "Nationaliteit", "Functie_2", "Omschrijving_4_2", "In_opleiding", "Cluster_Afdeling_2", "Patientgebonden_functies", "Patientgebonden_functies_2", "Soort_functie", "In_dienst__i.v.m._dienstjaren_", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Volgnummer", "Formatieplaats_2", "Omschrijving_5", "Service_Lines", "Service_Line_Type", "Cluster_Afdeling_3", "Organisatorische_eenheid_2", "Omschrijving_6", "Soort_medewerker", "Type_contract"}, {"Medewerker", "Roepnaam", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving", "Geboorteplaats", "Geslacht", "Leeftijd", "Datum_in_dienst", "Formatieplaats", "Omschrijving_3", "Omschrijving_3_2", "Datum_uit_dienst", "Dienstverband", "Dienstverband_2", "Status_dienstverband", "Kostenplaats", "Omschrijving_4", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Initiatief", "Dienstjaren", "Cluster_Afdeling", "Dienstbetrekking", "Nationaliteit", "Functie_2", "Omschrijving_4_2", "In_opleiding", "Cluster_Afdeling_2", "Patientgebonden_functies", "Patientgebonden_functies_2", "Soort_functie", "In_dienst__i.v.m._dienstjaren_", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Volgnummer", "Formatieplaats_2", "Omschrijving_5", "Service_Lines", "Service_Line_Type", "Cluster_Afdeling_3", "Organisatorische_eenheid_2", "Omschrijving_6", "Soort_medewerker", "Type_contract"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded Column1", each ([Naam_werkgever] = "Curacao Medical Center Exploitatie")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Medewerker", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Functie", "Geslacht", "Leeftijd", "Datum_in_dienst", "Datum_uit_dienst", "Status_dienstverband", "Kostenplaats", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Dienstjaren", "Cluster_Afdeling", "Dienstbetrekking", "In_opleiding", "Cluster_Afdeling_2", "Patientgebonden_functies", "Patientgebonden_functies_2", "Soort_functie", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Formatieplaats_2", "Omschrijving_5", "Cluster_Afdeling_3", "Organisatorische_eenheid_2", "Soort_medewerker", "Type_contract"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"Medewerker", "Medewerker ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Begindatum_salaris", type datetime}, {"Einddatum_salaris", type datetime}, {"Begindatum_functie", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Begindatum_salaris", type date}, {"Einddatum_salaris", type date}, {"Begindatum_functie", type date}, {"Datum_in_dienst", type datetime}, {"Datum_uit_dienst", type datetime}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"Datum_in_dienst", type date}, {"Datum_uit_dienst", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"Formatieplaats_2", "Formatieplaats Code"}, {"Organisatorische_eenheid_2", "OE Code"}, {"Cluster_Afdeling_3", "Cluster/Afdeling"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Geboortedatum", type datetime}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Changed Type3",{{"Geboortedatum", type date}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type4",{{"Functie", "Functie Code"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns2", {"Medewerker ID"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"Soort_functie"}, #"Dim Personeel Type OLD", {"Type Personeel"}, "Dim Personeel Type", JoinKind.LeftOuter),
				    #"Expanded Dim Personeel Type" = Table.ExpandTableColumn(#"Merged Queries", "Dim Personeel Type", {"Type Personeel ID"}, {"Type Personeel ID"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim Personeel Type", {"Schaal", "Trede"}, #"Dim SchaalType", {"Schaal", "Trede"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries1", "Dim SchaalType", {"Schaal ID"}, {"Schaal ID"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Dim SchaalType", {"Dienstbetrekking"}, #"Dim Dienstbetrekking", {"Dienstbetrekking"}, "Dim Dienstbetrekking", JoinKind.LeftOuter),
				    #"Expanded Dim Dienstbetrekking" = Table.ExpandTableColumn(#"Merged Queries2", "Dim Dienstbetrekking", {"Dienstbetrekking ID"}, {"Dienstbetrekking ID"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Expanded Dim Dienstbetrekking",{"Medewerker ID", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Functie Code", "Geslacht", "Leeftijd", "Datum_in_dienst", "Datum_uit_dienst", "Status_dienstverband", "Kostenplaats", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Dienstjaren", "In_opleiding", "Cluster_Afdeling_2", "Patientgebonden_functies", "Soort_functie", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Formatieplaats Code", "Omschrijving_5", "Cluster/Afdeling", "OE Code", "Soort_medewerker", "Type_contract", "Type Personeel ID", "Schaal ID", "Dienstbetrekking ID"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Removed Other Columns1",{{"Salaris", type number}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type5",{{"Cluster/Afdeling", "Cluster/Afdeling Formatieplaats"}, {"Cluster_Afdeling_2", "Cluster/Afdeling Functie"}}),
				    #"Merged Queries3" = Table.NestedJoin(#"Renamed Columns3", {"Cluster/Afdeling Formatieplaats"}, #"Dim Cluster/Afdeling Formatieplaats", {"Cluster/Afdeling Formatieplaatsniveau"}, "Dim Cluster/Afdeling Formatieplaats", JoinKind.LeftOuter),
				    #"Expanded Dim Cluster/Afdeling Formatieplaats" = Table.ExpandTableColumn(#"Merged Queries3", "Dim Cluster/Afdeling Formatieplaats", {"C/A Formatie ID"}, {"C/A Formatie ID"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Expanded Dim Cluster/Afdeling Formatieplaats", {"Cluster/Afdeling Functie"}, #"Dim Cluster/Afdeling Functienveau", {"Cluster/Afdeling Functienveau"}, "Dim Cluster/Afdeling Functienveau", JoinKind.LeftOuter),
				    #"Expanded Dim Cluster/Afdeling Functienveau" = Table.ExpandTableColumn(#"Merged Queries4", "Dim Cluster/Afdeling Functienveau", {"C/A Functie ID"}, {"C/A Functie ID"}),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Expanded Dim Cluster/Afdeling Functienveau",{{"Aantal_FTE", type number}, {"Dienstjaren", type number}}),
				    #"Merged Queries5" = Table.NestedJoin(#"Changed Type6", {"Patientgebonden_functies", "Soort_functie", "Cluster/Afdeling Formatieplaats"}, #"Dim Staf", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Staf", JoinKind.LeftOuter),
				    #"Expanded Dim Staf" = Table.ExpandTableColumn(#"Merged Queries5", "Dim Staf", {"Staf of Zorg"}, {"Dim Staf.Staf of Zorg"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Expanded Dim Staf", {"Patientgebonden_functies", "Soort_functie", "Cluster/Afdeling Formatieplaats"}, #"Dim Zorg", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Zorg", JoinKind.LeftOuter),
				    #"Expanded Dim Zorg" = Table.ExpandTableColumn(#"Merged Queries6", "Dim Zorg", {"Type Zorg Functie", "Staf of Zorg"}, {"Dim Zorg.Type Zorg Functie", "Dim Zorg.Staf of Zorg"}),
				    #"Merged Queries8" = Table.NestedJoin(#"Expanded Dim Zorg", {"Patientgebonden_functies", "Soort_functie", "Cluster/Afdeling Formatieplaats"}, #"Dim Medewerker Overig", {"Patientgebonden_functies", "Soort_functie", "Cluster_Afdeling_3"}, "Dim Medewerker Overig", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker Overig" = Table.ExpandTableColumn(#"Merged Queries8", "Dim Medewerker Overig", {"Staf of Zorg"}, {"Dim Medewerker Overig.Staf of Zorg"}),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Expanded Dim Medewerker Overig",{"Medewerker ID", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Functie Code", "Geslacht", "Leeftijd", "Datum_in_dienst", "Datum_uit_dienst", "Status_dienstverband", "Kostenplaats", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Dienstjaren", "In_opleiding", "Cluster/Afdeling Functie", "Patientgebonden_functies", "Soort_functie", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Trede", "Schaal", "Formatieplaats Code", "Omschrijving_5", "Cluster/Afdeling Formatieplaats", "OE Code", "Soort_medewerker", "Type_contract", "Schaal ID", "Dienstbetrekking ID", "C/A Formatie ID", "C/A Functie ID", "Dim Staf.Staf of Zorg", "Dim Zorg.Type Zorg Functie", "Dim Zorg.Staf of Zorg", "Dim Medewerker Overig.Staf of Zorg"}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Removed Other Columns2", {{"Dim Medewerker Overig.Staf of Zorg", type text}}, "en-US"),{"Dim Staf.Staf of Zorg", "Dim Zorg.Staf of Zorg", "Dim Medewerker Overig.Staf of Zorg"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Staf of Zorg"),
				    #"Merged Queries7" = Table.NestedJoin(#"Merged Columns", {"Soort_functie", "Dim Zorg.Type Zorg Functie", "Staf of Zorg"}, #"Dim Type Personeel", {"Soort_functie", "Type Zorg Functie", "Staf of Zorg"}, "Dim Type Personeel", JoinKind.LeftOuter),
				    #"Expanded Dim Type Personeel" = Table.ExpandTableColumn(#"Merged Queries7", "Dim Type Personeel", {"Type Personeel ID"}, {"Type Personeel ID"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Expanded Dim Type Personeel", {"Medewerker ID"}),
				    #"Merged Queries9" = Table.NestedJoin(#"Removed Duplicates1", {"Medewerker ID"}, #"Dim Medewerker (FormatieBezetting)", {"Medewerker"}, "Dim Medewerker (FormatieBezetting)", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker (FormatieBezetting)" = Table.ExpandTableColumn(#"Merged Queries9", "Dim Medewerker (FormatieBezetting)", {"In_dienst__i.v.m._dienstjaren_"}, {"In_dienst__i.v.m._dienstjaren_"}),
				    #"Inserted Month" = Table.AddColumn(#"Expanded Dim Medewerker (FormatieBezetting)", "Month", each Date.Month([In_dienst__i.v.m._dienstjaren_]), Int64.Type),
				    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Month",{{"Month", "Anniversary Month"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns4", #"Dim Vrijwilleger en Stagair"}),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Appended Query",{{"Medewerker ID", type text}, {"Voornaam", type text}, {"Voorletters", type text}, {"Achternaam", type text}, {"Geboortenaam", type text}, {"Voorvoegsel", type text}, {"Status_dienstverband", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type7", "Flag Medewerker", each 1, type nullable number),
				    #"Renamed Columns5" = Table.RenameColumns(#"Added Custom",{{"Formatieplaats Code", "Formatieplaats"}, {"Functie Code", "Functie"}, {"Cluster/Afdeling Formatieplaats", "Cluster_Afdeling Formatieplaats"}, {"Omschrijving_5", "Formatieplaats Omschrijving"}}),
				    #"Merged Queries10" = Table.NestedJoin(#"Renamed Columns5", {"Schaal ID"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType1" = Table.ExpandTableColumn(#"Merged Queries10", "Dim SchaalType", {"Schaal/Trede"}, {"Schaal/Trede"}),
				    #"Removed Other Columns3" = Table.SelectColumns(#"Expanded Dim SchaalType1",{"Medewerker ID", "Voornaam", "Voorletters", "Achternaam", "Geboortenaam", "Voorvoegsel", "E-mail_werk", "Geboortedatum", "Functie", "Geslacht", "Leeftijd", "Datum_in_dienst", "Datum_uit_dienst", "Status_dienstverband", "Kostenplaats", "Geblokkeerd", "Naam_werkgever", "Aantal_FTE", "Dienstjaren", "In_opleiding", "Cluster/Afdeling Functie", "Patientgebonden_functies", "Soort_functie", "Salaris", "Begindatum_salaris", "Einddatum_salaris", "Begindatum_functie", "Formatieplaats", "Formatieplaats Omschrijving", "Cluster_Afdeling Formatieplaats", "OE Code", "Soort_medewerker", "Type_contract", "Schaal ID", "Dienstbetrekking ID", "C/A Formatie ID", "C/A Functie ID", "Dim Zorg.Type Zorg Functie", "Staf of Zorg", "Type Personeel ID", "In_dienst__i.v.m._dienstjaren_", "Anniversary Month", "Flag Medewerker", "Schaal/Trede"})
				in
				    #"Removed Other Columns3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

