table 'Dim Percentage Vacature LNT'
	lineageTag: 72d41e5f-c6d4-457a-bbec-7f608ae5c7e5

	column Percentage
		dataType: double
		lineageTag: e6791c81-a617-4408-a86a-2f956f46a3bc
		summarizeBy: none
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Percentage Name'
		dataType: string
		lineageTag: 66e16979-d414-4755-9254-91779fdd5fec
		summarizeBy: none
		sourceColumn: Percentage Name
		sortByColumn: Percentage

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SchaalType
		dataType: string
		lineageTag: 02a016d6-8d15-4f73-8eef-598df6d78521
		summarizeBy: none
		sourceColumn: SchaalType

		annotation SummarizationSetBy = Automatic

	column 'Percentage Key'
		dataType: string
		lineageTag: a43b6af0-da09-4736-a31d-ecf9ae92e1e5
		summarizeBy: none
		sourceColumn: Percentage Key

		annotation SummarizationSetBy = Automatic

	partition 'Dim Percentage Vacature LNT' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMtAzVNJRMjRQVYrVAfNMQVxTGNcIxDWCc40NgFxjuGKQpCmcZw7imsPVWoC4FlAuxBKQ0lgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Percentage = _t, #"Percentage Name" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Percentage", Percentage.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "SchaalType", each "LNT"),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Percentage Key", each Text.From([Percentage Name]) & "_" & Text.From([SchaalType])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Percentage Key", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

