table 'Dim Calendar'
	lineageTag: a883d342-a4f1-4794-be15-d8996c371305

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: def524d1-abad-460e-a6e4-5eb8b30724b9
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 968b7272-25f6-4bce-9659-09bd9bc08790
			defaultHierarchy: LocalDateTable_ad3891fd-19ab-4639-8353-00240143c7b3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ae166625-1320-454f-8eeb-849fced7db78
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month no.'
		dataType: int64
		formatString: 0
		lineageTag: c93fa123-ca3b-4900-8dd1-5f7f56b177d8
		summarizeBy: sum
		sourceColumn: Month no.

		annotation SummarizationSetBy = Automatic

	column 'Month no. (leading zeros)'
		dataType: string
		lineageTag: 8da0414a-a436-4fa2-a334-4bcd74c7aa8c
		summarizeBy: none
		sourceColumn: Month no. (leading zeros)

		annotation SummarizationSetBy = Automatic

	column 'Month name (long)'
		dataType: string
		lineageTag: e1df56d3-31b0-4f84-b52b-df2f80322b8c
		summarizeBy: none
		sourceColumn: Month name (long)

		annotation SummarizationSetBy = Automatic

	column 'Month name (short)'
		dataType: string
		lineageTag: 96f12460-e64a-413b-87f1-aa22f5440576
		summarizeBy: none
		sourceColumn: Month name (short)
		sortByColumn: 'Month no.'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9a1ad999-e1fd-46de-a459-f8a7d802b947
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: 0303459b-6764-4070-9e0a-ff923b0699f5
		summarizeBy: sum
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: b762cde2-a004-4320-bed1-0794dc8b3a15
		summarizeBy: sum
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 189f09f9-f526-42ff-a49b-fb4f21b07762
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Day of week no.'
		dataType: int64
		formatString: 0
		lineageTag: 1e8d2381-4aac-4d09-b814-2b0dba9ce5da
		summarizeBy: sum
		sourceColumn: Day of week no.

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 9176bdeb-9b0a-4a77-8725-d63f7d9110a7
		summarizeBy: sum
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	column 'Day of week'
		dataType: string
		lineageTag: f6141d07-e209-49d1-b8a9-4c176f50d497
		summarizeBy: none
		sourceColumn: Day of week

		annotation SummarizationSetBy = Automatic

	column 'Day of week short'
		dataType: string
		lineageTag: e68c3374-2265-4dde-96b3-f40809f7fa7b
		summarizeBy: none
		sourceColumn: Day of week short

		annotation SummarizationSetBy = Automatic

	column DateFormatted
		dataType: string
		lineageTag: 84568534-6222-4436-bd9f-dab1af02f7da
		summarizeBy: none
		sourceColumn: DateFormatted

		annotation SummarizationSetBy = Automatic

	column 'Year/Month no.'
		dataType: string
		lineageTag: d9dc822e-57e4-401c-b317-c51bcdc55738
		summarizeBy: none
		sourceColumn: Year/Month no.

		annotation SummarizationSetBy = Automatic

	column 'Year/Month name (short)'
		dataType: string
		lineageTag: 24c68b92-4247-4ceb-8ee1-6740dc4cf4bc
		summarizeBy: none
		sourceColumn: Year/Month name (short)

		annotation SummarizationSetBy = Automatic

	column Year/Quarter
		dataType: string
		lineageTag: c0b49755-f31d-4934-936f-c62e0b2cfb73
		summarizeBy: none
		sourceColumn: Year/Quarter

		annotation SummarizationSetBy = Automatic

	column 'Week no.'
		dataType: int64
		formatString: 0
		lineageTag: d6e41dba-2a14-408d-b1b9-1bb0816b0b18
		summarizeBy: sum
		sourceColumn: Week no.

		annotation SummarizationSetBy = Automatic

	column 'Year (wk)'
		dataType: int64
		formatString: 0
		lineageTag: 670179c7-0843-49dc-b1f8-a79012e6f3cb
		summarizeBy: sum
		sourceColumn: Year (wk)

		annotation SummarizationSetBy = Automatic

	column Year/Week
		dataType: string
		lineageTag: e4f657a9-55d5-4654-b453-0e0ad714807f
		summarizeBy: none
		sourceColumn: Year/Week

		annotation SummarizationSetBy = Automatic

	column WY
		dataType: int64
		formatString: 0
		lineageTag: 0ca492e0-17e1-4d40-a003-5cd80da0ee05
		summarizeBy: sum
		sourceColumn: WY

		annotation SummarizationSetBy = Automatic

	column 'Week no. (relative)'
		dataType: string
		lineageTag: 0d66a36a-a9c9-42d3-b52c-b0bf2c861897
		summarizeBy: none
		sourceColumn: Week no. (relative)

		annotation SummarizationSetBy = Automatic

	column 'Year (wk) (relative)'
		dataType: string
		lineageTag: 3d9618ce-0744-4d3d-8198-9e36e12c09bd
		summarizeBy: none
		sourceColumn: Year (wk) (relative)

		annotation SummarizationSetBy = Automatic

	column 'Year (relative)'
		dataType: string
		lineageTag: dbff1fe7-bf52-4877-9532-619fc02e5344
		summarizeBy: none
		sourceColumn: Year (relative)

		annotation SummarizationSetBy = Automatic

	column 'Quarter (relative)'
		dataType: string
		lineageTag: 198d60fb-993a-4ced-95af-9f1fb4ae7c05
		summarizeBy: none
		sourceColumn: Quarter (relative)

		annotation SummarizationSetBy = Automatic

	column 'Month name (relative)'
		dataType: string
		lineageTag: 99d0d913-73b6-41f5-94a4-04e7efdbd9da
		summarizeBy: none
		sourceColumn: Month name (relative)

		annotation SummarizationSetBy = Automatic

	column 'Day of Year (wk) '
		dataType: int64
		formatString: 0
		lineageTag: a13924e5-2e35-4b80-a331-9170d5dc0a73
		summarizeBy: sum
		sourceColumn: "Day of Year (wk) "

		annotation SummarizationSetBy = Automatic

	column 'Start date year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: df599161-43e2-4181-90a0-256618ed504e
		summarizeBy: none
		sourceColumn: Start date year

		variation Variation
			isDefault
			relationship: 5de80d7c-2fd9-4ef4-84ad-551ed8060543
			defaultHierarchy: LocalDateTable_17d15d23-9858-43a8-83a2-65bffd42729d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Always
		dataType: int64
		formatString: 0
		lineageTag: 9f329cf0-49f5-4b3d-9afe-5c6475f7c2fe
		summarizeBy: sum
		sourceColumn: Always

		annotation SummarizationSetBy = Automatic

	column 'Quarter no.'
		dataType: int64
		formatString: 0
		lineageTag: 953c8abe-d021-4b7e-a80f-bbd6c25f980e
		summarizeBy: sum
		sourceColumn: Quarter no.

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: b790b3ba-cdbc-4fce-a91e-6c238eb766c8
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	partition 'Dim Calendar' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    StartDate = #date(Date.Year(DateTime.LocalNow())-3, 1, 1),
				    EndDate = Date.AddYears(Date.From(DateTime.LocalNow()), 1),
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month no.", each Date.Month([Date]), type number),
				    #"Inserted Month Number (leading zeros)" = Table.AddColumn(#"Inserted Month", "Month no. (leading zeros)", each Text.PadStart(Text.From([#"Month no."]),2,"0")),
				    #"Inserted Month Name (long)" = Table.AddColumn(#"Inserted Month Number (leading zeros)", "Month name (long)", each Date.MonthName([Date]), type text),
				    #"Inserted Month Name (short)" = Table.AddColumn(#"Inserted Month Name (long)", "Month name (short)", each Text.Start([#"Month name (long)"],3)),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name (short)", "Quarter", each "Q"&Text.From(Date.QuarterOfYear([Date]))),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([Date]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date]), type number),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([Date]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of week no.", each if Date.DayOfWeek([Date])=0
				then 7
				else Date.DayOfWeek([Date])),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day of week", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week short" = Table.AddColumn(#"Inserted Day Name", "Day of week short", each Text.Start([Day of week],3)),
				    Custom1 = Table.AddColumn(#"Inserted Day of Week short", "DateFormatted", each Text.From([Day])&"-"&Text.From([#"Month no. (leading zeros)"]&"-"&Text.From([Year]))),
				    #"Inserted Year/Month no" = Table.AddColumn(Custom1, "Year/Month no.", each Text.From([Year])&"/"&Text.From([#"Month no. (leading zeros)"])),
				    #"Inserted Year/Month name" = Table.AddColumn(#"Inserted Year/Month no", "Year/Month name (short)", each Text.From([Year])&"/"&Text.From([#"Month name (short)"])),
				    #"Inserted Year/Quarter" = Table.AddColumn(#"Inserted Year/Month name", "Year/Quarter", each Text.From([Year])&"/"&Text.From([Quarter])),
				    #"Added ISO Week Number" = Table.AddColumn(#"Inserted Year/Quarter", "Week no.", each if
				Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=0
				
				then 
				Number.RoundDown((Date.DayOfYear(#date(Date.Year([Date])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([Date])-1,12,31), Day.Monday)+1)+10)/7)
				
				else if
				(Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year([Date]),12,31), Day.Monday)+1<4))
				
				then
				1
				
				else 
				Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)),
				    #"Added ISO Year" = Table.AddColumn(#"Added ISO Week Number", "Year (wk)", each Date.Year(Date.AddDays([Date], 26 - [#"Week no."]))),
				    #"Inserted Year/week" = Table.AddColumn(#"Added ISO Year", "Year/Week", each Text.From([#"Year (wk)"])&"/"&Text.PadStart(Text.From([#"Week no."]),2,"0")),
				    #"Inserted WY" = Table.AddColumn(#"Inserted Year/week", "WY", each [#"Day of week no."]*1000000 
				+[#"Week no."]*10000 
				+[#"Year (wk)"]),
				    #"Added Custom6" = Table.AddColumn(#"Inserted WY", "This week", each if
				Number.RoundDown((Date.DayOfYear(DateTime.LocalNow())-(Date.DayOfWeek(DateTime.LocalNow(), Day.Monday)+1)+10)/7)=0
				
				then 
				Number.RoundDown((Date.DayOfYear(#date(Date.Year(DateTime.LocalNow())-1,12,31))-(Date.DayOfWeek(#date(Date.Year(DateTime.LocalNow())-1,12,31), Day.Monday)+1)+10)/7)
				
				else if
				(Number.RoundDown((Date.DayOfYear(DateTime.LocalNow())-(Date.DayOfWeek(DateTime.LocalNow(), Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year(DateTime.LocalNow()),12,31), Day.Monday)+1<4))
				
				then
				1
				
				else 
				Number.RoundDown((Date.DayOfYear(DateTime.LocalNow())-(Date.DayOfWeek(DateTime.LocalNow(), Day.Monday)+1)+10)/7)),
				    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Previous week", each if
				Number.RoundDown((Date.DayOfYear(Date.AddDays(DateTime.LocalNow(),-7))-(Date.DayOfWeek(Date.AddDays(DateTime.LocalNow(),-7), Day.Monday)+1)+10)/7)=0
				
				then 
				Number.RoundDown((Date.DayOfYear(#date(Date.Year(Date.AddDays(DateTime.LocalNow(),-7))-1,12,31))-(Date.DayOfWeek(#date(Date.Year(Date.AddDays(DateTime.LocalNow(),-7))-1,12,31), Day.Monday)+1)+10)/7)
				
				else if
				(Number.RoundDown((Date.DayOfYear(Date.AddDays(DateTime.LocalNow(),-7))-(Date.DayOfWeek(Date.AddDays(DateTime.LocalNow(),-7), Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year(Date.AddDays(DateTime.LocalNow(),-7)),12,31), Day.Monday)+1<4))
				
				then
				1
				
				else 
				Number.RoundDown((Date.DayOfYear(Date.AddDays(DateTime.LocalNow(),-7))-(Date.DayOfWeek(Date.AddDays(DateTime.LocalNow(),-7), Day.Monday)+1)+10)/7)),
				    #"Inserted week no. (relative)" = Table.AddColumn(#"Added Custom7", "Week no. (relative)", each if [#"Week no."] = [This week] then "This week" else if [#"Week no."] = [Previous week] then "Previous week" else [#"Week no."]),
				    #"Added Custom9" = Table.AddColumn(#"Inserted week no. (relative)", "This year (wk)", each Date.Year(Date.AddDays(DateTime.LocalNow(), 26 - [This week]))),
				    #"Inserted year (wk) (relative)" = Table.AddColumn(#"Added Custom9", "Year (wk) (relative)", each if [#"Year (wk)"]=[#"This year (wk)"]
				then "This year"
				else [#"Year (wk)"]),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted year (wk) (relative)",{"This week", "Previous week", "This year (wk)"}),
				    #"Inserted year (relative)" = Table.AddColumn(#"Removed Columns", "Year (relative)", each if [Year]=Date.Year(DateTime.LocalNow())
				then "This year"
				else [Year]),
				    #"Inserted quarter (relative)" = Table.AddColumn(#"Inserted year (relative)", "Quarter (relative)", each if [Quarter]="Q"&Text.From(Date.QuarterOfYear(DateTime.LocalNow()))
				then "This quarter"
				else if [Quarter]="Q"&Text.From(Date.QuarterOfYear(DateTime.LocalNow())-1) or [Quarter]="Q"&Text.From(Date.QuarterOfYear(DateTime.LocalNow())+3)
				then "Previous quarter"
				else [Quarter]),
				    #"Inserted month name (relative)" = Table.AddColumn(#"Inserted quarter (relative)", "Month name (relative)", each if [#"Month no."]=Date.Month(DateTime.LocalNow())
				then "This month"
				else if [#"Month no."]=Date.Month(DateTime.LocalNow())-1 or [#"Month no."]=Date.Month(DateTime.LocalNow()) +11
				then "Previous month"
				else [#"Month name (long)"]),
				    #"Inserted Day of Year (wk)" = Table.AddColumn(#"Inserted month name (relative)", "Day of Year (wk) ", each Duration.Days(
				    [Date]-
				    Date.AddDays(#date([#"Year (wk)"],1,4),-1*
				    (
				        if Date.DayOfWeek(#date([#"Year (wk)"],1,4))=0
				        then 0
				        else Date.DayOfWeek(#date([#"Year (wk)"],1,4))
				    ))
				)),
				    #"Added Custom" = Table.AddColumn(#"Inserted Day of Year (wk)", "Start date year", each Date.AddDays(#date([#"Year (wk)"],1,4),1+
				-1*
				    (
				        if Date.DayOfWeek(#date([#"Year (wk)"],1,4))=0
				        then 0
				        else Date.DayOfWeek(#date([#"Year (wk)"],1,4))
				    ))),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Always", each 1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Year", Int64.Type}, {"Month no.", Int64.Type}, {"Month no. (leading zeros)", type text}, {"Month name (long)", type text}, {"Month name (short)", type text}, {"Quarter", type text}, {"Week of Year", Int64.Type}, {"Week of Month", Int64.Type}, {"Day", Int64.Type}, {"Day of week no.", Int64.Type}, {"Day of Year", Int64.Type}, {"Day of week", type text}, {"Day of week short", type text}, {"Year/Month no.", type text}, {"Year/Month name (short)", type text}, {"Year/Quarter", type text}, {"Week no.", Int64.Type}, {"Year (wk)", Int64.Type}, {"Year/Week", type text}, {"WY", Int64.Type}, {"Week no. (relative)", type text}, {"Year (wk) (relative)", type text}, {"Year (relative)", type text}, {"Quarter (relative)", type text}, {"Month name (relative)", type text}, {"Day of Year (wk) ", Int64.Type}, {"Start date year", type date}, {"Always", Int64.Type}, {"DateFormatted", type text}}),
				    #"Inserted Quarter1" = Table.AddColumn(#"Changed Type1", "Quarter.1", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Quarter no."}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns1", "Year/Month no.", "Year/Month no. - Copy"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column",{{"Year/Month no. - Copy", "Year/Period"}})
				in
				    #"Renamed Columns2"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

