table 'Fact Forecasting Medewerkers'
	lineageTag: 92aa7b64-6098-49bf-b67e-c200a2e13ec4

	column 'Medewerker ID'
		dataType: string
		lineageTag: 45845d3e-5c51-411d-b0ad-dfa812a8ad0e
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: 5ad1c3f9-2976-4e08-a1e6-e08d18ee0da2
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 79a9a20f-a4aa-4a62-bba9-1c0c2c3e9dfc
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: b7313e0a-ace7-4862-b8a9-0541b42ee23a
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: ba9edb3d-c924-457f-897c-4349998123fc
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column Rapportagecockpit_omschrijving
		dataType: string
		lineageTag: 706afcd1-46e5-48d3-b6c6-3528f80c8c6d
		summarizeBy: none
		sourceColumn: Rapportagecockpit_omschrijving

		annotation SummarizationSetBy = Automatic

	column 'Bruto Salaris'
		dataType: double
		lineageTag: 8982a931-c2fb-4bf7-a796-553c497b5e4b
		summarizeBy: sum
		sourceColumn: Bruto Salaris

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 314e2cb8-eff2-4f03-b264-2c8f81c48bbf
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: string
		lineageTag: 77eb5422-2de6-46cb-b3f4-31d04bad970c
		summarizeBy: none
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 94b6115f-ed4b-4ed6-a346-25bc6cd8d42b
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column SchaalType
		dataType: string
		lineageTag: a7ccccb2-3a30-4d8e-a35f-8666a07f933c
		summarizeBy: none
		sourceColumn: SchaalType

		annotation SummarizationSetBy = Automatic

	column '2434 - Salaris '
		dataType: double
		lineageTag: 1b6bfe4b-2edf-475f-81bd-4b2e8ddd903b
		summarizeBy: sum
		sourceColumn: "2434 - Salaris "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '3121 - Reservering Vakantiegeld Bedrag'
		dataType: double
		lineageTag: 110ff44e-775b-442b-9a5d-b2419f4a1b3e
		summarizeBy: sum
		sourceColumn: 3121 - Reservering Vakantiegeld Bedrag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '3135 - Vakantietoeslag Med Spec'
		dataType: double
		lineageTag: 44259d11-1f9f-4a08-a1d1-e94f4718f7a4
		summarizeBy: sum
		sourceColumn: 3135 - Vakantietoeslag Med Spec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '3105 - Pensioen Toeslag (BMP)'
		dataType: double
		lineageTag: cd0ef607-aa95-4803-9d8a-442743b133d3
		summarizeBy: sum
		sourceColumn: 3105 - Pensioen Toeslag (BMP)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2545 - Pensioen Toeslag'
		dataType: double
		lineageTag: 839bb296-3cb1-4511-8c38-91bcda6d2408
		summarizeBy: sum
		sourceColumn: 2545 - Pensioen Toeslag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '3105 - Pensioen Toeslag (BMP) (RvB)'
		dataType: double
		lineageTag: dd92b523-cec8-4418-a9ec-97ffab4b1ccd
		summarizeBy: sum
		sourceColumn: 3105 - Pensioen Toeslag (BMP) (RvB)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'WG Pensioen Toeslag (Andere OVK)'
		dataType: double
		lineageTag: 9a25a1c4-d10b-47cc-8e11-ff007fb88fb4
		summarizeBy: sum
		sourceColumn: WG Pensioen Toeslag (Andere OVK)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '3027 - Speciale Toelage'
		dataType: double
		lineageTag: 8804afce-1c69-4462-8e73-75398da5d0c1
		summarizeBy: sum
		sourceColumn: 3027 - Speciale Toelage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Kostenplaats
		dataType: string
		lineageTag: a126f76f-4ae2-400e-a0c3-45197eba1212
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column 'Bedrag (Tijdelijk)'
		dataType: double
		lineageTag: 20a9048d-56de-4841-83dd-d4ae530d0f7b
		summarizeBy: sum
		sourceColumn: Bedrag (Tijdelijk)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Forecasting Medewerkers' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Table.Combine({#"Fact Personeels Kosten 2024", #"Fact Personeels Kosten 2025", #"Fact Personeels Kosten 2021", #"Fact Personeels Kosten 2023", #"Fact Personeels Kosten 2022"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Omschrijving_klant", "Omschrijving LC"}, {"Medewerker", "Medewerker ID"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"Medewerker ID", "LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns", {"Grootboekrekening"}, #"Dim Grootboek", {"Code Grootboek"}, "Dim Grootboek", JoinKind.LeftOuter),
				    #"Expanded Dim Grootboek" = Table.ExpandTableColumn(#"Merged Queries", "Dim Grootboek", {"Rapportagecockpit_omschrijving"}, {"Rapportagecockpit_omschrijving"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded Dim Grootboek", each ([Rapportagecockpit_omschrijving] = "19 Lonen en salarissen" or [Rapportagecockpit_omschrijving] = "20 Sociale lasten" or [Rapportagecockpit_omschrijving] = "21 Overige personeelskosten")),
				    #"Merged Queries1" = Table.NestedJoin(#"Filtered Rows", {"Medewerker ID"}, #"Dim Medewerker Details", {"Medewerker ID"}, "Dim Medewerker Details", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker Details" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Medewerker Details", {"Kostenplaats", "Salaris", "Schaal ID"}, {"Kostenplaats", "Salaris", "Schaal ID"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded Dim Medewerker Details", "Year Forecasting", each Date.Year(DateTime.LocalNow()) + 1),
				    #"Invoked Custom Function" = Table.AddColumn(#"Added Custom", "Period Forecasting", each #"Forecasting Date Function"([Year Forecasting])),
				    #"Expanded Period Forecasting" = Table.ExpandTableColumn(#"Invoked Custom Function", "Period Forecasting", {"Period"}, {"Period"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded Period Forecasting", {"Medewerker ID", "LC", "Grootboekrekening", "Period"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Duplicates", {"Schaal ID"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries2", "Dim SchaalType", {"SchaalType"}, {"SchaalType"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Dim SchaalType",{{"Salaris", "Bruto Salaris"}}),
				    #"Added LC 2434 - Salaris" = Table.AddColumn(#"Renamed Columns1", "2434 - Salaris ", each if [LC] = "2434" then [Bruto Salaris] else null),
				    #"Added LC 3121" = Table.AddColumn(#"Added LC 2434 - Salaris", "3121 - Reservering Vakantiegeld Bedrag", each if [LC] = "3121" then ([Bruto Salaris] * 0.075) else null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added LC 3121",{{"3121 - Reservering Vakantiegeld Bedrag", type number}}),
				    #"Added LC 3135" = Table.AddColumn(#"Changed Type2", "3135 - Vakantietoeslag Med Spec", each if [LC] = "3135" then ([Bruto Salaris] * 0.075) else null),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added LC 3135",{{"3135 - Vakantietoeslag Med Spec", type number}}),
				    #"Added LNT WG Pensioen" = Table.AddColumn(#"Changed Type3", "3105 - Pensioen Toeslag (BMP)", each if [SchaalType] = "LNT" and [LC] = "3105" then [Bruto Salaris] * 0.10 else null),
				    #"Added CAO WG Pensioen" = Table.AddColumn(#"Added LNT WG Pensioen", "2545 - Pensioen Toeslag", each if [SchaalType] = "CAO" and [LC] = "2545" then ([Bruto Salaris] * 0.09) else null),
				    #"Added RvB WG Pensioen" = Table.AddColumn(#"Added CAO WG Pensioen", "3105 - Pensioen Toeslag (BMP) (RvB)", each if [LC] = "3105" then (if [Medewerker ID] = "502029" then ([Bruto Salaris] * 0.15) else if [Medewerker ID] = "500311" then ([Bruto Salaris] * 0.10) else if [Medewerker ID] = "500280" then ([Bruto Salaris] * 0.15) else if [Medewerker ID] = "40831" then ([Bruto Salaris] * 0.10) else null) else null),
				    #"Added Andere OVK WG Pensioen" = Table.AddColumn(#"Added RvB WG Pensioen", "WG Pensioen Toeslag (Andere OVK)", each if [SchaalType] = "Andere OVK" and [LC] = "2545"
				then ([Bruto Salaris] * 0.09) else if [SchaalType] = "Andere OVK" and [LC] = "3100" then ([Bruto Salaris] * 0.085) else if [SchaalType] = "Andere OVK" and [LC] = "3105" and [#"3105 - Pensioen Toeslag (BMP) (RvB)"] = null then ([Bruto Salaris] * 0.10) else null),
				    #"Added LC 3027 Speciale Toelage" = Table.AddColumn(#"Added Andere OVK WG Pensioen", "3027 - Speciale Toelage", each if [LC] = "3027" then ([Bruto Salaris] * 0.057) else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added LC 3027 Speciale Toelage",{{"2434 - Salaris ", type number}, {"3121 - Reservering Vakantiegeld Bedrag", type number}, {"3135 - Vakantietoeslag Med Spec", type number}, {"3105 - Pensioen Toeslag (BMP)", type number}, {"2545 - Pensioen Toeslag", type number}, {"3105 - Pensioen Toeslag (BMP) (RvB)", type number}, {"WG Pensioen Toeslag (Andere OVK)", type number}, {"3027 - Speciale Toelage", type number}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "Bedrag (Tijdelijk)", each Text.Combine({Text.From([#"2434 - Salaris "], "en-US"), Text.From([#"3121 - Reservering Vakantiegeld Bedrag"], "en-US"), Text.From([#"3135 - Vakantietoeslag Med Spec"], "en-US"), Text.From([#"3105 - Pensioen Toeslag (BMP)"], "en-US"), Text.From([#"2545 - Pensioen Toeslag"], "en-US"), Text.From([#"3105 - Pensioen Toeslag (BMP) (RvB)"], "en-US"), Text.From([#"WG Pensioen Toeslag (Andere OVK)"], "en-US"), Text.From([#"3027 - Speciale Toelage"], "en-US")}, ""), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Merged Column",{{"Bedrag (Tijdelijk)", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

