table 'Fact Forecasting Medewerkers Soft Landing'
	lineageTag: a997c2a0-d67c-45fd-b42d-421bd265097c

	column 'Medewerker ID'
		dataType: string
		lineageTag: 098e2b3d-9322-41e5-869a-eb2ab8145690
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: 488cb518-3bd8-4e78-908d-5663091e3715
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: f4b88bf4-d8f4-49c5-bfae-598b25076632
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: 5e68c48f-bbd5-4fdb-922b-f29bd8bed268
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: 583cdc18-7785-4543-a1af-c433ffe4aeb1
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: e2e189af-de46-4845-aaf2-4336abd06542
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rapportagecockpit_omschrijving
		dataType: string
		lineageTag: 38b2283e-cd39-43dd-bf58-90f974e619ee
		summarizeBy: none
		sourceColumn: Rapportagecockpit_omschrijving

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: int64
		formatString: 0
		lineageTag: 3da12a8b-8fe1-409f-8dec-1251b94a3b27
		summarizeBy: sum
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: double
		lineageTag: cc4e146b-6577-4a77-8525-dc608d3564c6
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: c382b4f0-33f1-4a35-a509-f60e74391561
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 46ecd2b1-0ad9-4724-85ce-f422cb82a4b7
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: f8c2d583-eb78-429d-bc85-ce5fc60cc993
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 3fa66974-0fc0-49c8-8f50-760440d5fd31
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: 3625bb96-dd9f-4e18-970f-81ce917ed277
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Period (leading zeros)'
		dataType: string
		lineageTag: 26ae4090-a8f8-4ffa-9803-9dce6c16ee96
		summarizeBy: none
		sourceColumn: Period (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 131927e0-528f-4780-bcc6-ade2597f1a50
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Softlanding per Maand'
		dataType: double
		lineageTag: f9a17763-2834-48a7-a92e-05137cecc340
		summarizeBy: sum
		sourceColumn: Softlanding per Maand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Forecasting Medewerkers Soft Landing' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Buffered Fact Forecasting Medewerkers",
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type number}, {"FTE", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [LC] = "3164"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Medewerker ID", "LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving", "FTE", "Rapportagecockpit_omschrijving", "Year Forecasting", "Period", "Anniversary Month", "Kostenplaats", "Naam_werkgever", "Schaal ID", "Type Personeel ID", "Period (leading zeros)", "Year/Period", "Softlanding per Maand"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

