table 'Fact Salaris Indexering Actuals'
	lineageTag: fbdaa7c8-80bc-4235-afd4-ccd0768b294a

	column Jaar
		dataType: double
		formatString: 0
		lineageTag: 3188398a-3288-4a9f-b7ee-4fc1745883b4
		summarizeBy: sum
		sourceColumn: Jaar

		annotation SummarizationSetBy = Automatic

	column Boekingsperiode
		dataType: double
		lineageTag: cddf5104-624c-4a53-8d2c-53fd3e1214f9
		summarizeBy: sum
		sourceColumn: Boekingsperiode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Medewerker ID'
		dataType: string
		lineageTag: 47952a56-8ebf-45b0-86ba-bf479809ba49
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: 18d18e83-b97a-452e-a4e9-4fcca13eab88
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 4ece0313-2375-4634-ac4e-dd1c5cf6b8cd
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Waarde
		dataType: double
		lineageTag: 716fa3b4-0ba3-40e6-8ba3-bae75ea67b97
		summarizeBy: sum
		sourceColumn: Waarde

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bedrag_credit
		dataType: double
		lineageTag: c479bca9-8809-49fc-8661-87bb61de63f3
		summarizeBy: sum
		sourceColumn: Bedrag_credit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Grootboekrekening
		dataType: string
		lineageTag: b73944fa-ffb5-460c-be3c-9c4a2a46bfa6
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: 20c75330-8e2c-4a0f-b3e6-311b38c05d75
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column IsExtrapolated
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: edc48359-6006-4d0b-b081-ba1adcf981a8
		summarizeBy: none
		sourceColumn: IsExtrapolated

		annotation SummarizationSetBy = Automatic

	column OriginalBoekingsperiode
		dataType: double
		formatString: 0
		lineageTag: 88fe4414-40e7-4507-b775-3d112d80baa4
		summarizeBy: sum
		sourceColumn: OriginalBoekingsperiode

		annotation SummarizationSetBy = Automatic

	column 'Boekingsperiode (leading zeros)'
		dataType: string
		lineageTag: 757cf075-2729-4996-8f1c-5bacd0fb24ef
		summarizeBy: none
		sourceColumn: Boekingsperiode (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 24ab4631-6766-4b98-b5de-95322b6b6881
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: dbda85c5-3355-4444-9ad4-14e1e6b65f07
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: 45f1d12d-c141-4d32-b33d-f081f3d40a0b
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column 'Trede Verhoging'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2e8625e3-b6bf-4762-889f-f8129f8042e2
		summarizeBy: none
		sourceColumn: Trede Verhoging

		annotation SummarizationSetBy = Automatic

	column 'Schaal.MAX Trede'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e93f0f82-0a1e-4736-a4da-f83ca937eb33
		summarizeBy: none
		sourceColumn: Schaal.MAX Trede

		annotation SummarizationSetBy = Automatic

	column 'Bedrag (OLD)'
		dataType: double
		lineageTag: be19e4d4-5d42-4ba6-a1a9-1b0e2312e160
		summarizeBy: sum
		sourceColumn: Bedrag (OLD)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris (Schaal ID New)'
		dataType: double
		lineageTag: 6ce633a3-1786-4bc1-b8ad-c204bb7baa40
		summarizeBy: sum
		sourceColumn: Salaris (Schaal ID New)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bedrag (New)'
		dataType: double
		lineageTag: 3f1f0781-862e-4e43-b021-852a3a35aef4
		summarizeBy: sum
		sourceColumn: Bedrag (New)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Kostenplaats
		dataType: string
		lineageTag: 18464500-5742-4b68-a24b-3d69e73d8bde
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column 'Schaal.SchaalType'
		dataType: string
		lineageTag: 38aecb05-af09-454e-9316-56be1af66e65
		summarizeBy: none
		sourceColumn: Schaal.SchaalType

		annotation SummarizationSetBy = Automatic

	column Indexering
		dataType: double
		lineageTag: 9b54797c-e72b-47d3-8988-3b822bbea83d
		summarizeBy: sum
		sourceColumn: Indexering

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Index Name'
		dataType: string
		lineageTag: 545d139b-3d23-4574-aa7e-fdfe092c3ed4
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	column 'Bedrag Incl Indexering'
		dataType: double
		lineageTag: 8526b5a3-6936-412e-a4be-3e86ca833833
		summarizeBy: sum
		sourceColumn: Bedrag Incl Indexering

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type Personeel ID'
		dataType: string
		lineageTag: 9fff8e14-bf00-4301-9456-0a61976048a6
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: 1fc0b350-765b-4277-b6b8-021caf00d0bc
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Naam_werkgever
		dataType: string
		lineageTag: fd286e93-9518-4391-8e94-4af7d9ea4977
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID (New)'
		dataType: double
		lineageTag: 68e38b47-7e9d-4b55-aa66-6d05154d1995
		summarizeBy: none
		sourceColumn: Schaal ID (New)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Salaris Indexering Actuals' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Extrapolatie Salaris Indexering Actuals"(#"Fact Salaris Indexering Actuals Source"),
				    #"Changed Type9" = Table.TransformColumnTypes(Source,{{"Jaar", type number}, {"Boekingsperiode", type number}, {"Waarde", type number}, {"Bedrag_credit", type number}, {"FTE", type number}, {"OriginalBoekingsperiode", type number}, {"Kostenplaats", type text}, {"LC", type text}, {"Omschrijving LC", type text}, {"Grootboekrekening", type text}, {"Grootboekrekening_omschrijving", type text}, {"Naam_werkgever", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type9", "Boekingsperiode (leading zeros)", each Text.PadStart(Text.From([Boekingsperiode]),2,"0"), type nullable text),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Year/Period", each Text.From([Jaar]) & "/" & Text.From([#"Boekingsperiode (leading zeros)"]), type nullable text),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"IsExtrapolated", type logical}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Medewerker ID"}, #"Dim Medewerker", {"Medewerker ID"}, "Dim Medewerker", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker" = Table.ExpandTableColumn(#"Merged Queries", "Dim Medewerker", {"Schaal ID", "Type Personeel ID", "Anniversary Month"}, {"Schaal ID", "Type Personeel ID", "Anniversary Month"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim Medewerker", {"Schaal ID"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries1", "Dim SchaalType", {"SchaalType", "MAX Trede"}, {"Schaal.SchaalType", "Schaal.MAX Trede"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Dim SchaalType",{{"Schaal.SchaalType", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Trede Verhoging", each if [IsExtrapolated] = false or [Type Personeel ID] = "Z_3" or [#"Schaal.MAX Trede"] = true then false else if ([IsExtrapolated] = true and [Boekingsperiode] >= [Anniversary Month] and [#"Schaal.MAX Trede"] = false) then true else null, type logical),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Bedrag (OLD)", each [Waarde] - [Bedrag_credit], type nullable number),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Schaal ID (New)", each if [Trede Verhoging] = true and [Type Personeel ID] <> "Z_3" then ([Schaal ID] + 1) else [Schaal ID], type nullable number),
				    #"Merged Queries2" = Table.NestedJoin(#"Added Custom4", {"Schaal ID (New)"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType1" = Table.ExpandTableColumn(#"Merged Queries2", "Dim SchaalType", {"Salaris"}, {"Salaris"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Expanded Dim SchaalType1",{{"Salaris", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type5",{{"Salaris", "Salaris (Schaal ID New)"}}),
				    #"Added Custom5" = Table.AddColumn(#"Renamed Columns", "Bedrag (New)", each if [Trede Verhoging] = false then [#"Bedrag (OLD)"] else [#"Salaris (Schaal ID New)"], type nullable number),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Index Name", each "5,4,3,2,1,0", type nullable text),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Added Custom6", {{"Index Name", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Index Name"),
				    #"Added Suffix" = Table.TransformColumns(#"Split Column by Delimiter", {{"Index Name", each _ & ".00%", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Added Suffix", "Index Name", "Indexering", type nullable number),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Duplicated Column",{{"Indexering", type number}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type7", "Bedrag Incl Indexering", each if [Boekingsperiode] >= 7 and ([Type Personeel ID] = "Z_1" or [Type Personeel ID] = "Z_3" or [Type Personeel ID] = "Z_10" or [Type Personeel ID] = "Z_15") or [Schaal.SchaalType] = "Andere OVK" then [#"Bedrag (New)"] else if [Boekingsperiode] < 7 then [#"Bedrag (New)"] else ([#"Bedrag (New)"] * [Indexering]) + [#"Bedrag (New)"], type nullable number)
				in
				    #"Added Custom7"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

