table 'Fact Forecasting MdW LC Overig per GB'
	lineageTag: a8e5b345-9cb6-4500-a3b0-9de2e84bb0f9

	column 'Medewerker ID'
		dataType: string
		lineageTag: 881c0eee-9ad8-4662-a904-ec73e038f8cd
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: string
		lineageTag: b237ef2c-9114-4f55-bc12-42675e4937dc
		summarizeBy: none
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: int64
		formatString: 0
		lineageTag: c1c1e72d-b79a-45b0-b3fb-d1c47655ed39
		summarizeBy: sum
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 0df66cf6-fe56-495e-a208-ea8cf213138d
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: e5ed0b8b-21d7-45f6-9a3b-8a848841c1fd
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: c2bdd897-f4ae-4dcb-8907-40ecb72560d3
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: c32838ef-566b-43e8-919f-65f04e85ea8c
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: c5a35266-9d9b-4f91-90da-1ff13fc26f0d
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Period (leading zeros)'
		dataType: string
		lineageTag: ab120d42-571c-403e-a5a8-bae7807b3964
		summarizeBy: none
		sourceColumn: Period (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 968244db-c0d2-4db8-9794-84845776a662
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Index Name Actuals'
		dataType: string
		lineageTag: 4aa3eb60-0f60-4f1e-bc75-0514650b2d23
		summarizeBy: none
		sourceColumn: Index Name Actuals

		annotation SummarizationSetBy = Automatic

	column 'Max Salaris End Actuals'
		dataType: double
		lineageTag: 9e5e99b6-a876-43bc-b4a4-50742b7a5cbe
		summarizeBy: sum
		sourceColumn: Max Salaris End Actuals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Schaal ID (Trede Verhoging Actuals)'
		dataType: double
		lineageTag: 66bd18fb-ef1a-4cbe-8c24-2114b436cda7
		summarizeBy: sum
		sourceColumn: New Schaal ID (Trede Verhoging Actuals)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MAX Trede Actuals'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7f4c3b52-4057-4349-86a4-293e236b99f9
		summarizeBy: none
		sourceColumn: MAX Trede Actuals

		annotation SummarizationSetBy = Automatic

	column 'SchaalType Forecasting'
		dataType: string
		lineageTag: 7ddd3cd1-accd-4059-9ad1-5c50ee3798cc
		summarizeBy: none
		sourceColumn: SchaalType Forecasting

		annotation SummarizationSetBy = Automatic

	column 'Trede Verhoging (Forecasting)'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 81613511-e005-4ce2-ba7e-b6bde5282768
		summarizeBy: none
		sourceColumn: Trede Verhoging (Forecasting)

		annotation SummarizationSetBy = Automatic

	column 'New Schaal ID (Forecasting)'
		dataType: int64
		formatString: 0
		lineageTag: 964fe0c8-f4fa-4f97-968f-282b1dc206ba
		summarizeBy: none
		sourceColumn: New Schaal ID (Forecasting)

		annotation SummarizationSetBy = Automatic

	column 'Salaris New Forecasting'
		dataType: double
		lineageTag: 5fa09cfa-ead8-498d-983a-ac6aae46aee8
		summarizeBy: sum
		sourceColumn: Salaris New Forecasting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris Base Forecasting Original'
		dataType: double
		lineageTag: ccd6a5ba-d404-4808-80f4-91cd8c55c109
		summarizeBy: sum
		sourceColumn: Salaris Base Forecasting Original

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris per Mnd'
		dataType: double
		lineageTag: c457d220-4ad2-4931-adcc-13640792f7b9
		summarizeBy: sum
		sourceColumn: Salaris per Mnd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris Base Forecasting'
		dataType: double
		lineageTag: 9d2e6e14-ec8a-4bb2-9913-a20212d0f77c
		summarizeBy: sum
		sourceColumn: Salaris Base Forecasting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC
		dataType: string
		lineageTag: 2ddeaa25-70a7-43ad-9932-7dffde283d21
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: 3472c923-2760-44a1-b407-c37ac1aef0b8
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column '(M) GB 4101100 - Maaltijd Vergoeding' =
			
			VAR total  = [(WA) GB 4101100 - Maaltijd Vergoeding]
			VAR n =
			    CALCULATE(
			        DISTINCTCOUNT('Dim Medewerker'[Medewerker ID]),
			        ALL('Dim Medewerker'),
			        'Dim Medewerker'[Flag Maaltijdvergoeding] = 1,
			        'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1,
			        'Dim Medewerker'[Status_dienstverband] = "In dienst"
			    )
			VAR perMedewerker = DIVIDE(total, n, BLANK())
			RETURN
			IF (
			    'Fact Forecasting MdW LC Overig per GB'[Grootboekrekening] = "4101100" &&
			    RELATED('Dim Medewerker'[Flag Maaltijdvergoeding]) = 1 &&
			    RELATED('Dim Medewerker'[Medewerkers in Fact Forecasting]) = 1 &&
			    RELATED('Dim Medewerker'[Status_dienstverband]) = "In dienst",
			    DIVIDE(perMedewerker, 12, BLANK()),
			    BLANK()
			)
		lineageTag: e5859bd9-475c-46bc-a0f8-a117698a573e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(M) GB 4125100 - Personeel niet in Loondienst' = ```
			
			VAR selectedGL = 'Fact Forecasting MdW LC Overig per GB'[Grootboekrekening]
			
			VAr basesetmedewerker = 
			FILTER(
			    'Dim Medewerker',
			    'Dim Medewerker'[Flag GB 4125100 - Personeel niet in loondienst] = 1 &&
			    'Dim Medewerker'[Status_dienstverband] = "In dienst" && 
			    'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			)
			
			VAR countmedewerkers = 
			CALCULATE(
			    COUNTROWS('Dim Medewerker'),
			    ALL('Dim Medewerker'),
			    basesetmedewerker
			)
			VAR total = [(WA) GB 4125100 - Personeel niet in Loondienst]
			
			VAR personeelnietinloondienst = 
			CALCULATE(
			    DIVIDE([(WA) GB 4125100 - Personeel niet in Loondienst], countmedewerkers, BLANK()),
			    basesetmedewerker,
			    KEEPFILTERS('Fact Forecasting MdW LC Overig per GB'[Flag Personeel Niet in Loondienst] = 1)
			)
			
			RETURN
			IF(
			    selectedGL = "4125100" && 'Fact Forecasting MdW LC Overig per GB'[Flag Personeel Niet in Loondienst] = 1, 
			    DIVIDE(personeelnietinloondienst, 12, BLANK()),
			    BLANK()
			)
			
			```
		lineageTag: e2eba0de-d400-4c7d-b39c-4ec262a5e03a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Flag Maaltijdvergoeding' =
			
			IF(
			    RELATED('Dim Medewerker'[Flag Maaltijdvergoeding]) = 1,
			    1,
			    0)
		formatString: 0
		lineageTag: a4b83809-c306-45c3-bdbd-f6c42544f4bd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag Personeel Niet in Loondienst' =
			
			IF(
			    RELATED('Dim Medewerker'[Flag GB 4125100 - Personeel niet in loondienst]) = 1,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 24825f57-4651-4f83-8220-1374f32464fe
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Fact Forecasting MdW LC Overig per GB' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Buffered Fact Forecasting Medewerkers",
				    #"Removed Other Columns1" = Table.SelectColumns(Source, {"Medewerker ID", "FTE", "Year Forecasting", "Period", "Anniversary Month", "Kostenplaats", "Schaal ID", "Type Personeel ID", "Period (leading zeros)", "Year/Period", "Index Name Actuals", "Max Salaris End Actuals", "New Schaal ID (Trede Verhoging Actuals)", "MAX Trede Actuals", "SchaalType Forecasting", "Trede Verhoging (Forecasting)", "New Schaal ID (Forecasting)", "Salaris New Forecasting", "Salaris Base Forecasting Original", "Salaris per Mnd", "Salaris Base Forecasting"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns1", {"Medewerker ID", "Period", "Index Name Actuals", "MAX Trede Actuals", "Trede Verhoging (Forecasting)", "New Schaal ID (Forecasting)", "Salaris Base Forecasting", "Kostenplaats"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "LC 0001 Overig", each #"LC Overig"),
				    #"Expanded Column1" = Table.ExpandTableColumn(#"Added Custom", "LC 0001 Overig", {"LC"}, {"LC"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded Column1", {"LC"}, #"Dim KPT LC per GB", {"LC"}, "Dim KPT LC per GB", JoinKind.LeftOuter),
				    #"Expanded Dim KPT LC per GB" = Table.ExpandTableColumn(#"Merged Queries", "Dim KPT LC per GB", {"Grootboekrekening"}, {"Grootboekrekening"})
				in
				    #"Expanded Dim KPT LC per GB"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

