table 'Fact Forecasting Vacatures'
	lineageTag: 114278a5-cda5-4b3a-90a9-11a9655cd651

	column Formatieplaats
		dataType: string
		lineageTag: 6eb454c5-4054-4464-867d-cf02d80a2137
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		lineageTag: bac9796f-84d8-4bcf-b597-b5dfd3800cad
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 4c954f83-0c8f-49d7-b11c-2da6ea9f82a2
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 0c59f5ab-9955-48d2-964f-7efeda1434c5
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Salaris Incl Indexering'
		dataType: double
		lineageTag: 35ea5606-a70f-4161-badf-11959d30d59f
		summarizeBy: sum
		sourceColumn: Salaris Incl Indexering

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Schaal ID'
		dataType: double
		formatString: 0
		lineageTag: 094613f2-7f58-44b7-885a-7a5f91507069
		summarizeBy: none
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Index Name'
		dataType: string
		lineageTag: 3cc90095-c5ae-409e-bf8c-da69e41bf373
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: 28d2ad2c-8923-4126-96a1-7c81caa22284
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: int64
		lineageTag: cf9e9fd9-1a16-4ce2-8dcc-1f89ae315866
		summarizeBy: sum
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Percentage Key'
		dataType: string
		lineageTag: b062130d-285e-4ace-8bd4-73ce12dbf4af
		summarizeBy: none
		sourceColumn: Percentage Key

		annotation SummarizationSetBy = Automatic

	column 'Salaris Incl Indexering * (Verschil FTE)' = 'Fact Forecasting Vacatures'[Salaris Incl Indexering] * 'Fact Forecasting Vacatures'[Verschil per Vac (FTE)]
		lineageTag: 3980e3b0-48aa-4cd4-a10d-308f7ebfbed8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Formatieplaats Key'
		dataType: string
		lineageTag: 4a419f15-e722-4f85-a35a-78bd69f3ef8d
		summarizeBy: none
		sourceColumn: Formatieplaats Key

		annotation SummarizationSetBy = Automatic

	column 'Medewerker ID'
		dataType: string
		lineageTag: 2e4e9c00-8320-4eb3-b9ad-4d918c503b7d
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 0b72b50e-e115-4c4a-a45f-4ee1373ae876
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'WN bijdrage pensioen (LNT)' =
			
			VAR salaris = 'Fact Forecasting Vacatures'[Salaris Incl Indexering * (Verschil FTE)]
			VAR schaaltype = 'Fact Forecasting Vacatures'[SchaalType]
			
			RETURN
			IF(
			    schaaltype = "LNT",
			    salaris * 0.10
			)
		lineageTag: e1e158f9-af0c-4932-bf9f-4cc4903df915
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'WN bijdrage pensioen (CAO)' =
			
			VAR salaris = 'Fact Forecasting Vacatures'[Salaris Incl Indexering * (Verschil FTE)]
			VAR schaaltype = 'Fact Forecasting Vacatures'[SchaalType]
			
			RETURN
			IF(
			    schaaltype = "CAO",
			    salaris * 0.05 * 12,
			    BLANK()
			)
		lineageTag: bf41bcec-ef98-4ee8-9f6c-5f4258a0e4e4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Flag Medische Specialisten' = RELATED('Dim Medewerker'[Flag Medische Specialisten])
		formatString: 0
		lineageTag: 4eb5509b-640a-47f8-8cee-7440d91f8250
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Flag overwerk 200% en 300%' = RELATED('Dim Medewerker'[Flag Overtime 200% and 300% Type Personeel])
		formatString: 0
		lineageTag: dacf26c5-a1d4-45c4-a93d-1bca2a8424d5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '(M) LC 3091 - WG Ziektekosten Specialisten' =
			
			VAR flagmedspec = 'Fact Forecasting Vacatures'[Flag Medische Specialisten]
			VAR selectedLC = 'Fact Forecasting Vacatures'[LC]
			RETURN
			IF(
			    flagmedspec = 1 && selectedLC = "3091",
			    DIVIDE(13000, 12, BLANK()),
			    BLANK()
			)
		lineageTag: 56db8050-956c-42fc-8491-cebc297cea27
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC
		dataType: string
		lineageTag: b55e6298-8933-4f44-a6b4-f7e544aa231c
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 5ebc69ce-eaa9-492d-b052-589b8b0dc1fd
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: 5906a568-3439-4563-8733-f082721a1a90
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: eb14b197-40ed-4213-bc45-4d92b86acb1d
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column '(V) LC 3080 Beroepkosten (Specialisten)' =
			
			VAR selectedGL = 'Fact Forecasting Vacatures'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Vacatures'[LC]
			VAR medspec = 'Fact Forecasting Vacatures'[Flag Medische Specialisten]
			RETURN
			IF(
			    selectedLC = "3080" && medspec = 1,
			    DIVIDE(14000, 12, BLANK()) * 'Fact Forecasting Vacatures'[Verschil per Vac (FTE)],
			    BLANK()
			)
		lineageTag: 7ef6933a-64d0-4233-a532-34bb2f3cee34
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(V) GB 4114000 - Cessantia' = ```
			
			VAR selectedGL = 'Fact Forecasting Vacatures'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Vacatures'[LC]
			
			
			
			RETURN
			IF(
			    selectedGL = "4114000" && selectedLC = "0001",
			    DIVIDE(40,12,BLANK()),
			    BLANK()
			)
			
			
			
			```
		lineageTag: 9b5de2b8-66c3-4144-a679-c139be16b007
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(V) GB 4101100 - Maaltijd Vergoeding' = ```
			
			VAR selectedGl = 'Fact Forecasting Vacatures'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Vacatures'[LC]
			VAR FTE =
			CALCULATE(
			    [FTE Forecasting Medewerker (max period at total)],
			    ALL('Dim Looncomponent'),
			    ALL('Dim Grootboek'),
			    ALL('Dim Medewerker')
			)
			VAR ratio = DIVIDE(15000, FTE)
			
			VAR amount = ratio * 'Fact Forecasting Vacatures'[Verschil per Vac (FTE)]
			
			RETURN
			IF(
			    selectedGl = "4101100" && selectedLC = "0001" && RELATED('Dim Medewerker'[Flag Maaltijdvergoeding]) = 1,
			    DIVIDE(amount, 12, BLANK()),
			    BLANK()
			)
			
			```
		lineageTag: e5b81b40-496f-4033-a510-8c36bb329077
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type Zorg Functie'
		dataType: string
		lineageTag: 4b117bac-5a28-429d-8dbd-a40540909039
		summarizeBy: none
		sourceColumn: Type Zorg Functie

		annotation SummarizationSetBy = Automatic

	column 'Max Schaal/Trede'
		dataType: string
		lineageTag: cb415885-42fa-4706-a187-18e6ecb6438d
		summarizeBy: none
		sourceColumn: Max Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column SchaalType
		dataType: string
		lineageTag: 27a76ff6-fdf4-47d9-a959-edd416df0362
		summarizeBy: none
		sourceColumn: SchaalType

		annotation SummarizationSetBy = Automatic

	column 'Verschil per Vac (FTE)'
		dataType: double
		lineageTag: 30e107b8-7d70-447e-be3b-b93625aacd4a
		summarizeBy: sum
		sourceColumn: Verschil per Vac (FTE)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris (incl %)'
		dataType: double
		lineageTag: c1241e55-a234-4f13-b1bf-b67f5cabe1ae
		summarizeBy: sum
		sourceColumn: Salaris (incl %)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(V) GB 4120500 - Werving en selectiekosten' =
			
			VAR selectedGL = 'Fact Forecasting Vacatures'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Vacatures'[LC]
			VAR flagmedspec = 'Fact Forecasting Vacatures'[Flag Medische Specialisten]
			
			VAR kosten = DIVIDE(1800, 12, BLANK())
			
			RETURN
			IF(
			    selectedGL = "4120500" && selectedLC = "3139" && flagmedspec = 1,
			    kosten,
			    BLANK()
			)
		lineageTag: bf176ace-f9c7-4e3d-bf7e-8533642c5e3b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Percentage Name CAO'
		dataType: string
		lineageTag: 532cfc1c-0bf0-429e-a69e-66de0749cb25
		summarizeBy: none
		sourceColumn: Percentage Name CAO

		annotation SummarizationSetBy = Automatic

	column 'Percentage Name LNT'
		dataType: string
		lineageTag: d285a14b-1ccb-4469-b97c-4886a9bcb423
		summarizeBy: none
		sourceColumn: Percentage Name LNT

		annotation SummarizationSetBy = Automatic

	partition 'Fact Forecasting Vacatures' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = #"Dim Vacatures Medewerker (STG) Test",
				    #"Renamed Columns2" = Table.RenameColumns(Source,{{"Dim Zorg.Type Zorg Functie", "Type Zorg Functie"}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Renamed Columns2",{{"Type Zorg Functie", Text.Trim, type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Trimmed Text1",{"Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begin Datum", "Eind Datum", "C/A Formatie ID", "Type Zorg Functie", "Type Personeel ID", "Max Schaal/Trede", "Schaal ID", "SchaalType", "Salaris"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Type Personeel ID", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"Salaris", "Bruto Salaris"}}),
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns1", "Year Forecasting", each Date.Year([Begin Datum]) + 1, Int64.Type),
				    #"Merged Queries" = Table.NestedJoin(#"Inserted Year", {"Formatieplaats"}, #"Dim Vacature per Verschil FTE Test", {"Formatieplaats"}, "Dim Vacature per Verschil FTE Test", JoinKind.LeftOuter),
				    #"Expanded Dim Vacature per Verschil FTE Test" = Table.ExpandTableColumn(#"Merged Queries", "Dim Vacature per Verschil FTE Test", {"Verschil (excl)", "Medewerker ID"}, {"Verschil (excl)", "Medewerker ID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Dim Vacature per Verschil FTE Test",{{"Verschil (excl)", "Verschil per Vac (FTE)"}}),
				
				    DimPeriod = Table.Buffer(#"Dim Period"),
				
				    #"Merged Dim Period" = Table.NestedJoin(#"Renamed Columns", {"Year Forecasting"},  DimPeriod, {"Year"}, "Dim Period", JoinKind.LeftOuter),
				    #"Expanded Dim Period" = Table.ExpandTableColumn(#"Merged Dim Period", "Dim Period", {"Month no.", "Year/Period"}, {"Month no.", "Year/Period"}),
				
				    DimLCperGB = Table.Buffer(#"Dim LC per GL Support"),
				
				    #"DimLCperGLSupport" = Table.AddColumn(#"Expanded Dim Period", "Dim LC per GB", each DimLCperGB),
				    #"Expanded Support" = Table.ExpandTableColumn(#"DimLCperGLSupport", "Dim LC per GB", {"LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving"}, {"LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving"}),
				
				    DimPerCAO = Table.Buffer(#"Dim Percentage Vacature CAO"), // Buffer table to increase performance
				    DimPerLNT = Table.Buffer(#"Dim Percentage Vacature LNT"), // Buffer table to increase performance
				
				    #"Merged Dim Per CAO" = Table.NestedJoin(#"Expanded Support", {"SchaalType"}, DimPerCAO, {"SchaalType"}, "Dim Percentage Vacature CAO", JoinKind.LeftOuter),
				    #"Expanded Dim Percentage Vacature CAO" = Table.ExpandTableColumn(#"Merged Dim Per CAO", "Dim Percentage Vacature CAO", {"Percentage", "Percentage Name"}, {"Percentage", "Percentage Name"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Expanded Dim Percentage Vacature CAO",{{"Percentage", "Percentage CAO"}, {"Percentage Name", "Percentage Name CAO"}}),
				    #"Merged Dim Per LNT" = Table.NestedJoin(#"Renamed Columns3", {"SchaalType"}, DimPerLNT, {"SchaalType"}, "Dim Percentage Vacature LNT", JoinKind.LeftOuter),
				    #"Expanded Dim Percentage Vacature LNT" = Table.ExpandTableColumn(#"Merged Dim Per LNT", "Dim Percentage Vacature LNT", {"Percentage", "Percentage Name"}, {"Percentage", "Percentage Name"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Expanded Dim Percentage Vacature LNT",{{"Percentage", "Percentage LNT"}, {"Percentage Name", "Percentage Name LNT"}}),
				    #"Added Custom Perc Key" = Table.AddColumn(#"Renamed Columns4", "Percentage Key", each if [SchaalType] = "CAO" then Text.From([Percentage Name CAO]) & "_" & Text.From([SchaalType]) else if [SchaalType] = "LNT" then Text.From([Percentage Name LNT]) & "_" & Text.From([SchaalType]) else null, type nullable text),
				    #"Added Salaris Perc" = Table.AddColumn(#"Added Custom Perc Key", "Salaris (incl %)", each if [SchaalType] = "CAO" then ([Bruto Salaris] * [Percentage CAO]) else if [SchaalType] = "LNT" then ([Bruto Salaris] * [Percentage LNT]) else null, type nullable number),
				
				    IndexVac = Table.Buffer(#"Dim Indexering Vacatures"),
				
				    #"Added Dim Index Vac" = Table.AddColumn(#"Added Salaris Perc", "Dim Indexering Vacatures", each IndexVac),
				    #"Expand Dim Index Vac" = Table.ExpandTableColumn(#"Added Dim Index Vac", "Dim Indexering Vacatures", {"Indexering", "Index Name"}, {"Indexering", "Index Name"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Expand Dim Index Vac",{{"Month no.", "Month"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns5", "Salaris", each 
				        if [SchaalType] = "CAO" 
				        then (if [Month] < 7 
				                then [#"Salaris (incl %)"] 
				                else ([#"Salaris (incl %)"] + ([#"Salaris (incl %)"] * [Indexering]))
				            ) 
				        else if [SchaalType] = "LNT" 
				        then ( if [Month] >= 7 and ([Type Zorg Functie] = "Medisch Specialisten" or [Type Zorg Functie] = "Arts-assistenten") 
				                then [#"Salaris (incl %)"] 
				                else if [Month] < 7 
				                then [#"Salaris (incl %)"] 
				                else ([#"Salaris (incl %)"] + ([#"Salaris (incl %)"] * [Indexering]))
				            )
				        else null, type nullable number),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Formatieplaats Key", each Text.From([Medewerker ID]) & "_" & Text.From([Month]), type nullable text),
				    #"Renamed Columns6" = Table.RenameColumns(#"Added Custom1",{{"Salaris", "Salaris Incl Indexering"}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns6",{"Formatieplaats", "Omschrijving", "Kostenplaats", "Type Zorg Functie", "Type Personeel ID", "Max Schaal/Trede", "Schaal ID", "SchaalType", "Year Forecasting", "Verschil per Vac (FTE)", "Medewerker ID", "Month", "Year/Period", "LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving", "Percentage Name CAO", "Percentage Name LNT", "Percentage Key", "Salaris (incl %)", "Index Name", "Salaris Incl Indexering", "Formatieplaats Key"})
				in
				    #"Removed Other Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

