table 'Fact Forecasting Medewerkers Salaris'
	lineageTag: d91f9453-ed3e-4d00-948b-c8d73cf3731a

	column 'Medewerker ID'
		dataType: string
		lineageTag: b1aa7e17-f76d-4be2-bc23-b14ad7c747e5
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: 9061ea51-713d-4f8a-b752-d910732ef30a
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Year Forecasting'
		dataType: int64
		formatString: 0
		lineageTag: 72645f14-f6cf-4bfe-946f-35dc8c091168
		summarizeBy: sum
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: double
		lineageTag: d416d39d-acca-4725-834e-5a11ba01878c
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: 9df6a7d4-6404-4810-9879-d6fbf9efa319
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 478ab20d-58a8-4699-af62-b105f204e2de
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: b4c54f77-25a0-440a-bb3c-999fd267b55d
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: 81bfb8aa-017d-4ece-a9c0-64da2ce9b52a
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Period (leading zeros)'
		dataType: string
		lineageTag: 5ad9ab2a-31dd-4b26-9105-ee97550ec275
		summarizeBy: none
		sourceColumn: Period (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 71a3a7bd-29ac-4717-9d21-6243039fb6bd
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Index Name Actuals'
		dataType: string
		lineageTag: b9c2fd88-c5c7-4986-95ed-75ceb41329a3
		summarizeBy: none
		sourceColumn: Index Name Actuals

		annotation SummarizationSetBy = Automatic

	column 'Max Salaris End Actuals'
		dataType: double
		lineageTag: 93e9eb01-28aa-4f08-8e8b-4bfa65e7461f
		summarizeBy: sum
		sourceColumn: Max Salaris End Actuals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New Schaal ID (Trede Verhoging Actuals)'
		dataType: double
		lineageTag: 5b7f90bb-65cd-4bc8-bd27-aa532730c943
		summarizeBy: sum
		sourceColumn: New Schaal ID (Trede Verhoging Actuals)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MAX Trede Actuals'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 35cec671-ff4d-4942-bb4d-ef350b960428
		summarizeBy: none
		sourceColumn: MAX Trede Actuals

		annotation SummarizationSetBy = Automatic

	column 'SchaalType Forecasting'
		dataType: string
		lineageTag: 148ebacf-4d6b-4743-8efc-6bdc7af18381
		summarizeBy: none
		sourceColumn: SchaalType Forecasting

		annotation SummarizationSetBy = Automatic

	column 'Trede Verhoging (Forecasting)'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cbcf7064-612a-419d-89b6-e4869f3c16c0
		summarizeBy: none
		sourceColumn: Trede Verhoging (Forecasting)

		annotation SummarizationSetBy = Automatic

	column 'New Schaal ID (Forecasting)'
		dataType: int64
		formatString: 0
		lineageTag: ce1f3166-354b-450d-81d9-266de47ea018
		summarizeBy: none
		sourceColumn: New Schaal ID (Forecasting)

		annotation SummarizationSetBy = Automatic

	column 'Salaris New Forecasting'
		dataType: double
		lineageTag: 954d044b-8072-46f7-bd19-289a02f7d2cf
		summarizeBy: sum
		sourceColumn: Salaris New Forecasting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris Base Forecasting Original'
		dataType: double
		lineageTag: e7227cee-ee26-4e43-b375-b934eced54c2
		summarizeBy: sum
		sourceColumn: Salaris Base Forecasting Original

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris per Mnd'
		dataType: double
		lineageTag: a512bd6a-99f7-4e26-92ae-9aafa0f9fcae
		summarizeBy: sum
		sourceColumn: Salaris per Mnd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris Base Forecasting'
		dataType: double
		lineageTag: 113d46c2-2950-4a8f-81b1-a5e3f1da0102
		summarizeBy: sum
		sourceColumn: Salaris Base Forecasting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Softlanding per Maand'
		dataType: double
		lineageTag: 48600060-79e8-497e-8d12-b9afdce24b62
		summarizeBy: sum
		sourceColumn: Softlanding per Maand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC
		dataType: string
		lineageTag: 294f0e08-9348-44fb-8e78-f5d9a4b0af81
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 26039a9c-8cf4-4552-b242-770ad6a7770e
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: a999c2fd-ee22-48c2-a8e8-9e4b6a08f5eb
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: df286845-faf6-4962-9e28-f84b66ffbcbd
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column Rapportagecockpit_omschrijving
		dataType: string
		lineageTag: 8de5d5e4-ac64-4ac8-97d3-5f31765d8c3c
		summarizeBy: none
		sourceColumn: Rapportagecockpit_omschrijving

		annotation SummarizationSetBy = Automatic

	column 'FTE (Divided by 100)' = ```
			DIVIDE('Fact Forecasting Medewerkers Salaris'[FTE], 100, BLANK())
			
			```
		lineageTag: 66ece7f7-e15a-43b3-8f3d-998e58053720
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dienstjaren Medewerker Actuals' = RELATED('Dim Medewerker'[Dienstjaren])
		lineageTag: 4861f936-2aff-45d4-adb0-50242aa6e1a5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dienstjaren Medewerker Forecasting' = 'Fact Forecasting Medewerkers Salaris'[Dienstjaren Medewerker Actuals] + 1
		lineageTag: 163d8755-35a6-446a-8767-095a8e4482fe
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Naam_werkgever
		dataType: string
		lineageTag: ab7c5810-ee91-4784-8d77-aaf070527e3a
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column '(M) GB 4106000 - Bijzondere Vergoedingen' =
			
			VAR selectedGL = 'Fact Forecasting Medewerkers Salaris'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Medewerkers Salaris'[LC]
			VAR FTE = 'Fact Forecasting Medewerkers Salaris'[FTE (Divided by 100)]
			VAR MaandenInDienst = [Maanden in Dienst Actuals]
			VAR amount =
			CALCULATE(
			    DIVIDE(700, (12 * MaandenInDienst)) * FTE
			)
			RETURN
			SWITCH(
			    TRUE(),
			    selectedGL = "4106000", amount,
			    BLANK()
			)
		formatString: 0.00
		lineageTag: 6d39672d-0587-40f7-b119-e251fc3e5929
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'SchaalType Forecasting NEW' = RELATED('Dim SchaalType'[SchaalType Forecasting])
		lineageTag: 79ad6ff4-4b90-4f7e-bb91-cbc8b9e3e96c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '(M) LC 3075 - Overwerk 300%' = ```
			
			VAR selectedGL = 'Fact Forecasting Medewerkers Salaris'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Medewerkers Salaris'[LC]
			
			
			VAR total = DIVIDE([(WA) GB 4101000 Overwerk], 2)
			
			VAR countmedewerkers = 
			CALCULATE(
			    [Count Medewerkers],
			    ALL('Dim Medewerker'),
			    'Dim Medewerker'[Flag Overwerk 300%],
			    'Dim Medewerker'[Status_dienstverband] = "In dienst",
			    'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			)
			
			VAR basesetmedewerker = 
			FILTER(
			    'Dim Medewerker',
			    'Dim Medewerker'[Flag Overwerk 300%] = 1 &&
			    'Dim Medewerker'[Status_dienstverband] = "In dienst" &&
			    'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			)
			
			VAR kosten = 
			CALCULATE(
			    DIVIDE(total, countmedewerkers, BLANK()),
			    basesetmedewerker
			)
			
			RETURN
			IF(
			    selectedGL = "4101000" && selectedLC = "3075", 
			    DIVIDE(kosten, 12, BLANK()),
			    BLANK()
			)
			```
		lineageTag: 094dd0a5-d212-459c-a348-9aa7b6dd00c7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(M) LC 2622 - Overwerk 200%' = ```
			
			VAR selectedGL = 'Fact Forecasting Medewerkers Salaris'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Medewerkers Salaris'[LC]
			
			
			VAR total = DIVIDE([(WA) GB 4101000 Overwerk], 2)
			
			VAR countmedewerkers = 
			CALCULATE(
			    [Count Medewerkers],
			    ALL('Dim Medewerker'),
			    'Dim Medewerker'[Flag Overwerk 200%] = 1,
			    'Dim Medewerker'[Status_dienstverband] = "In dienst",
			    'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			)
			
			VAR basesetmedewerker = 
			FILTER(
			    'Dim Medewerker',
			    'Dim Medewerker'[Flag Overwerk 200%] = 1 &&
			    'Dim Medewerker'[Status_dienstverband] = "In dienst" && 
			    'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1
			)
			
			VAR kosten = 
			CALCULATE(
			    DIVIDE(total, countmedewerkers, BLANK()),
			    basesetmedewerker
			)
			
			VAR totalekosten = 
			SUMX(
			    basesetmedewerker,
			    kosten
			)
			
			RETURN
			
			IF(
			    selectedGL = "4101000" && selectedLC = "2622", 
			    DIVIDE(kosten, 12, BLANK()),
			    BLANK()
			)
			```
		lineageTag: ade996e1-b454-48f2-ad2c-1b7142878acb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(M) LC 3086 - Feesturen' = ```
			
			// 4101500
			
			VAR selectedGL = 'Fact Forecasting Medewerkers Salaris'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Medewerkers Salaris'[LC]
			
			VAR total = [(WA) GB 4101500 - Feesturen/dagen]
			
			VAR countmedewerkers = 
			CALCULATE(
			    [Count Medewerkers],
			    ALL('Dim Medewerker'),
			    'Dim Medewerker'[Feesturen flag] = 1,
			    'Dim Medewerker'[Status_dienstverband] = "In dienst"
			)
			
			VAR basesetmedewerker = 
			FILTER(
			    'Dim Medewerker',
			    'Dim Medewerker'[Feesturen flag] = 1 && 
			    'Dim Medewerker'[Status_dienstverband] = "In dienst"
			)
			
			VAR kosten = 
			CALCULATE(
			    DIVIDE(total, countmedewerkers, BLANK()),
			    basesetmedewerker
			)
			
			VAR totalekosten = 
			SUMX(
			    basesetmedewerker,
			    kosten
			)
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    selectedGL = "4101500" && selectedLC = "3086", DIVIDE(kosten, 12, BLANK()),
			    BLANK()
			)
			
			```
		lineageTag: ffcc7571-a7d5-47bb-ad20-d4c81f76f3be
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(M) LC 3078 - Begrafeniskosten' = ```
			
			// 4104000
			
			VAR selectedGL = 'Fact Forecasting Medewerkers Salaris'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Medewerkers Salaris'[LC]
			
			
			VAR countmedewerkers = 
			CALCULATE(
			    DISTINCTCOUNT('Fact Forecasting Medewerkers Salaris'[Medewerker ID]),
			    ALL('Dim Medewerker')
			)
			
			VAR averagekosten = DIVIDE([(WA) GB 4104000 - Onbelaste Vergoedingen], countmedewerkers, BLANK())
			
			VAR totalekosten = 
			SUMX(
			    VALUES('Fact Forecasting Medewerkers Salaris'[Medewerker ID]),
			    averagekosten
			)
			
			RETURN
			SWITCH(
			    TRUE(),
			    selectedGL = "4104000" || selectedLC = "3078", DIVIDE(totalekosten, 12, BLANK()),
			    BLANK()
			)
			```
		lineageTag: eb723b5d-23bf-4fb8-a6df-139a13ea9b65
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '(M) LC 2434 - Salaris' = ```
			
			VAR selectedGL = 'Fact Forecasting Medewerkers Salaris'[Grootboekrekening]
			VAR selectedLC = 'Fact Forecasting Medewerkers Salaris'[LC]
			
			RETURN
			IF(
			    selectedGL = "4100000" && selectedLC = "2434", 
			    'Fact Forecasting Medewerkers Salaris'[Salaris Base Forecasting],
			    BLANK()
			)
			```
		lineageTag: 3713dbd9-de86-48c9-b071-0bffb8e4aeb5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Forecasting Medewerkers Salaris' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Buffered Fact Forecasting Medewerkers",
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type number}, {"FTE", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([LC] = "2434"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

