table 'Fact Schemawerk'
	lineageTag: 96e53677-86ff-4597-aeee-abc89d272d1d

	column Year/Period
		dataType: string
		lineageTag: 96b4ba37-7e9a-41a9-a4da-b98177931263
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column Jaar
		dataType: double
		lineageTag: dacfdf17-02b3-4ba4-b275-8fa9ad4659a6
		summarizeBy: sum
		sourceColumn: Jaar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Salarissen'
		dataType: double
		lineageTag: 363d08f2-f45e-489d-8877-644ca79ef0e7
		summarizeBy: sum
		sourceColumn: Total Salarissen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC
		dataType: string
		lineageTag: b1524287-d306-425b-a07d-0feffd3578f8
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Bedrag Schemawerk'
		dataType: double
		lineageTag: 504d28f0-c598-4fc9-9f99-7023308fb0ce
		summarizeBy: sum
		sourceColumn: Bedrag Schemawerk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Percentage
		dataType: double
		lineageTag: 902d8426-08e2-4a36-9352-50b09ca72cba
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Schemawerk' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Table.Combine({#"GC_FinancialeMutaties (2021 - 1-3)", #"GC_FinancialeMutaties (2021 - 4)", #"GC_FinancialeMutaties (2021 - 5)", #"GC_FinancialeMutaties (2021 - 6)", #"GC_FinancialeMutaties (2021 - 7)", #"GC_FinancialeMutaties (2021 - 8)", #"GC_FinancialeMutaties (2021 - 9)", #"GC_FinancialeMutaties (2021 - 10)", #"GC_FinancialeMutaties (2021 - 11)", #"GC_FinancialeMutaties (2021 - >12)", #"GC_FinancialeMutaties (2022- 1-3)", #"GC_FinancialeMutaties (2022- 4-6)", #"GC_FinancialeMutaties (2022- 5)", #"GC_FinancialeMutaties (2022- 6)", #"GC_FinancialeMutaties (2022- 7)", #"GC_FinancialeMutaties (2022- 8)", #"GC_FinancialeMutaties (2022- 9)", #"GC_FinancialeMutaties (2022- 10)", #"GC_FinancialeMutaties (2022- 11)", #"GC_FinancialeMutaties (2022- >12)", #"GC_FinancialeMutaties (2023 - 1-3)", #"GC_FinancialeMutaties (2023 - 4)", #"GC_FinancialeMutaties (2023 - 5)", #"GC_FinancialeMutaties (2023 - 6)", #"GC_FinancialeMutaties (2023 - 7)", #"GC_FinancialeMutaties (2023 - 8)", #"GC_FinancialeMutaties (2023 - 9)", #"GC_FinancialeMutaties (2023 - 10)", #"GC_FinancialeMutaties (2023 - 11)", #"GC_FinancialeMutaties (2023 - >12)", #"GC_FinancialeMutaties (2024 - 1-3)", #"GC_FinancialeMutaties (2024 - 4)", #"GC_FinancialeMutaties (2024 - 5)", #"GC_FinancialeMutaties (2024 - 6)", #"GC_FinancialeMutaties (2024 - 7)", #"GC_FinancialeMutaties (2024 - 8)", #"GC_FinancialeMutaties (2024 - 9)", #"GC_FinancialeMutaties (2024 - 10)", #"GC_FinancialeMutaties (2024 - 11)", #"GC_FinancialeMutaties (2024 - >12)", #"GC_FinancialeMutaties (2025 - 1)", #"GC_FinancialeMutaties (2025 - 2)", #"GC_FinancialeMutaties (2025 - 3)", #"GC_FinancialeMutaties (2025 - 4)", #"GC_FinancialeMutaties (2025 - 5)", #"GC_FinancialeMutaties (2025 - 6)", #"GC_FinancialeMutaties (2025 - 7)", #"GC_FinancialeMutaties (2025 - 8)", #"GC_FinancialeMutaties (2025 - 9)", #"GC_FinancialeMutaties (2025 - 11)", #"GC_FinancialeMutaties (2025 - >12)", #"GC_FinancialeMutaties (2025 - 10)"}),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Boekstukdatum", type datetime}, {"Datum_boeking", type datetime}, {"Datum_toegevoegd", type datetime}, {"Datum_gewijzigd", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Boekstukdatum", type date}, {"Datum_boeking", type date}, {"Datum_toegevoegd", type date}, {"Datum_gewijzigd", type date}, {"Bedrag_debet", type number}, {"Bedrag_credit", type number}, {"Saldo", type number}, {"Valutabedrag_debet", type number}, {"Valutabedrag_credit", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Period (leading zeros)", each Text.PadStart(Text.From([Periode]),2,"0")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Year/Period", each Text.From([Jaar]) & "/" & Text.From([#"Period (leading zeros)"])),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Bedrag in LC", each [Saldo]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Bedrag in LC", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type2",{"Beheerder", "Type_rekening", "Administratie", "Naam_administratie", "Jaar", "Periode", "Boekstukdatum", "Datum_boeking", "Nummer_journaalpost", "Volgnummer_journaalpost", "Rapportagecockpit_omschrijving", "Verzamelen_op", "Rekeningnummer_2", "Omschrijving", "Boekstuknummer", "Factuurnummer", "Omschrijving_2", "Omschrijving_boeking", "Bedrag_debet", "Bedrag_credit", "Saldo", "Valuta", "Valutabedrag_debet", "Valutabedrag_credit", "Code_dagboek", "Omschrijving_3", "Code_verbijzonderingsas_1", "Omschrijving_4", "Code_verbijzonderingsas_2", "Transitorische_post", "Admin._rek.-courantboeking", "Datum_toegevoegd", "Toegevoegd_door", "Datum_gewijzigd", "Gewijzigd_door", "Type_rekening_2", "Rapportagecockpit", "Period (leading zeros)", "Year/Period", "Bedrag in LC"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each [Rekeningnummer_2] = "4100000"),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"Year/Period", "Rekeningnummer_2", "Jaar"}, {{"Total", each List.Sum([Bedrag in LC]), type nullable number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Total", "Total Salarissen"}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns",{"Year/Period", "Jaar", "Total Salarissen"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Other Columns1",{{"Jaar", type number}, {"Year/Period", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type3", {"Jaar", "Year/Period"}, #"Fact Schemawerk Support", {"Jaar", "Boeking Year/Period"}, "Fact Schemawerk Support", JoinKind.LeftOuter),
				    #"Expanded Fact Schemawerk Support" = Table.ExpandTableColumn(#"Merged Queries", "Fact Schemawerk Support", {"LC", "Bedrag Schemawerk"}, {"LC", "Bedrag Schemawerk"}),
				    #"Added Custom3" = Table.AddColumn(#"Expanded Fact Schemawerk Support", "Percentage", each [Bedrag Schemawerk] / [Total Salarissen], type nullable number)
				in
				    #"Added Custom3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

