table 'Fact Forecasting Vacatures'
	lineageTag: 114278a5-cda5-4b3a-90a9-11a9655cd651

	column Geblokkeerd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 76771010-4e4e-4f52-8667-8466dad9a65c
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: 59175e64-4d1b-47c6-8c67-d50ef08c6293
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: 9de37e6a-6d75-45eb-941b-1fabcb2623d2
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: d850aa91-db98-4b4d-8e91-d50cc2690be8
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column Declarerend_Niet-declarerend
		dataType: string
		lineageTag: a0fe73da-affe-4dc9-b78d-730b1fb2021f
		summarizeBy: none
		sourceColumn: Declarerend_Niet-declarerend

		annotation SummarizationSetBy = Automatic

	column Service_Line_Type
		dataType: string
		lineageTag: 91d634f5-5288-46be-bbb1-0a828e062f27
		summarizeBy: none
		sourceColumn: Service_Line_Type

		annotation SummarizationSetBy = Automatic

	column Service_Lines
		dataType: string
		lineageTag: 8d1cfba9-1c4b-4eb8-909f-6655c41733ed
		summarizeBy: none
		sourceColumn: Service_Lines

		annotation SummarizationSetBy = Automatic

	column Cluster_Afdeling
		dataType: string
		lineageTag: dccb2840-0e64-44dc-8786-de93ea6ba169
		summarizeBy: none
		sourceColumn: Cluster_Afdeling

		annotation SummarizationSetBy = Automatic

	column Formatieplaats
		dataType: string
		lineageTag: 6eb454c5-4054-4464-867d-cf02d80a2137
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		lineageTag: bac9796f-84d8-4bcf-b597-b5dfd3800cad
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 4c954f83-0c8f-49d7-b11c-2da6ea9f82a2
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column OE
		dataType: string
		lineageTag: 61b32662-ff5a-49e9-9769-e874c9ffbbcb
		summarizeBy: none
		sourceColumn: OE

		annotation SummarizationSetBy = Automatic

	column Omschrijving_2
		dataType: string
		lineageTag: a39c1d9a-8fe1-4189-8d58-7816c77a2446
		summarizeBy: none
		sourceColumn: Omschrijving_2

		annotation SummarizationSetBy = Automatic

	column Functie
		dataType: string
		lineageTag: 9ad68a34-6934-41e6-aa82-846096106118
		summarizeBy: none
		sourceColumn: Functie

		annotation SummarizationSetBy = Automatic

	column Omschrijving_3
		dataType: string
		lineageTag: 57c0034d-24b9-4453-a509-b9403c5e88d8
		summarizeBy: none
		sourceColumn: Omschrijving_3

		annotation SummarizationSetBy = Automatic

	column Generieke_functienaam
		dataType: string
		lineageTag: 2b77c7a1-bf81-46c0-aa5b-8bc9f0f1e197
		summarizeBy: none
		sourceColumn: Generieke_functienaam

		annotation SummarizationSetBy = Automatic

	column FTE_Begroot
		dataType: double
		lineageTag: 12409285-d7ca-4416-8f8a-636268fdb249
		summarizeBy: sum
		sourceColumn: FTE_Begroot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Werkelijk
		dataType: double
		lineageTag: 442c1a20-e68a-4f3a-81dd-e77cbb574428
		summarizeBy: sum
		sourceColumn: Werkelijk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Instroom
		dataType: double
		lineageTag: f7790bc6-8572-42d6-a945-09c1a526059f
		summarizeBy: sum
		sourceColumn: Instroom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FTE uitstroom (zonder bepaalde tijd)'
		dataType: double
		lineageTag: 2081f823-c7e1-4c42-830f-193e6997388d
		summarizeBy: sum
		sourceColumn: FTE uitstroom (zonder bepaalde tijd)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Verschil
		dataType: double
		lineageTag: 235d3332-b588-4a76-b758-8da145ab291a
		summarizeBy: sum
		sourceColumn: Verschil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Verschil (excl)'
		dataType: double
		lineageTag: 06dbf6df-b7f0-4f7c-8b1a-a500e7cc548a
		summarizeBy: sum
		sourceColumn: Verschil (excl)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gebruiker
		dataType: string
		lineageTag: be896c72-ad7c-493a-98cc-7d6789f872c3
		summarizeBy: none
		sourceColumn: Gebruiker

		annotation SummarizationSetBy = Automatic

	column Type_functie
		dataType: string
		lineageTag: 11d8e508-6bd4-4468-b648-a161310754ce
		summarizeBy: none
		sourceColumn: Type_functie

		annotation SummarizationSetBy = Automatic

	column 'Datum Gewijzigd'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8f3d855-2c39-4b17-bd6e-70d0ea1bd966
		summarizeBy: none
		sourceColumn: Datum Gewijzigd

		variation Variation
			isDefault
			relationship: c0bc57d4-0f7c-4d72-aa4f-b66e69583786
			defaultHierarchy: LocalDateTable_2d48c39c-d009-4314-8331-6a126025f12a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tijd Gewijzigd'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4801987c-2d6e-41c2-8ff1-8b00465a3ba6
		summarizeBy: none
		sourceColumn: Tijd Gewijzigd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Uren_Begroot
		dataType: double
		lineageTag: 9d72e6b9-cc01-4064-9067-775e16e832c6
		summarizeBy: sum
		sourceColumn: Uren_Begroot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uren_Werkelijk
		dataType: double
		lineageTag: 6608ff9b-17be-4ae4-a349-33c71dad22b1
		summarizeBy: sum
		sourceColumn: Uren_Werkelijk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uren_Verschil
		dataType: double
		lineageTag: 6900d0f4-b2ad-44c6-bacb-a90649071847
		summarizeBy: sum
		sourceColumn: Uren_Verschil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Medewerker ID'
		dataType: int64
		formatString: 0
		lineageTag: 9a6836cb-4160-40d2-a2d3-e327711187e6
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Periode
		dataType: string
		lineageTag: 6585effc-4d03-4b3e-ad81-ea48139403b7
		summarizeBy: none
		sourceColumn: Periode

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 0c59f5ab-9955-48d2-964f-7efeda1434c5
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: string
		lineageTag: 4d270d45-3c07-47dc-bfb7-a2674003cd97
		summarizeBy: none
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Schaal/Trede
		dataType: string
		lineageTag: 6e23ae47-2278-4ff6-bdd3-0794b04c1d76
		summarizeBy: none
		sourceColumn: Schaal/Trede

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: 06a4d1c0-7bcf-4e5b-9c11-e8ff9ec73223
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: 82bea722-0ac7-419f-bec0-e6d1ab653790
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column 'Schaal/Trede Salaris'
		dataType: string
		lineageTag: 35ea5606-a70f-4161-badf-11959d30d59f
		summarizeBy: none
		sourceColumn: Schaal/Trede Salaris

		annotation SummarizationSetBy = Automatic

	column '2434 - Salaris'
		dataType: string
		lineageTag: 50ff9afa-2962-40d9-a90f-40068b3c361d
		summarizeBy: none
		sourceColumn: 2434 - Salaris

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 094613f2-7f58-44b7-885a-7a5f91507069
		summarizeBy: none
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	partition 'Fact Forecasting Vacatures' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Json.Document(Web.Contents("https://86331.rest.afas.online/ProfitRestServices/connectors/CMC_Formatieplaats" & "?skip=-1&take=-1", [Headers=[Authorization="AfasToken PHRva2VuPjx2ZXJzaW9uPjE8L3ZlcnNpb24+PGRhdGE+Qjk5N0I1MjNGMzhENDgwNjgyRTA0NzQ4RkZCQUQ1RjU5MTA1OEU3QUEwQTQ0MDMxODlBNUVGNTNEMjFDREQ5MTwvZGF0YT48L3Rva2VuPg=="]])),
				    rows = Source[rows],
				    #"Converted to Table" = Table.FromList(rows, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}, {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"Geblokkeerd", type logical}, {"Naam_werkgever", type text}, {"Patientgebonden_functies", type text}, {"Soort_functie", type text}, {"Declarerend_Niet-declarerend", type text}, {"Service_Lines", type text}, {"Cluster_Afdeling", type text}, {"Omschrijving", type text}, {"Formatieplaats", type text}, {"Kostenplaats", Int64.Type}, {"Organisatorische_eenheid", type text}, {"Omschrijving_2", type text}, {"Functie", type text}, {"Omschrijving_3", type text}, {"Generieke_functienaam", type text}, {"Gebruiker", type text}, {"Type_functie", type text}, {"Naam", type text}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([Einddatum], "T"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Text Before Delimiter", "Eind Datum"}}),
				    #"Inserted Text Before Delimiter1" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Begindatum], "T"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Before Delimiter1",{{"Text Before Delimiter", "Begin Datum"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Begin Datum", type date}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum"}),
				    #"Inserted Text Before Delimiter2" = Table.AddColumn(#"Reordered Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Gewijzigd], "T"), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Text Before Delimiter2",{{"Text Before Delimiter", "Datum Gewijzigd"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Datum Gewijzigd", type date}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Changed Type3", "Text After Delimiter", each Text.AfterDelimiter([Gewijzigd], "T"), type text),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Inserted Text After Delimiter", {{"Text After Delimiter", each Text.BeforeDelimiter(_, "Z"), type text}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Extracted Text Before Delimiter",{{"Text After Delimiter", "Tijd Gewijzigd"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Tijd Gewijzigd", type time}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type4",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum", "Datum Gewijzigd", "Tijd Gewijzigd"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Aantal_FTE_2", type number}, {"Aantal_FTE", type number}, {"Aantal_FTE_3", type number}, {"Aantal_FTE_4", type number}, {"Verschil", type number}, {"FTE_Begroot", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type5", "Uren_Begroot", each [FTE_Begroot] * 8),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Uren_Werkelijk", each [Aantal_FTE] * 8),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Uren_Verschil", each [Verschil] * 8),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom2",{{"Uren_Begroot", type number}, {"Uren_Werkelijk", type number}, {"Uren_Verschil", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type6", each ([Naam_werkgever] = "Curacao Medical Center Exploitatie")),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Filtered Rows",{{"Kostenplaats", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type7", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns7" = Table.RenameColumns(#"Added Index",{{"Index", "Medewerker ID"}}),
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns7", "Year", each Date.Year([Begin Datum]), Int64.Type),
				    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Year",{{"Aantal_FTE", "Werkelijk"}, {"Aantal_FTE_2", "Instroom"}, {"Aantal_FTE_3", "FTE uitstroom (zonder bepaalde tijd)"}, {"Verschil", "Verschil (excl)"}, {"Aantal_FTE_4", "Verschil"}, {"Organisatorische_eenheid", "OE"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns4", each [#"Verschil (excl)"] > 0),
				    #"Invoked Custom Function" = Table.AddColumn(#"Filtered Rows1", "Year Forecasting", each #"Forecasting Vacature Date Function"([Year])),
				    #"Expanded Year Forecasting" = Table.ExpandTableColumn(#"Invoked Custom Function", "Year Forecasting", {"Year"}, {"Year.1"}),
				    #"Renamed Columns9" = Table.RenameColumns(#"Expanded Year Forecasting",{{"Year.1", "Year Forecasting"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns9", {"Year Forecasting"}, #"Dim Calendar", {"Year"}, "Dim Calendar", JoinKind.LeftOuter),
				    #"Expanded Dim Calendar" = Table.ExpandTableColumn(#"Merged Queries", "Dim Calendar", {"Month no. (leading zeros)"}, {"Month no. (leading zeros)"}),
				    #"Renamed Columns8" = Table.RenameColumns(#"Expanded Dim Calendar",{{"Month no. (leading zeros)", "Periode"}}),
				    #"Added Custom3" = Table.AddColumn(#"Renamed Columns8", "Year/Period", each Text.From([Year Forecasting]) & "/" & Text.From([#"Periode"])),
				    #"Merged Queries1" = Table.NestedJoin(#"Added Custom3", {"Formatieplaats", "Patientgebonden_functies"}, #"Dim Schaal per Formatieplaats CAO", {"Formatieplaats Code", "Patientgebonden_functies"}, "Dim Schaal per Formatieplaats CAO", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats CAO" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Schaal per Formatieplaats CAO", {"Max Schaal/Trede"}, {"Max Schaal/Trede"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Expanded Dim Schaal per Formatieplaats CAO",{{"Max Schaal/Trede", "Max Schaal/Trede CAO"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns5",{{"Max Schaal/Trede CAO", Text.Trim, type text}}),
				    #"Merged Queries2" = Table.NestedJoin(#"Trimmed Text", {"Max Schaal/Trede CAO"}, #"CAO Schaal", {"Max Trede Flag"}, "CAO Schaal", JoinKind.LeftOuter),
				    #"Expanded CAO Schaal" = Table.ExpandTableColumn(#"Merged Queries2", "CAO Schaal", {"Salaris"}, {"Salaris"}),
				    #"Renamed Columns6" = Table.RenameColumns(#"Expanded CAO Schaal",{{"Salaris", "MAX Salaris CAO"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns6", {"Formatieplaats", "Periode"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Removed Duplicates", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats LNT", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats LNT", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats LNT" = Table.ExpandTableColumn(#"Merged Queries3", "Dim Schaal per Formatieplaats LNT", {"Schaal/Trede LNT 386K Vacature Forecasting", "LNT 386K Schaal Vac Forecast Salaris"}, {"Schaal/Trede LNT 386K Vacature Forecasting", "LNT 386K Schaal Vac Forecast Salaris"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Expanded Dim Schaal per Formatieplaats LNT", {"Formatieplaats"}, #"Dim Schaal per Formatieplaats BMP", {"Formatieplaats Code"}, "Dim Schaal per Formatieplaats BMP", JoinKind.LeftOuter),
				    #"Expanded Dim Schaal per Formatieplaats BMP" = Table.ExpandTableColumn(#"Merged Queries4", "Dim Schaal per Formatieplaats BMP", {"Schaal/Trede LNT 386K Vac Forecasting", "Salari LNT 386K Forecast Vac"}, {"BMP.Schaal/Trede LNT 386K Vac Forecasting", "BMP.Salari LNT 386K Forecast Vac"}),
				    #"Added Custom4" = Table.AddColumn(#"Expanded Dim Schaal per Formatieplaats BMP", "BMP Schaal/Trede LNT 386K", each if[#"BMP.Schaal/Trede LNT 386K Vac Forecasting"] = [#"Schaal/Trede LNT 386K Vacature Forecasting"] then null else [#"BMP.Schaal/Trede LNT 386K Vac Forecasting"]),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "BMP Salaris LNT 386K", each if [BMP.Salari LNT 386K Forecast Vac] = [LNT 386K Schaal Vac Forecast Salaris] then null else [BMP.Salari LNT 386K Forecast Vac]),
				    #"Merged Columns" = Table.CombineColumns(#"Added Custom5",{"BMP Schaal/Trede LNT 386K", "Schaal/Trede LNT 386K Vacature Forecasting", "Max Schaal/Trede CAO"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Schaal/Trede"),
				    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Merged Columns", {{"MAX Salaris CAO", type text}, {"LNT 386K Schaal Vac Forecast Salaris", type text}, {"BMP Salaris LNT 386K", type text}}, "en-US"),{"MAX Salaris CAO", "LNT 386K Schaal Vac Forecast Salaris", "BMP Salaris LNT 386K"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Bruto Salaris"),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Merged Columns1",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Werkelijk", "Instroom", "FTE uitstroom (zonder bepaalde tijd)", "Verschil", "Verschil (excl)", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum", "Datum Gewijzigd", "Tijd Gewijzigd", "Uren_Begroot", "Uren_Werkelijk", "Uren_Verschil", "Medewerker ID", "Year", "Year Forecasting", "Periode", "Year/Period", "Schaal/Trede", "Bruto Salaris"}),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Removed Other Columns1",{{"Bruto Salaris", type number}}),
				    #"Merged Queries5" = Table.NestedJoin(#"Changed Type8", {"Formatieplaats"}, #"Fact Formatieplaats per LC Per GB", {"Formatieplaats Code"}, "Fact Formatieplaats per LC Per GB", JoinKind.LeftOuter),
				    #"Expanded Fact Formatieplaats per LC Per GB" = Table.ExpandTableColumn(#"Merged Queries5", "Fact Formatieplaats per LC Per GB", {"LC", "Grootboekrekening"}, {"LC", "Grootboekrekening"}),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Expanded Fact Formatieplaats per LC Per GB",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "OE", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Werkelijk", "Instroom", "FTE uitstroom (zonder bepaalde tijd)", "Verschil", "Verschil (excl)", "Gebruiker", "Type_functie", "Datum Gewijzigd", "Tijd Gewijzigd", "Uren_Begroot", "Uren_Werkelijk", "Uren_Verschil", "Medewerker ID", "Year Forecasting", "Periode", "Year/Period", "Schaal/Trede", "LC", "Grootboekrekening"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Removed Other Columns2", {"Schaal/Trede"}, #"Dim SchaalType", {"Schaal/Trede"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries6", "Dim SchaalType", {"Salaris", "Schaal ID"}, {"Salaris", "Schaal ID"}),
				    #"Renamed Columns10" = Table.RenameColumns(#"Expanded Dim SchaalType",{{"Salaris", "Schaal/Trede Salaris"}}),
				    #"Added LC 2434 Salaris" = Table.AddColumn(#"Renamed Columns10", "2434 - Salaris", each if [LC] = "2434" then [#"Schaal/Trede Salaris"] else null)
				in
				    #"Added LC 2434 Salaris"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

