table 'Fact Forecasting Medewerkers Other LC'
	lineageTag: 4f61c073-ab65-49e2-b034-ed1249faf2cc

	column 'Medewerker ID'
		dataType: string
		lineageTag: 2689172f-fd69-4c66-a089-d105518e46b4
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: 4bf5091c-b514-4454-a94a-d4d3a0906f30
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 99b9eafc-143d-40c9-b360-450a577dd198
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: d79c2bc5-d051-463e-88ee-29e038ed138d
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: aebc5c4c-ce18-452b-8237-9ca71bf6ac9c
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: f2e23dbb-a8b1-4c15-bad6-4a91a82b061a
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rapportagecockpit_omschrijving
		dataType: string
		lineageTag: 9677eab8-8b62-4a4e-8e05-74244904da62
		summarizeBy: none
		sourceColumn: Rapportagecockpit_omschrijving

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: int64
		formatString: 0
		lineageTag: a990cca0-7016-4b4e-a6a2-61b67491d82e
		summarizeBy: sum
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: double
		lineageTag: 6058ee5b-0399-43fb-9556-60414a438f65
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: 302690f6-5cc1-4f9e-9025-c5ce4332d863
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: afc6bcfa-ee0d-4509-823f-35aec66be2c4
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: acbfcfd0-f7d0-492e-853d-c1e3251f7524
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: d0e72a39-af25-423c-a43d-0756e4f7d096
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: 2775298a-e7f9-481d-80f7-908556fd5b49
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Period (leading zeros)'
		dataType: string
		lineageTag: 6c35b0c0-e394-44bb-9c45-8cf816ad08a1
		summarizeBy: none
		sourceColumn: Period (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: aca19110-878a-4638-a066-45b10a914529
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Index Name Actuals'
		dataType: string
		lineageTag: 28c1a874-9764-4b78-83b4-191e0f014533
		summarizeBy: none
		sourceColumn: Index Name Actuals

		annotation SummarizationSetBy = Automatic

	column 'SchaalType Forecasting'
		dataType: string
		lineageTag: 401b4248-2393-4499-9498-79131bfc14f3
		summarizeBy: none
		sourceColumn: SchaalType Forecasting

		annotation SummarizationSetBy = Automatic

	column 'Trede Verhoging (Forecasting)'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d6058998-bee2-4d09-99ea-57a264abac1c
		summarizeBy: none
		sourceColumn: Trede Verhoging (Forecasting)

		annotation SummarizationSetBy = Automatic

	column 'New Schaal ID (Forecasting)'
		dataType: int64
		formatString: 0
		lineageTag: 3443e772-566b-4ae1-ba4a-f5395ed7bd20
		summarizeBy: none
		sourceColumn: New Schaal ID (Forecasting)

		annotation SummarizationSetBy = Automatic

	partition 'Fact Forecasting Medewerkers Other LC' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Buffered Fact Forecasting Medewerkers",
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type number}, {"FTE", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [LC] <> "2434" and [LC] <> "3164"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Medewerker ID", "LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving", "FTE", "Rapportagecockpit_omschrijving", "Year Forecasting", "Period", "Anniversary Month", "Kostenplaats", "Naam_werkgever", "Schaal ID", "Type Personeel ID", "Period (leading zeros)", "Year/Period", "Index Name Actuals", "SchaalType Forecasting", "Trede Verhoging (Forecasting)", "New Schaal ID (Forecasting)"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

