table 'Fact Actuals FTE'
	lineageTag: 3657a3f8-3326-4d2b-b375-d6d974a98225

	column Jaar
		dataType: int64
		formatString: 0
		lineageTag: eb6fad41-4b1a-4455-8860-9202facf090e
		summarizeBy: sum
		sourceColumn: Jaar

		annotation SummarizationSetBy = Automatic

	column Boekingsperiode
		dataType: int64
		formatString: 0
		lineageTag: c23430fc-f5eb-4160-b2da-b18285a59b09
		summarizeBy: sum
		sourceColumn: Boekingsperiode

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: fb4dc941-6f35-4f9f-b6a1-ef643d8eb88a
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column Kostenplaats_omschrijving
		dataType: string
		lineageTag: 4261102d-619b-42c6-808d-d08760138ca6
		summarizeBy: none
		sourceColumn: Kostenplaats_omschrijving

		annotation SummarizationSetBy = Automatic

	column 'Boeking Periode (leading zeros)'
		dataType: string
		lineageTag: ae576dac-8122-49e9-b563-06e8f7c940a7
		summarizeBy: none
		sourceColumn: Boeking Periode (leading zeros)

		annotation SummarizationSetBy = Automatic

	column 'Boeking Year/Period'
		dataType: string
		lineageTag: 9b3e8102-9798-4d43-91fb-97a8e974d225
		summarizeBy: none
		sourceColumn: Boeking Year/Period

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: 472c2583-f2ee-4f09-b4ee-bee5ff27a9e1
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Schaal ID'
		dataType: double
		formatString: 0
		lineageTag: 8bb597fd-8aa5-4cf2-a303-e81fd070545e
		summarizeBy: none
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Medewerker ID'
		dataType: string
		lineageTag: 3a30444b-3e40-41fa-a41a-49e3f9a5179a
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	partition 'Fact Actuals FTE' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = #"Fact Personeels Kosten",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Jaar", "Boekingsperiode", "Medewerker ID", "Kostenplaats", "Kostenplaats_omschrijving", "Boeking Periode (leading zeros)", "Boeking Year/Period", "FTE", "Schaal ID"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Medewerker ID", "Boeking Year/Period"})
				in 
				    #"Removed Duplicates"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

