table 'Fact Forcasting Schemawerk'
	lineageTag: 5ec6a05a-3be9-4f28-a2b8-cc3192b094b8

	column 'Year/Period Original'
		dataType: string
		lineageTag: b774d407-76fe-4f44-91e0-8a17145d2d9b
		summarizeBy: none
		sourceColumn: Year/Period Original

		annotation SummarizationSetBy = Automatic

	column Jaar
		dataType: double
		lineageTag: 2fa88387-3fa3-42c3-b35e-afc4fd0d58f3
		summarizeBy: sum
		sourceColumn: Jaar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Periode
		dataType: double
		lineageTag: 783b48e1-d6c9-4827-85c4-85e167a4594b
		summarizeBy: sum
		sourceColumn: Periode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Salarissen'
		dataType: double
		lineageTag: a33925f1-74b1-49fa-a46e-540ea8a173af
		summarizeBy: sum
		sourceColumn: Total Salarissen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsExtrapolated
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ccab7d49-8d5c-4bb3-9d33-3d669ec3fb88
		summarizeBy: none
		sourceColumn: IsExtrapolated

		annotation SummarizationSetBy = Automatic

	column 'Period (leading zeros)'
		dataType: string
		lineageTag: 003ada09-2272-4084-af1b-c2151c1662b2
		summarizeBy: none
		sourceColumn: Period (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 377742dd-f6f3-403f-aea8-f9bfc8174fd1
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: fc79c0e9-9769-4766-a7cf-e49e017d12af
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Bedrag Schemawerk'
		dataType: double
		lineageTag: 40961a4e-fb73-4687-a761-d618c8ae9115
		summarizeBy: sum
		sourceColumn: Bedrag Schemawerk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Grootboekrekeing = RELATED('Dim LC per GL'[Grootboekrekening])
		lineageTag: b910b707-a479-4167-8f3d-4968a86341f6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Percentage = DIVIDE('Fact Forcasting Schemawerk'[Bedrag Schemawerk], 'Fact Forcasting Schemawerk'[Total Salarissen], BLANK())
		lineageTag: 1437e99d-8dc7-4616-97c6-488b9a576fb7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Percentage corrected' = ```
			
			VAR curYear  = 'Fact Forcasting Schemawerk'[Jaar]
			VAR curMonth = 'Fact Forcasting Schemawerk'[Periode]
			VAR curLC = 'Fact Forcasting Schemawerk'[LC]
			VAR prevPct =
			    CALCULATE(
			        MAX('Fact Forcasting Schemawerk'[Percentage]),          
			        FILTER(
			            ALL('Fact Forcasting Schemawerk'),
			            'Fact Forcasting Schemawerk'[Jaar] = curYear - 1
			            && 'Fact Forcasting Schemawerk'[Periode] = curMonth 
			            && 'Fact Forcasting Schemawerk'[LC] = curLC
			        )
			    )
			RETURN IF('Fact Forcasting Schemawerk'[IsExtrapolated], prevPct, 'Fact Forcasting Schemawerk'[Percentage])
			
			```
		lineageTag: 51d67e6f-8fd5-46fd-86f5-af1e37d981aa
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Forcasting Schemawerk' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Buffered Fact Forcasting Schemawerk",
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Year/Period", "Year/Period Original"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Period (leading zeros)", each Text.PadStart(Text.From([Periode]),2,"0"), type nullable text),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom", "Year/Period", each Text.From([Jaar]) & "/" & Text.From([#"Period (leading zeros)"]), type nullable text),
				
				    FactSchemawerk = Table.Buffer(#"Fact Schemawerk Support Source"),
				
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom2", {"Jaar", "Year/Period"}, FactSchemawerk, {"Jaar", "Year/Period"}, "Fact Schemawerk Support Source", JoinKind.LeftOuter),
				    #"Expanded Fact Schemawerk Support Source" = Table.ExpandTableColumn(#"Merged Queries", "Fact Schemawerk Support Source", {"LC", "Bedrag Schemawerk"}, {"LC", "Bedrag Schemawerk"})
				in
				    #"Expanded Fact Schemawerk Support Source"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

