table 'Fact FormatiePlaats'
	lineageTag: ec9687a2-fef3-4536-a4e3-c6ba243a62dc

	column Geblokkeerd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3a5fe360-50ee-4d29-bfa0-17fb0441bc86
		summarizeBy: none
		sourceColumn: Geblokkeerd

		annotation SummarizationSetBy = Automatic

	column Naam_werkgever
		dataType: string
		lineageTag: 69de70e5-2b6a-44a6-a5ea-6fa04cd197c4
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column Patientgebonden_functies
		dataType: string
		lineageTag: f4fbadcf-8733-4a82-ba93-21c9bdf73ea4
		summarizeBy: none
		sourceColumn: Patientgebonden_functies

		annotation SummarizationSetBy = Automatic

	column Soort_functie
		dataType: string
		lineageTag: 22a53dee-5796-4260-81fa-5cd104b4fd13
		summarizeBy: none
		sourceColumn: Soort_functie

		annotation SummarizationSetBy = Automatic

	column Declarerend_Niet-declarerend
		dataType: string
		lineageTag: 3c0d0ad5-5dbc-4e6c-a062-91a42e118b06
		summarizeBy: none
		sourceColumn: Declarerend_Niet-declarerend

		annotation SummarizationSetBy = Automatic

	column Service_Line_Type
		dataType: string
		lineageTag: 10a5d7e0-0220-4738-afd2-d7cda9b3b2f6
		summarizeBy: none
		sourceColumn: Service_Line_Type

		annotation SummarizationSetBy = Automatic

	column Service_Lines
		dataType: string
		lineageTag: 6954e0a4-4031-4b03-9378-7f0f8004a2b2
		summarizeBy: none
		sourceColumn: Service_Lines

		annotation SummarizationSetBy = Automatic

	column Cluster_Afdeling
		dataType: string
		lineageTag: 40687402-70ca-4254-8a53-6865ede52f33
		summarizeBy: none
		sourceColumn: Cluster_Afdeling

		annotation SummarizationSetBy = Automatic

	column Formatieplaats
		dataType: string
		lineageTag: efc1b955-3a31-4415-be5d-dc0581682901
		summarizeBy: none
		sourceColumn: Formatieplaats

		annotation SummarizationSetBy = Automatic

	column Omschrijving
		dataType: string
		lineageTag: 82fd86b6-724d-49d6-9602-4e25ecb2075f
		summarizeBy: none
		sourceColumn: Omschrijving

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 237f0f19-c730-4813-a279-98d3dfbfe599
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column OE
		dataType: string
		lineageTag: 4007df20-cef1-4e2c-a447-dc82820c2794
		summarizeBy: none
		sourceColumn: OE

		annotation SummarizationSetBy = Automatic

	column Omschrijving_2
		dataType: string
		lineageTag: 7f85b32e-7c0a-4dd9-936f-df9f985d08eb
		summarizeBy: none
		sourceColumn: Omschrijving_2

		annotation SummarizationSetBy = Automatic

	column Functie
		dataType: string
		lineageTag: 25b13fed-b722-4025-8a14-c17ffb5a3060
		summarizeBy: none
		sourceColumn: Functie

		annotation SummarizationSetBy = Automatic

	column Omschrijving_3
		dataType: string
		lineageTag: 7ef837cf-b277-4435-a458-f873f5c969b6
		summarizeBy: none
		sourceColumn: Omschrijving_3

		annotation SummarizationSetBy = Automatic

	column Generieke_functienaam
		dataType: string
		lineageTag: 37b97c35-b333-45ef-99e7-71772673d72c
		summarizeBy: none
		sourceColumn: Generieke_functienaam

		annotation SummarizationSetBy = Automatic

	column FTE_Begroot
		dataType: double
		lineageTag: df038465-0a6f-4600-8494-c05f199fe000
		summarizeBy: sum
		sourceColumn: FTE_Begroot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Werkelijk
		dataType: double
		lineageTag: 92062f35-544b-4caa-aaeb-0e442e0a4b0b
		summarizeBy: sum
		sourceColumn: Werkelijk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Instroom
		dataType: double
		lineageTag: 39ffe8ae-cd37-4f6c-b333-03f61e9f7600
		summarizeBy: sum
		sourceColumn: Instroom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FTE uitstroom (zonder bepaalde tijd)'
		dataType: double
		lineageTag: 7b3eb3ec-8d68-4c1c-84ee-f257422e0d04
		summarizeBy: sum
		sourceColumn: FTE uitstroom (zonder bepaalde tijd)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Verschil
		dataType: double
		lineageTag: 8ccc01c3-ce40-4e56-8ea5-7f88ce4f6e64
		summarizeBy: sum
		sourceColumn: Verschil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Verschil (excl)'
		dataType: double
		lineageTag: d96089f2-594b-4bea-8b34-f5318c8a2e79
		summarizeBy: sum
		sourceColumn: Verschil (excl)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gebruiker
		dataType: string
		lineageTag: a717204c-529d-4f23-b97b-fcdf870dbddb
		summarizeBy: none
		sourceColumn: Gebruiker

		annotation SummarizationSetBy = Automatic

	column Type_functie
		dataType: string
		lineageTag: ca2518b5-bd82-4516-be3e-b7773d98ff4d
		summarizeBy: none
		sourceColumn: Type_functie

		annotation SummarizationSetBy = Automatic

	column Naam
		dataType: string
		lineageTag: a77b5e32-2af0-4026-8d88-5974bdf94b83
		summarizeBy: none
		sourceColumn: Naam

		annotation SummarizationSetBy = Automatic

	column 'Begin Datum'
		dataType: dateTime
		formatString: Long Date
		lineageTag: de090bd5-820f-4716-9341-f9e246e21939
		summarizeBy: none
		sourceColumn: Begin Datum

		variation Variation
			isDefault
			relationship: 369bf740-7b40-487e-9c1e-de77d96ae3b4
			defaultHierarchy: LocalDateTable_ff0b6a01-a3a6-42f7-906d-39e53520f9c0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Eind Datum'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9124199f-439b-4192-b57d-d8d1956e6df8
		summarizeBy: none
		sourceColumn: Eind Datum

		variation Variation
			isDefault
			relationship: 66a7ea94-9b8e-4d77-86a9-70c6f3c4ac7a
			defaultHierarchy: LocalDateTable_446649bc-0a8a-4f7b-a7a4-374345c30b17.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Datum Gewijzigd'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6898be62-66f4-4422-87b8-c078c48860aa
		summarizeBy: none
		sourceColumn: Datum Gewijzigd

		variation Variation
			isDefault
			relationship: 76de0eee-6d1c-4672-ae17-5e64da9a91a0
			defaultHierarchy: LocalDateTable_440d5084-fae8-4d5f-8be9-307106ab9e02.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tijd Gewijzigd'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6425dab1-6669-499e-b430-1da28adcc922
		summarizeBy: none
		sourceColumn: Tijd Gewijzigd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Uren_Begroot
		dataType: double
		lineageTag: e1c120e3-f64c-42f6-993c-1a5ee1ac16a8
		summarizeBy: sum
		sourceColumn: Uren_Begroot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uren_Werkelijk
		dataType: double
		lineageTag: 046da4f4-ee9f-4ec2-855c-0cf238fc9560
		summarizeBy: sum
		sourceColumn: Uren_Werkelijk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uren_Verschil
		dataType: double
		lineageTag: 4e6319c9-04a4-4ed3-91a4-521573920741
		summarizeBy: sum
		sourceColumn: Uren_Verschil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: bd51a26b-27d8-4cdf-aadb-1cc85ab1e124
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05cb4810-da65-4527-b51d-5938ba0ebcf8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Periode
		dataType: string
		lineageTag: 388cd865-e544-42ff-abde-fe31ba6e0188
		summarizeBy: none
		sourceColumn: Periode

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: 233630ac-5617-4f7b-9111-f0d6a1dc9ff6
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: int64
		formatString: 0
		lineageTag: 4f9545b9-7000-4478-baee-336b23ba0b2c
		summarizeBy: count
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'C/A Formatie ID'
		dataType: int64
		formatString: 0
		lineageTag: 9b3b1b84-2c35-4566-9a9a-e1ab975fe413
		summarizeBy: none
		sourceColumn: C/A Formatie ID

		annotation SummarizationSetBy = Automatic

	partition 'Fact FormatiePlaats' = m
		mode: import
		queryGroup: Model
		source = ```
				let
				    Source = Json.Document(Web.Contents("https://86331.rest.afas.online/ProfitRestServices/connectors/CMC_Formatieplaats" & "?skip=-1&take=-1", [Headers=[Authorization="AfasToken PHRva2VuPjx2ZXJzaW9uPjE8L3ZlcnNpb24+PGRhdGE+Qjk5N0I1MjNGMzhENDgwNjgyRTA0NzQ4RkZCQUQ1RjU5MTA1OEU3QUEwQTQ0MDMxODlBNUVGNTNEMjFDREQ5MTwvZGF0YT48L3Rva2VuPg=="]])),
				    rows = Source[rows],
				    #"Converted to Table" = Table.FromList(rows, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}, {"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Formatieplaats", "Omschrijving"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"Geblokkeerd", type logical}, {"Naam_werkgever", type text}, {"Patientgebonden_functies", type text}, {"Soort_functie", type text}, {"Declarerend_Niet-declarerend", type text}, {"Service_Lines", type text}, {"Cluster_Afdeling", type text}, {"Omschrijving", type text}, {"Formatieplaats", type text}, {"Kostenplaats", Int64.Type}, {"Organisatorische_eenheid", type text}, {"Omschrijving_2", type text}, {"Functie", type text}, {"Omschrijving_3", type text}, {"Generieke_functienaam", type text}, {"Gebruiker", type text}, {"Type_functie", type text}, {"Naam", type text}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([Einddatum], "T"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Text Before Delimiter", "Eind Datum"}}),
				    #"Inserted Text Before Delimiter1" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Begindatum], "T"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Before Delimiter1",{{"Text Before Delimiter", "Begin Datum"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Begin Datum", type date}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "Begindatum", "Einddatum", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gewijzigd", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum"}),
				    #"Inserted Text Before Delimiter2" = Table.AddColumn(#"Reordered Columns", "Text Before Delimiter", each Text.BeforeDelimiter([Gewijzigd], "T"), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Text Before Delimiter2",{{"Text Before Delimiter", "Datum Gewijzigd"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Datum Gewijzigd", type date}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Changed Type3", "Text After Delimiter", each Text.AfterDelimiter([Gewijzigd], "T"), type text),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Inserted Text After Delimiter", {{"Text After Delimiter", each Text.BeforeDelimiter(_, "Z"), type text}}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Extracted Text Before Delimiter",{{"Text After Delimiter", "Tijd Gewijzigd"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Tijd Gewijzigd", type time}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type4",{"Geblokkeerd", "Naam_werkgever", "Patientgebonden_functies", "Soort_functie", "Declarerend_Niet-declarerend", "Service_Line_Type", "Service_Lines", "Cluster_Afdeling", "Formatieplaats", "Omschrijving", "Kostenplaats", "Organisatorische_eenheid", "Omschrijving_2", "Functie", "Omschrijving_3", "Generieke_functienaam", "FTE_Begroot", "Aantal_FTE", "Aantal_FTE_2", "Aantal_FTE_3", "Aantal_FTE_4", "Verschil", "Gebruiker", "Type_functie", "Naam", "Begin Datum", "Eind Datum", "Datum Gewijzigd", "Tijd Gewijzigd"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Aantal_FTE_2", type number}, {"Aantal_FTE", type number}, {"Aantal_FTE_3", type number}, {"Aantal_FTE_4", type number}, {"Verschil", type number}, {"FTE_Begroot", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type5", "Uren_Begroot", each [FTE_Begroot] * 8),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Uren_Werkelijk", each [Aantal_FTE] * 8),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Uren_Verschil", each [Verschil] * 8),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom2",{{"Uren_Begroot", type number}, {"Uren_Werkelijk", type number}, {"Uren_Verschil", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type6", each ([Naam_werkgever] = "Curacao Medical Center Exploitatie")),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Filtered Rows",{{"Kostenplaats", type text}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type7", "Year", each Date.Year([Begin Datum]), Int64.Type),
				    #"Merged Queries" = Table.NestedJoin(#"Inserted Year", {"Year"}, #"Dim Calendar", {"Year"}, "Dim Calendar", JoinKind.LeftOuter),
				    #"Expanded Dim Calendar" = Table.ExpandTableColumn(#"Merged Queries", "Dim Calendar", {"Date", "Month no. (leading zeros)"}, {"Date", "Month no. (leading zeros)"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Expanded Dim Calendar",{{"Aantal_FTE", "Werkelijk"}, {"Aantal_FTE_2", "Instroom"}, {"Aantal_FTE_3", "FTE uitstroom (zonder bepaalde tijd)"}, {"Verschil", "Verschil (excl)"}, {"Aantal_FTE_4", "Verschil"}, {"Organisatorische_eenheid", "OE"}, {"Month no. (leading zeros)", "Periode"}}),
				    #"Added Custom3" = Table.AddColumn(#"Renamed Columns4", "Year/Period", each Text.From([Year]) & "/" & Text.From([#"Periode"])),
				    #"Merged Queries1" = Table.NestedJoin(#"Added Custom3", {"Soort_functie"}, #"Dim Personeel Type OLD", {"Type Personeel"}, "Dim Personeel Type", JoinKind.LeftOuter),
				    #"Expanded Dim Personeel Type" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Personeel Type", {"Type Personeel ID"}, {"Type Personeel ID"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Dim Personeel Type", {"Cluster_Afdeling"}, #"Dim Cluster/Afdeling Formatieplaats", {"Cluster/Afdeling Formatieplaatsniveau"}, "Dim Cluster/Afdeling Formatieplaats", JoinKind.LeftOuter),
				    #"Expanded Dim Cluster/Afdeling Formatieplaats" = Table.ExpandTableColumn(#"Merged Queries2", "Dim Cluster/Afdeling Formatieplaats", {"C/A Formatie ID"}, {"C/A Formatie ID"})
				in 
				    #"Expanded Dim Cluster/Afdeling Formatieplaats"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

