table 'Fact Forecasting Medewerkers'
	lineageTag: 92aa7b64-6098-49bf-b67e-c200a2e13ec4

	column 'Medewerker ID'
		dataType: string
		lineageTag: 45845d3e-5c51-411d-b0ad-dfa812a8ad0e
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: 5ad1c3f9-2976-4e08-a1e6-e08d18ee0da2
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 79a9a20f-a4aa-4a62-bba9-1c0c2c3e9dfc
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening
		dataType: string
		lineageTag: b7313e0a-ace7-4862-b8a9-0541b42ee23a
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: ba9edb3d-c924-457f-897c-4349998123fc
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column Rapportagecockpit_omschrijving
		dataType: string
		lineageTag: 706afcd1-46e5-48d3-b6c6-3528f80c8c6d
		summarizeBy: none
		sourceColumn: Rapportagecockpit_omschrijving

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID (Dim MdW)'
		dataType: int64
		formatString: 0
		lineageTag: 314e2cb8-eff2-4f03-b264-2c8f81c48bbf
		summarizeBy: sum
		sourceColumn: Schaal ID (Dim MdW)

		annotation SummarizationSetBy = Automatic

	column 'Year Forecasting'
		dataType: string
		lineageTag: 77eb5422-2de6-46cb-b3f4-31d04bad970c
		summarizeBy: none
		sourceColumn: Year Forecasting

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 94b6115f-ed4b-4ed6-a346-25bc6cd8d42b
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column SchaalType
		dataType: string
		lineageTag: a7ccccb2-3a30-4d8e-a35f-8666a07f933c
		summarizeBy: none
		sourceColumn: SchaalType

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: a126f76f-4ae2-400e-a0c3-45197eba1212
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: 56e4f47d-2be2-4574-b260-9e1006282978
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column 'New Schaal ID (Trede Verhoging Actuals)'
		dataType: double
		lineageTag: e16a7a99-d271-4e63-8f6c-63990d91bfa0
		summarizeBy: sum
		sourceColumn: New Schaal ID (Trede Verhoging Actuals)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MAX Trede Actuals'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26f41efe-0db5-4ef3-8f2d-4708a31aa049
		summarizeBy: none
		sourceColumn: MAX Trede Actuals

		annotation SummarizationSetBy = Automatic

	column 'Trede Verhoging Forecasting'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9a3cec0c-18dd-42d8-ac7f-4f229df0466a
		summarizeBy: none
		sourceColumn: Trede Verhoging Forecasting

		annotation SummarizationSetBy = Automatic

	column 'New Schaal ID (Trede Verhoging Forecasting)'
		dataType: int64
		formatString: 0
		lineageTag: 6e20674b-bddb-4a6b-b88c-f9eab9b2b1ef
		summarizeBy: none
		sourceColumn: New Schaal ID (Trede Verhoging Forecasting)

		annotation SummarizationSetBy = Automatic

	column 'Period Forecasting (leading zeros)'
		dataType: string
		lineageTag: 6c2942dd-f896-4687-bd9e-e5d3fa0c9579
		summarizeBy: none
		sourceColumn: Period Forecasting (leading zeros)

		annotation SummarizationSetBy = Automatic

	column 'Year/Period Forecasting'
		dataType: string
		lineageTag: 25892536-f629-4418-b6a4-4003ae8370bd
		summarizeBy: none
		sourceColumn: Year/Period Forecasting

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: 954ad951-e857-4ffd-8881-fb65486f08f2
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MAX Trede Forecasting'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a615fde3-5822-4e2e-b758-1789735fbe0c
		summarizeBy: none
		sourceColumn: MAX Trede Forecasting

		annotation SummarizationSetBy = Automatic

	column 'FTE Forecasting'
		dataType: double
		lineageTag: 3a50b4ea-8d9e-44aa-aa8f-80c59e5e3c1c
		summarizeBy: sum
		sourceColumn: FTE Forecasting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Forecasting Medewerkers' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Table.Combine({#"Fact Personeels Kosten 2024", #"Fact Personeels Kosten 2025", #"Fact Personeels Kosten 2021", #"Fact Personeels Kosten 2023", #"Fact Personeels Kosten 2022"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Omschrijving_klant", "Omschrijving LC"}, {"Medewerker", "Medewerker ID"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"Medewerker ID", "LC", "Omschrijving LC", "Grootboekrekening", "Grootboekrekening_omschrijving", "FTE"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Year Forecasting", each Date.Year(DateTime.LocalNow()) + 1),
				    #"Invoked Custom Function" = Table.AddColumn(#"Added Custom", "Period Forecasting", each #"Forecasting Medewerker Date Function"([Year Forecasting])),
				    #"Expanded Period Forecasting" = Table.ExpandTableColumn(#"Invoked Custom Function", "Period Forecasting", {"Period"}, {"Period"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded Period Forecasting", {"Grootboekrekening"}, #"Dim Grootboek", {"Code Grootboek"}, "Dim Grootboek", JoinKind.LeftOuter),
				    #"Expanded Dim Grootboek" = Table.ExpandTableColumn(#"Merged Queries", "Dim Grootboek", {"Rapportagecockpit_omschrijving"}, {"Rapportagecockpit_omschrijving"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded Dim Grootboek", each ([Rapportagecockpit_omschrijving] = "19 Lonen en salarissen" or [Rapportagecockpit_omschrijving] = "20 Sociale lasten" or [Rapportagecockpit_omschrijving] = "21 Overige personeelskosten")),
				    #"Merged Queries1" = Table.NestedJoin(#"Filtered Rows", {"Medewerker ID"}, #"Dim Medewerker", {"Medewerker ID"}, "Dim Medewerker Details", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker Details" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Medewerker Details", {"Anniversary Month", "Kostenplaats", "Schaal ID"}, {"Anniversary Month", "Kostenplaats", "Schaal ID"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Dim Medewerker Details",{{"Schaal ID", "Schaal ID (Dim MdW)"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns1", {"Medewerker ID", "LC", "Grootboekrekening", "Period"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Duplicates", {"Medewerker ID"}, #"Fact Medewerker MAX Schaal/Trede Actuals", {"Medewerker ID"}, "Fact Medewerker MAX Schaal/Trede Actuals", JoinKind.LeftOuter),
				    #"Expanded Fact Medewerker MAX Schaal/Trede Actuals" = Table.ExpandTableColumn(#"Merged Queries2", "Fact Medewerker MAX Schaal/Trede Actuals", {"New Schaal ID (Trede Verhoging Actuals)", "MAX Trede Actuals"}, {"New Schaal ID (Trede Verhoging Actuals)", "MAX Trede Actuals"}),
				    #"Added Custom1" = Table.AddColumn(#"Expanded Fact Medewerker MAX Schaal/Trede Actuals", "Trede Verhoging Forecasting", each if [Anniversary Month] = [Period] then true else false),
				    #"Merged Queries3" = Table.NestedJoin(#"Added Custom1", {"New Schaal ID (Trede Verhoging Actuals)"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries3", "Dim SchaalType", {"SchaalType", "MAX Trede"}, {"SchaalType", "MAX Trede"}),
				    #"Added Custom2" = Table.AddColumn(#"Expanded Dim SchaalType", "New Schaal ID (Trede Verhoging Forecasting)", each if [Trede Verhoging Forecasting] = true and [MAX Trede Actuals] = false and ([SchaalType] = null or [SchaalType] = "Andere OVK") then ([#"New Schaal ID (Trede Verhoging Actuals)"] + 1) else if [#"New Schaal ID (Trede Verhoging Actuals)"] = null then [#"Schaal ID (Dim MdW)"] else [#"New Schaal ID (Trede Verhoging Actuals)"]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Period Forecasting (leading zeros)", each Text.PadStart(Text.From([Period]),2,"0")),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Year/Period Forecasting", each Text.From([Year Forecasting]) & "/" & Text.From([#"Period Forecasting (leading zeros)"])),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom4",{{"MAX Trede", "MAX Trede Forecasting"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns2",{{"FTE", type number}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type", "FTE Forecasting", each [FTE]/100),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom5",{{"FTE Forecasting", type number}, {"Period Forecasting (leading zeros)", type text}, {"Year/Period Forecasting", type text}, {"SchaalType", type text}, {"Kostenplaats", type text}, {"Trede Verhoging Forecasting", type logical}, {"New Schaal ID (Trede Verhoging Forecasting)", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

