table 'Test Fact Salaris Extrapolated'
	lineageTag: 74b808d4-59f9-4669-b126-a9dd390d2318

	column Jaar
		dataType: double
		lineageTag: 9b1e05da-bfa1-41a3-95ad-207c2e53ed35
		summarizeBy: sum
		sourceColumn: Jaar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Boekingsperiode
		dataType: double
		lineageTag: 6ee97b7a-d13c-48c6-8b8a-c3fea557c408
		summarizeBy: sum
		sourceColumn: Boekingsperiode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Medewerker ID'
		dataType: string
		lineageTag: 6d15c196-19d4-4c67-b8c4-3485dae944d0
		summarizeBy: none
		sourceColumn: Medewerker ID

		annotation SummarizationSetBy = Automatic

	column Kostenplaats
		dataType: string
		lineageTag: 047281ba-910b-4d4c-ba2c-ebf02576e5de
		summarizeBy: none
		sourceColumn: Kostenplaats

		annotation SummarizationSetBy = Automatic

	column LC
		dataType: string
		lineageTag: c5f6185f-d805-4cf7-a2e6-6b77bf97e8bd
		summarizeBy: none
		sourceColumn: LC

		annotation SummarizationSetBy = Automatic

	column 'Omschrijving LC'
		dataType: string
		lineageTag: 8a45d75c-6c84-4e1b-846a-2762827ba7e6
		summarizeBy: none
		sourceColumn: Omschrijving LC

		annotation SummarizationSetBy = Automatic

	column Waarde
		dataType: double
		lineageTag: 745541d7-3668-4050-ba6c-fe55a18a4ad6
		summarizeBy: sum
		sourceColumn: Waarde

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bedrag_credit
		dataType: double
		lineageTag: fdf917b3-d8a6-4efe-a1fb-be5998dccc79
		summarizeBy: sum
		sourceColumn: Bedrag_credit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Grootboekrekening
		dataType: string
		lineageTag: af609f8c-e524-46db-8f28-5335b9da339a
		summarizeBy: none
		sourceColumn: Grootboekrekening

		annotation SummarizationSetBy = Automatic

	column Grootboekrekening_omschrijving
		dataType: string
		lineageTag: 24b11141-cc1e-4340-a6d9-88fa352f8a5d
		summarizeBy: none
		sourceColumn: Grootboekrekening_omschrijving

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: d1192a4c-73b5-4f11-aa5d-a2f6276c1822
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Naam_werkgever
		dataType: string
		lineageTag: c63f0f37-c907-41ea-a10c-87d86f7f30f1
		summarizeBy: none
		sourceColumn: Naam_werkgever

		annotation SummarizationSetBy = Automatic

	column IsExtrapolated
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 807eabbd-b555-4efc-8328-be755d045120
		summarizeBy: none
		sourceColumn: IsExtrapolated

		annotation SummarizationSetBy = Automatic

	column OriginalBoekingsperiode
		dataType: double
		lineageTag: 9b812408-9add-436a-84c9-5a4ab4f95685
		summarizeBy: sum
		sourceColumn: OriginalBoekingsperiode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Boekingsperiode (leading zeros)'
		dataType: string
		lineageTag: 0b88c538-57a8-4fb1-9f23-72998e5be66d
		summarizeBy: none
		sourceColumn: Boekingsperiode (leading zeros)

		annotation SummarizationSetBy = Automatic

	column Year/Period
		dataType: string
		lineageTag: f146aba1-104c-498a-90f3-a3e924a0d1d7
		summarizeBy: none
		sourceColumn: Year/Period

		annotation SummarizationSetBy = Automatic

	column 'Schaal ID'
		dataType: int64
		formatString: 0
		lineageTag: 22438e20-3e94-4cd4-90fe-731ec3f573b6
		summarizeBy: count
		sourceColumn: Schaal ID

		annotation SummarizationSetBy = Automatic

	column 'Type Personeel ID'
		dataType: string
		lineageTag: 23a1d429-4368-406a-b9f0-0e574fbbea1e
		summarizeBy: none
		sourceColumn: Type Personeel ID

		annotation SummarizationSetBy = Automatic

	column 'Anniversary Month'
		dataType: int64
		formatString: 0
		lineageTag: be00ecf2-8cda-4aa1-b1f0-2832ff72a56e
		summarizeBy: sum
		sourceColumn: Anniversary Month

		annotation SummarizationSetBy = Automatic

	column 'Schaal.SchaalType'
		dataType: string
		lineageTag: 6f21f96f-2201-4293-a2b8-2c4a0ffe4203
		summarizeBy: none
		sourceColumn: Schaal.SchaalType

		annotation SummarizationSetBy = Automatic

	column 'Schaal.MAX Trede'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 19de6ad6-4cab-4462-9b97-f2ba046da29b
		summarizeBy: none
		sourceColumn: Schaal.MAX Trede

		annotation SummarizationSetBy = Automatic

	column 'Trede Verhoging'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3b8feca5-4cf2-4a7e-bea3-ca8da535c46b
		summarizeBy: none
		sourceColumn: Trede Verhoging

		annotation SummarizationSetBy = Automatic

	column 'Bedrag (OLD)'
		dataType: double
		lineageTag: a8391429-7b60-4747-b7c6-961fc0425ca9
		summarizeBy: sum
		sourceColumn: Bedrag (OLD)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Schaal ID (New)'
		dataType: double
		lineageTag: 66e187dd-88ba-458e-9135-8edb998d41c2
		summarizeBy: sum
		sourceColumn: Schaal ID (New)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salaris (Schaal ID New)'
		dataType: double
		lineageTag: 69b807e2-b621-477a-98c9-b605796b4499
		summarizeBy: sum
		sourceColumn: Salaris (Schaal ID New)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bedrag (New)'
		dataType: double
		lineageTag: d347a8ba-609a-4050-b3ca-c25945b1fe3e
		summarizeBy: sum
		sourceColumn: Bedrag (New)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Indexering
		dataType: double
		lineageTag: 9b0ee0e6-281e-4722-b54e-be288ce0efe4
		summarizeBy: sum
		sourceColumn: Indexering

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Index Name'
		dataType: string
		lineageTag: b8944b18-0568-4cbd-9f4d-8d4b75819310
		summarizeBy: none
		sourceColumn: Index Name

		annotation SummarizationSetBy = Automatic

	column 'Bedrag Incl Indexering'
		dataType: double
		lineageTag: 8bd6ce89-ef73-4843-a627-bf3292b675fd
		summarizeBy: sum
		sourceColumn: Bedrag Incl Indexering

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Test Fact Salaris Extrapolated' = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = #"Extrapolatie Salaris Indexering Actuals Test"(#"Fact Salaris Indexering Actuals Source (2)"),
				    #"Changed Type9" = Table.TransformColumnTypes(Source,{{"Boekingsperiode", type number}, {"Jaar", type number}, {"Waarde", type number}, {"Bedrag_credit", type number}, {"FTE", type number}, {"OriginalBoekingsperiode", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type9", "Boekingsperiode (leading zeros)", each Text.PadStart(Text.From([Boekingsperiode]),2,"0"), type nullable text),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Year/Period", each Text.From([Jaar]) & "/" & Text.From([#"Boekingsperiode (leading zeros)"]), type nullable text),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"IsExtrapolated", type logical}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Medewerker ID"}, #"Dim Medewerker", {"Medewerker ID"}, "Dim Medewerker", JoinKind.LeftOuter),
				    #"Expanded Dim Medewerker" = Table.ExpandTableColumn(#"Merged Queries", "Dim Medewerker", {"Schaal ID", "Type Personeel ID", "Anniversary Month"}, {"Schaal ID", "Type Personeel ID", "Anniversary Month"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim Medewerker", {"Schaal ID"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType" = Table.ExpandTableColumn(#"Merged Queries1", "Dim SchaalType", {"SchaalType", "MAX Trede"}, {"Schaal.SchaalType", "Schaal.MAX Trede"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Dim SchaalType",{{"Schaal.SchaalType", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Trede Verhoging", each if [IsExtrapolated] = false or [Type Personeel ID] = "Z_3" or [#"Schaal.MAX Trede"] = true then false else if ([IsExtrapolated] = true and [Boekingsperiode] >= [Anniversary Month] and [#"Schaal.MAX Trede"] = false) then true else null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Trede Verhoging", type logical}}),
				    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Bedrag (OLD)", each [Waarde] - [Bedrag_credit]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom3",{{"Bedrag (OLD)", type number}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type3", "Schaal ID (New)", each if [Trede Verhoging] = true and [Type Personeel ID] <> "Z_3" then ([Schaal ID] + 1) else [Schaal ID]),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom4",{{"Schaal ID (New)", type number}}),
				    #"Merged Queries2" = Table.NestedJoin(#"Changed Type4", {"Schaal ID (New)"}, #"Dim SchaalType", {"Schaal ID"}, "Dim SchaalType", JoinKind.LeftOuter),
				    #"Expanded Dim SchaalType1" = Table.ExpandTableColumn(#"Merged Queries2", "Dim SchaalType", {"Salaris"}, {"Salaris"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Expanded Dim SchaalType1",{{"Salaris", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type5",{{"Salaris", "Salaris (Schaal ID New)"}}),
				    #"Added Custom5" = Table.AddColumn(#"Renamed Columns", "Bedrag (New)", each if [Trede Verhoging] = false then [#"Bedrag (OLD)"] else [#"Salaris (Schaal ID New)"]),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom5",{{"Bedrag (New)", type number}}),
				    #"Added Custom6" = Table.AddColumn(#"Changed Type6", "Dim Indexering", each #"Dim Indexering Actuals"),
				    #"Expanded Indexering Actuals" = Table.ExpandTableColumn(#"Added Custom6", "Dim Indexering", {"Indexering", "Index Name"}, {"Indexering", "Index Name"}),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Expanded Indexering Actuals",{{"Indexering", type number}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type7", "Bedrag Incl Indexering", each if [Boekingsperiode] >= 7 and ([Type Personeel ID] = "Z_1" or [Type Personeel ID] = "Z_3" or [Type Personeel ID] = "Z_10" or [Type Personeel ID] = "Z_15") or [Schaal.SchaalType] = "Andere OVK" then [#"Bedrag (New)"] else if [Boekingsperiode] < 7 then [#"Bedrag (New)"] else ([#"Bedrag (New)"] * [Indexering]) + [#"Bedrag (New)"]),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom7",{{"Bedrag Incl Indexering", type number}, {"Index Name", type text}, {"Medewerker ID", type text}, {"Kostenplaats", type text}, {"LC", type text}, {"Omschrijving LC", type text}, {"Grootboekrekening", type text}, {"Grootboekrekening_omschrijving", type text}, {"Naam_werkgever", type text}})
				in
				    #"Changed Type8"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

