// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
FILTER(
    'Dim Medewerker',
    'Dim Medewerker'[Medewerkers in Fact Forecasting] = 1 && 
    'Dim Medewerker'[Flag 4105000 - Gratificaties] = 1 && 
    'Dim Medewerker'[Status_dienstverband] = "In dienst" && 
    'Dim Medewerker'[Dienstjaren Forecasting] = 25
)
